### ISSUE TITLE
px68k (Sharp X68000) core? 

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#10]
https://github.com/libretro/px68k-libretro

Pretty please?

**Comment by KMFDManic** [comment]
This one may not be as easy to do!  But, I did get another Core going, for now:)  Atari 5200!  Just updated it to the set, and will post a video:)  I will keep tabs on px68k and Atari ST!

**Comment by gingerbeardman** [comment]
Thanks man, they would be the cherry on the cake. Amazing work so far!

**Comment by Restart-Point** [comment]
Ha, I was going to ask the same thing! I want to play Nemesis '90 Kai! That was a home computer though.....keyboards input is a pain to deal with without a physical keyboard.

**Comment by atrac17** [comment]
Patiently waiting lol

**Comment by KMFDManic** [comment]
This is actually one of the more stubborn Cores to be able to run on the Mini NES/SNES.  It runs fine on PC:)  Due to the extra work involved in getting this to work, as far as recompiling the code, it will remain in my agenda.  But, it may not be as doable as, say Atari ST.  Even that one is a little stubborn!  But, rest assured, I will try to get every single possible one I can get going!  I already got several dozen:)

**Comment by KMFDManic** [comment]
This core is currently incompatible with the NES/SNES Classic, and would require some rewrite and recompiling of the code, unfortuately.  There are a good dozen+ Cores with similar issues, related to compatibility.  This also goes for The Atari ST Core.  Doing such rewrite or compile can be as easy as a couple hours, or as hard as many, many hours.  I will still keep it in my longterm agenda!

**Comment by atrac17** [comment]
Okay, thanks. I'll definitely be making a contribution to your efforts on
Wednesday. I really appreciate you working this and updating the SNES9x
core. I'll email you sometime Wednesday. Thanks again...

**Comment by KMFDManic** [comment]
@atrac17 have you had previous email contact with me?  Thanks for the appreciation:)

**Comment by KMFDManic** [comment]
@gingerbeardman @Restart-Point @atrac17 Got it working, and will post in next Update:)

**Comment by gingerbeardman** [comment]
WOWEE! Will set up my SNESC again this weekend. GOOD JOB
