### ISSUE TITLE
retroarch video settings locked, force save = reset

### ISSUE THREAD

**Issue by bankaiprimera** [KMFDManic/NESC-SNESC-Modifications#100]
* hakchi2 CE version: v2.30
  * retroarch used (filename): KMFDManic-NESC-SNESC-Cores.3-13-18.7z
  * hmod(s) used by the game you are having problems with (filenames): all of them
  
When using the KMFDManic-NESC-SNESC-Cores.3-13-18.7z retroarch cores and v2.30 hakchi, certain video settings are locked and after changing them they can't be saved. When I exit retroarch (with save on exit) it isn't saved and when using the "overwrite preset core save" in retroarch it crashes/resets to the dashboard.

The following settings seem to be locked:
- Threaded video = on (I want it off because of the added latency)
- Vsync = off (I would turn it on, after disabling threaded video)
- Hard GPU sync = off (I used to have it turned on with "lighter weight" cores such as genesis plus GX, because of reduced latency)

Is this a "feature" of can it be fixed?

**Comment by shedeus** [comment]
I would occasionally have trouble writing the settings to config with save to core.  Have you tried save to game instead?

From there, you can FTP into your mini console, grab the config files and manually save them back into the core defaults.  Kind of a pain, but that's how I got around the issue.  Besides, it's a great idea to back the config files anyway, so you don't lose all your settings with each update.

**Comment by KMFDManic** [comment]
@bankaiprimera Add CloverSNES from Xtras/Hakchi2 Folder, as a game, open that, make the changes you want, then Configuration Save.  Changing settings is sometimes dependent on the Core you are trying to change them with.  But, globally, there isn't an issue.

**Comment by KMFDManic** [comment]
https://www.reddit.com/r/miniSNESmods/comments/84r0xk/openbor_test_retroarch_aspect_fixes_explained/

Let me know if you still need any help:)

**Comment by bankaiprimera** [comment]
Thanks a lot man, I'm gonna check it out!

**Comment by bankaiprimera** [comment]
Everything works like a charm, I can customize core settings now just fine - except for 1 setting: threaded video. 

I have it disabled by default, but for FBA core I want it enabled (because of the bigger load on CPU compared to for example GenesisPlusGX core). When I enable threaded video and save it to the FBA2012 core preset, it doesn't save the setting. It is still disabled ingame.

Other video settings work just fine to save to core preset.

**Comment by shedeus** [comment]
Have you tried manually updating the config file for FBA with a "threaded_video=false" flag (not the exact working btw) using FTP?  That should do the trick

**Comment by bankaiprimera** [comment]
@shedeus I added CloverSNES from Xtras/Hakchi2 Folder, which should do the same as FTP'ing files, because your not in an active core. Didn't help.

**Comment by KMFDManic** [comment]
@bankaiprimera @shedeus Any personalized changes you guys want, simply let me know.  I will also followup with CRT on stock borders, as well as incorporate other things:)

**Comment by shedeus** [comment]
You know what make me flip out?  Is if I could change "skip frame" and "auto frame skip" defaults for neo_ppsspp core.  I like what it does to stability, but "skip frame 1" and "auto frame skip enable" defaults turn all my games into 60fps slideshows.  I change those back to frame skip 0 and disable auto frame skip for all my games, even if they run a bit slow.

If you could allow us to overwrite those settings as user set defaults to the core config, I would LOVE it!!

**Comment by KMFDManic** [comment]
@bankaiprimera Will be posting a Fixed RetroArch later today:)  @shedeus You may want to watch my PSP Performance Upgrade Videos, and try out the PSP Xtreme Add-On, to help with some of the more CPU Intensive Games.
