### ISSUE TITLE
Retroarch key mapping w/ PS3 controller

### ISSUE THREAD

**Issue by edimusxero** [KMFDManic/NESC-SNESC-Modifications#102]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.1.0
  * retroarch used (filename): _km_retroarch_171_xtreme_3_20_18
  * hmod(s) used by the game you are having problens with (filenames): Castlevania: Symphony of the Night
  
### Step 2: Describe the problem:
  
The triggers do not appear to be working at all, I cannot map them.  I also cannot map the right analog stick.
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by edimusxero** [comment]
I think I resolved this by downgrading the 8bitdo retro receiver firmware to version 1.05 beta.  All buttons seem to be working (with the exception of the L3 / R3) as of now.  I need to test further so I am leaving this open.

**Comment by KMFDManic** [comment]
I was going to say, this tutorial seems to be the best bet:)  You probably came across it!

https://www.reddit.com/r/miniSNESmods/comments/7w4aw7/8bitdo_sn30_pro_sf30_pro_correct_setup_for_near/?st=JF2IB3RQ&sh=e72dfbe6﻿

**Comment by edimusxero** [comment]
yea, I found something similar.  I don't think PSX games used L3/R3 very often (none that I know of) and most didn't even use the right analog stick so I think for now I am set.  Thank you for the reply and your continued excellent work!

**Comment by KMFDManic** [comment]
You're welcome:)  Just posted another Update:)

**Comment by edimusxero** [comment]
Excellent.  Time to reflash.  Now if only we could get the option to flash new games with out re writing the entire directory we'd be set!  *wink wink*

**Comment by KMFDManic** [comment]
We already do, it's called manual copying and pasting:)  I actually never synch or export at all:)

**Comment by edimusxero** [comment]
Ohhhh, thanks for the tip,  i would've never thought of that
