### ISSUE TITLE
Sega genesis lock-on cart bios files not working

### ISSUE THREAD

**Issue by shedeus** [KMFDManic/NESC-SNESC-Modifications#104]
* hakchi2 CE version: 1.10 CE / USB HOST
  * retroarch used (filename): _km_retroarch_171_xtreme_3_28_18.hmod
  * hmod(s) used by the game you are having problens with (filenames): km_master_bios_module_3_28_18.hmod with lock on bios files: areplay.bin, ggenie.bin, sk.bin, sk2chip.bin
  
### Step 2: Describe the problem:

After installing the bios files for the lock on cart (areplay.bin, ggenie.bin, sk.bin, sk2chip.bin) using the km_master_bios_module_3_28_18.hmod, the lock-on mode fails to function for all sega genesis games.  However, when I re-install the old hmod from several weeks/months ago (_km_bios_gen_plus_gx_lockon_opt_5_8_17.hmod) the lockon technology works as intended.  It seems you need more than just those bios files for it to work?  FYI!!

**Comment by KMFDManic** [comment]
You need to go into Core Options and enable lock on technology. Those files are all you need:)

**Comment by shedeus** [comment]
Yes, I had enabled in core options!  After enabling lock-on, the game would restart but knuckles would not show up!  Then when I tried installing the old hmod: _km_bios_gen_plus_gx_lockon_opt_5_8_17.hmod knuckles would show in up sonic 3 after enabling lock-on.  I just tried it again and it doesn't seem to work with only the bios files, but works when I install that old hmod...  weird!!

**Comment by KMFDManic** [comment]
Which way are you installing hmods

**Comment by shedeus** [comment]
I installed lock-on bios files using "km_master_bios_module_3_28_18.hmod" folder.  Then enabled lock-on technology but no games worked with lock-on cart.

When that didn't work, I uninstalled the master biso folder, then installed "_km_bios_gen_plus_gx_lockon_opt_5_8_17.hmod"

_km_bios_gen_plus_gx_lockon_opt_5_8_17.hmod works great after enabling lock-on.

**Comment by KMFDManic** [comment]
Just installed folder with JUST those files, on both NAND, as well as USB-HOST, and then loaded Core from RetroArch Icon, Loaded Content, Loaded Sonic 3, Chose Core again, and enabled Lock-On, it reset and showed Sonic & Knuckles.  No issues whatsoever.  Which hakchi and RetroArch are you on?

**Comment by KMFDManic** [comment]
You can send me a message on Reddit, if you continue to have issues, and I can help you with an alternative workaround.  But, it is working absolutely fine for me.

**Comment by KMFDManic** [comment]
Factory Reset shouldn't be needed.  You should be able to Custom Kernel Flash.  I had zero issues running exact same files via NAND and USB.
