### ISSUE TITLE
Donkey kong 2 jump man 

### ISSUE THREAD

**Issue by 123doglpc** [KMFDManic/NESC-SNESC-Modifications#105]
### Step 1: Describe your setup:

  * hakchi2 CE version: _____
  * retroarch used (filename): _____
  * hmod(s) used by the game you are having problens with (filenames): _____
  
### Step 2: Describe the problem:
  Hi what rom and mod to run this on usb host thanks email me at wildog555@yahoo.com and post a video on YouTube of it running bye
  * _____
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
dkongx.zip with MAME 2003, via _Dummy Folder method.  I will need to do a small video about how to properly add it with hakchi2 CE, since it is one of a few games that glitch, when attempting to add by normal means.
