### ISSUE TITLE
My SFC Mini Lockup

### ISSUE THREAD

**Issue by laikinman** [KMFDManic/NESC-SNESC-Modifications#106]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.1.0
  * retroarch used (filename): _km_retroarch_171_xtreme_3_31_18
  * hmod(s) used by the game you are having problens with (filenames): km_master_bios_module_3_28_18.hmod
  
### Step 2: Describe the problem:
  
access to the path 'disksys.rom'is denied.  System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive)
   於 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive)
   於 com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() 於 C:\hakchi2\WorkerForm.cs: line 603
   於 com.clusterrr.hakchi_gui.WorkerForm.StartThread() 於 C:\hakchi2\WorkerForm.cs: line 323
Closing main form
Saving config

My Update km_master_bios_module_3_28_18.hmod after SFC Mini Lockup Can't Retore and install and any updates ......

### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
You likely have security permissions and or firewall and or virus protection false positives.

**NES Classic - Access Denied - Let's Fix It!:)**

https://youtu.be/mGooTybpodM

**Comment by laikinman** [comment]
thank you so much !!! now can fix it :+1:
