### ISSUE TITLE
Zanac X Zanac doesn't work when I choose Zanac Neon, it stops at checking memory card pop up.

### ISSUE THREAD

**Issue by nevmind** [KMFDManic/NESC-SNESC-Modifications#107]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.10
  * retroarch used (filename): _km_retroarch_171_3_5_18.hmod
  * hmod(s) used by the game you are having problens with (filenames): _km_pcsx_rearmed_neon_1_28_18.hmod

  
### Step 2: Describe the problem:
  
  * In Zanac X Zanac , Choose Zanac Neon game.
    and then I can see message of checking memory card.
    and then it doen't proceed any more and stops.
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
Requires BIOS to work properly.  Not all games do. But, many will.  There is a Master BIOS Module in my Core Set, as well as a couple videos posted about this.

**SNES Classic - Master BIOS Module Overview**

https://youtu.be/uJCEQ_-wLbU

You can also private message me under MDFMKanic on Reddit, for direct assistance:)

**Comment by nevmind** [comment]
I have sent private message on Reddit for assistance.

**Comment by KMFDManic** [comment]
I can confirm, from a personal test, that BIOS are in fact the reason the game will work or not work:)  Issue closed, will followup with you on Reddit.
