### ISSUE TITLE
Nes Classic CRT Filter

### ISSUE THREAD

**Issue by bbaggins19** [KMFDManic/NESC-SNESC-Modifications#108]
Hello!  Thanks for the update.  I looked in the 3/31 KMFDManic and did not see the NES classic CRT filter hack.  Is there a specific one I should use for the NES classic with the latest 3/31 KMFDManic release?  I am using Nes classic, with no usb, and hakchi2 CE 1.1.0.  Thanks.

**Comment by bbaggins19** [comment]
Wow!  Thanks so much!  You Rock!

**Comment by KMFDManic** [comment]
Enjoy:)  Just retested, and can confirm CRT still works for NESC, with current RetroArch Standard, as well as Xtreme:)
