### ISSUE TITLE
mame2003 extreme and IREM titles

### ISSUE THREAD

**Issue by shedeus** [KMFDManic/NESC-SNESC-Modifications#109]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.10 CE / USB HOST
  * retroarch used (filename): 1.71 EXTREME 3/31
  * hmod(s) used by the game you are having problens with (filenames): mame2003 extreme 3/31nt
  
### Step 2: Describe the problem!
  
IREM titles have corrupted sound (e.g. Hook, Rtype leo, In the hunt, Undercover cops) again.  Please take a look!  Thanks i:n advance!
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
Reposted one that will work, and amended release notes to reflect that, til I get things fixed:)  Thanks for the heads up!

**Comment by shedeus** [comment]
You're the boss dude!  Thanks so much :)

**Comment by KMFDManic** [comment]
Fixed and the kov performance upgrade will be posted today, too.

**Comment by shedeus** [comment]
Thanks so much!!!
