### ISSUE TITLE
Irem games sound issues mame/snes mini

### ISSUE THREAD

**Issue by lethalcocktail** [KMFDManic/NESC-SNESC-Modifications#11]
Hi , first, thanks for the great job you did so far its really appreciated .
The problem is i that i have sound issues with 2 games in particular
made by Irem : in the hunt and gunforce 2 .
they run on both fba and mame 2003 but the sound is horrible or choppy.
i have tried every versions with every modules but none of them seem to work properly.
Any ideas or solution ? thanks

**Comment by gingerbeardman** [comment]
Have you tried to see if the issue is present on MAME on your PC (or another platform more powerful than NESC/SNESC?)

**Comment by lethalcocktail** [comment]
The games and sounds are working perfectly on my pc with mame , the problem seems to be only when i run it on the snes mini with retroarch .

**Comment by gingerbeardman** [comment]
It's possible the mini isn't powerful enough to run it. 

I wonder if it's possible to view CPU usage in MAME core?

**Comment by blackjack-78** [comment]
Same thing here...I can confirm the"crappy"sound on Irem games (with Gunforce 2 too, and  Undercover Cops...no matter the version). 
I've read that some of Irem games are running on "Irem M92"hardware...http://www.system16.com/hardware.php?id=747
Maybe it's a way to investigate...

**Comment by Restart-Point** [comment]
Yup, all late-period Irem games run badly on the mini SNES, with any core. Just have to hope for better-optimised cores in the future I guess

**Comment by KMFDManic** [comment]
Irem, and Midway, etc, are incredibly complex, as far as Audio Emulation.  Try Mortal Kombat Games, for example...They tend to be low volume.  It is one thing to emulate the game, but an entirely other to accurately pull off the sound.  Even on PC, some games do not fully realize the sound potential.  This is also why we have many different rom sets!  But, it also acts as a double edged sword, as far as the fine line between accurate emulation and the integrity of the original code:)
