### ISSUE TITLE
Canoe borders and CRT filter do not work with mame2010

### ISSUE THREAD

**Issue by shedeus** [KMFDManic/NESC-SNESC-Modifications#110]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.2 / SNESc USB HOST
  * retroarch used (filename): _km_retroarch_171_xtreme_4_21_18
  * hmod(s) used by the game you are having problens with (filenames): _km_mame2010_4_17_18
  
### Step 2: Describe the problem:
  
arcade games run with mame2010 do not display canoe borders or CRT filter (pressing L button) with SNESc / USBHOST!
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
I installed RetroArch Xtreme, had a few games with /bin/mame2010, held down L1, while loading the games, and Borders loaded flawlessly.  Let me know if you still have any trouble.  I had 3 others test it, too, and none had issues.  Remember, L1 while loading game from main UI to toggle on/off for just that game...And, R1, to toggle on/off, globally, for all games:)

**Comment by KMFDManic** [comment]
Keep me posted if you need anymore help:)
