### ISSUE TITLE
Question | How to Update new CORE Set from you to the SNES Mini

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#111]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.2_____
  * retroarch used (filename): _km_retroarch_171_xtreme_4_19_18
  * hmod(s) used by the game you are having problens with (filenames): some_____
  
### Step 2: Describe the problem:
  
  * How to Update new CORE Set from you to the SNES Mini
I didnt saw a information on how to update a Coreset from you.
my questions:

- can i just install the new core to snes mini ?
- do i need to uninstall the old core first and then install the new one ?
cheers
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by gingerbeardman** [comment]
> do i need to uninstall the old core first and then install the new one ?

yes

**Comment by AntiFly** [comment]
thanks dude didnt realised that this is the option i wanted, worked :-)
