### ISSUE TITLE
Amstrad CPC | FB Alpha 2016, analog move not working

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#113]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.2._____
  * retroarch used (filename): 1.7.1 extreme_____
  * hmod(s) used by the game you are having problens with (filenames): fbalpha2016_____
  
### Step 2: Describe the problem:
  
  * mapping to analog x/y not workgin, just nothing happens.
  

i just tested afburner.zip from a fbalpha x.39 set for CPC. the firebutton and missle is working well but im not possible to move the fighter...is there anything missing?? bug??
cheers

**Comment by AntiFly** [comment]
got exact same error on PPSSPP with Kingdom Hearts Birth by Sleep. cant move...
i read there is maybe an issue with the SNES controller and AXIS/DPAD?

do you think we can do anything here to get it work?

**Comment by KMFDManic** [comment]
Try going into retroarch options, controls, toggle gamepad (analog), to just gamepad. This helps many games, ps1, as well.

**Comment by AntiFly** [comment]
i already tried that and i tried to disable a secondary option to "none" (i dont have the correct name in mind atm). but not helped anyway, restart of snesmini does not helped either.
its weird because the settings seem reasonable to me and retroarch detected the controller and it is set correct so far i can tell.

**Comment by KMFDManic** [comment]
After Burner is easily remapped with MAME 2003 Xtreme.  You can temporarily remap R1 as R2, then tap R1 to pull up MAME Options.  And, from there, Inputs for This Game:)

I do similar thing, here

https://youtu.be/z3OiBtltu-Y

For PSP, N64, etc, you will likely need to do this

https://youtu.be/7wRsPdOrmmk

**Comment by KMFDManic** [comment]
And, for CPC Amstrad, remapping is done this way

https://youtu.be/91XA_0xfN_U

**Comment by AntiFly** [comment]
he thanks for supplieing the tuts , i watched them. looks pretty nice to remap the keys on mame...
to be honest i set all of my arcade to fba2016 and want the leftovers newer one to a newer mame2014 core.. but i guess a mixup is not possible cause they use both qsound.zip ?

anyway, do you think i could use such remap with FBA2016 too?
cheers

**Comment by KMFDManic** [comment]
Best to use MAME 2003/2000 for Remapping:)  Otherwise, you'd need to use RetroArch Settings, Controls, with the other Arcade Cores.  Qsound, I use for MAME 2003, MAME 2010, FBA 2012, FBA 2016.  Same qsound works with all of these Cores.  You can copy qsound.zip into Master BIOS Module in my Core Set, inside system folder, along with any other BIOS...Then, install as an HMOD, and will be fine on any CPS2 Games, as long as you have the appropriate rom sets:)  I wouldn't recommend MAME 2014, as it takes up too much space and isn't as optimal on the Mini as MAME 2010 and earlier:)

**Comment by AntiFly** [comment]
there was a information about "new" and "old" i thought it has to be differed thats why i thought i might need diff setups here...
anyway i tested the psp game and its not working with the snes controller, every setting is ignored. i guess thats the issue with the digital move button which is mapped to the analogue but the analogue is mapped to other settings ingame...
i prefer the fba2016 core , its very handy to use and splittet now the left overs not avail up to mame2003 and mame2014. thanks for infos dude
