### ISSUE TITLE
C8 Error on PPSSP Core while playing Metal Slug Anthology (sound gone first)

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#114]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.7.2_____
  * retroarch used (filename): 1.7.1 extreme_____
  * hmod(s) used by the game you are having problens with (filenames): _your ppssp core + addons____
  
Black Screen with "Nintendo" C8 Error.

**Comment by KMFDManic** [comment]
Make sure full command line does not contain 7z in it.  Hakchi tends to 7z compress when compress games when adding option is enabled. You can right click on the game in hakchi, decompress it, resynch.  Command line must be /bin/ppsspp

**Comment by KMFDManic** [comment]
And, after changing any retroarch settings for any psp games, restart, resume, as issues will occur with graphics and sound, otherwise.  

Keep me posted.  Also, good to do disk check on PC of flash drive occasionally.

**Comment by AntiFly** [comment]
hey there,
yes i saw the video about your tests on psp ;)
i have the psp in .iso and the psx in .pbp file structure..
