### ISSUE TITLE
Addon | Music Addon for advanced music hack

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#119]
Hi there,

you might lookin for some cool "retro" music , i converted some of the "best" cracktros/keygens in dubmode to wav. its verey enjoyable too me, so if you wanna do that into your package feel free..

its for USB-Host users.

[Download](http://www.share-online.biz/dl/VXDTL38PP3S5
)
cheers

**Comment by KMFDManic** [comment]
Thanks for the awesomeness of trying to help make things more fun and cool for many others.  When I do next Update, I will toss this into an Xtras Folder, and do a credit, accordingly:)  Obviously, it would be too large to have in the main Download.  But, the other Mega NZ link will be perfect for it:)

**Comment by AntiFly** [comment]
yeh , youre welcome ;)
