### ISSUE TITLE
Is it possible to make run "Night Slashers"properly ?!

### ISSUE THREAD

**Issue by blackjack-78** [KMFDManic/NESC-SNESC-Modifications#12]
Hi KMFDManic-San.
I would like to ask you if it's possible to make run "in a good way"Night Slashers?!
For me the bests results i have with this game is on mame2010 with the japanese rom(the most gore version...yeppp!!!^^).
I've read too that some of Data East games are running on"Data East ARM6" hardware(Night Slashers include).
http://www.system16.com/hardware.php?id=949&gid=18932#18932
I hope it can help...

**Comment by KMFDManic** [comment]
No, unfortunately, it is cpu intensive, and on the Mini NES/SNES, it isn't an optimally running game!  Any game that runs that slow, pretty much is shot as far as running on the Mini NES/SNES in any conceivably better form.  Sega Saturn, 3DO, follow the same pattern.
