### ISSUE TITLE
Freeintv stopped working?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#122]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.4
  * retroarch used (filename): _km_retroarch_171_standard_4_28_18
  * hmod(s) used by the game you are having problens with (filenames): _km_freeint_4_28_18
  
### Step 2: Describe the problem:
  
  * Recently, when updating my Retroarch Freeint stopped working. Immediately resets when trying to load ANY Intellivision rom. Tried using both .int and .freeintv in the command line but instant returns to snes classic menu. All bios are in the correct folder ('system') and going to CORE INFORMATION shows they are recognised.
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
BIOS are required to run FreeINT, exec.bin and grom.bin, which can be installed via the Master BIOS Module in my Core Set.  Copy them into the root, system folder.  Let me know if you still need any help.  Note, I am posting an Updated Core Set in a short while.  You may want to retest using the latest one.

**Comment by bolton80** [comment]
Hi, 
 
Thanks for replying. The BIOS are in the correct folder. But still nothing. I wonder if the command line might be wrong? Here’s an example of the format I am using... /bin/int /var/games/CLV-Z-JORYA/Shark!_Shark!.int.7z
 
As I said, Freeint worked fine a while back, so I don’t know how I’, having so many problems with it now.
 
As a side note, I’ve been desperately trying to get CD-I working with no success (really want to play Hotel Mario and a few other rare CD-I exclusives again), but no luck. Does it actually work at the moment? If so, any chance of a video? I’m sure lots of people would like to play Hotel Mario (many of them for the first time).
 
Amiga CD32 would be fun too, I had one back then, and it had some worthwhile games.
 
Thanks again for all your work on these releases. I’m really enjoying being able to put so many classics on such a convenient little system.
 
Steve

**Comment by gingerbeardman** [comment]
I'll try this in the morning. I use _FreeIntv_ (note the v at the end) a fair bit and have even submitted some fixes to the source code.

**Comment by KMFDManic** [comment]
@bolton80 I can confirm the Core works perfectly.  Keep in mind, not ALL Games will work.  I would suggest using Tron: Deadly Discs as a good test Game.  Also, make sure you do not have TOO many games/hmods flashed at one time.  Even though it may appear you have the Core installed, you may not.  There are, of course, other factors...as well.  But, as of right now, 5-12-18 FreeINT Core works perfectly:)  Keep me posted:)

**Comment by bolton80** [comment]
Hi KMDFManic and gingerbeardman. Thanks for responding. I've tried yesterday's new build and still nothing. So clearly there's a problem with my set-up. I wonder if some kind of config file may be corrupt or something, which is stopping the newer versions of FreeINTV from working? Does this sound likely, and if so, any idea how I would go about 'resetting' the config for FreeINTV so I can start from scratch? (Without restoring the whole SNES Mini to factory settings!).

**Comment by gingerbeardman** [comment]
OK, I just tested mine () and it's running. I have two folders of Intellivision games.

From some related RetroArch documentation:
> ### BIOS
> lr-freeintv requires two Intellivision BIOS files to be placed in the libretro 'system' folder:
> 
> | Function | Filename* | MD5 Hash |
> | --- | --- | --- | 
> | Executive ROM | `exec.bin`  | `62e761035cb657903761800f4437b8af` |
> | Graphics ROM | `grom.bin` | `0cd5946c6473e42e8e4c2137785e427f` |
> 
> * BIOS filenames are case-sensitive

**Comment by KMFDManic** [comment]
@bolton80 Flash Custom Kernel, Reinstall the Core/BIOS, synch LESS in Games.  Try to avoid being too close to the available MB.

Now for the very sad news.  CD-I Games with Videos in them, will not work...This pretty much makes CD-I a completely lost cause.  They didn't support those with video due to legal reasons.  Additionally, I am pretty certain the CD-I element is broken on our end!  I wanted to get it going, but it may not be easy!

**Comment by bolton80** [comment]
I've finally worked out what went wrong with my FreeINTV. Somehow the game roms became corrupted. I deleted them all from Hakchi, replaced them with new copies and it's working perfectly now. Thanks for all the tips though.

It's a shame about the CD-I situation.

**Comment by gingerbeardman** [comment]
Glad you've got it sorted! I'm currently trying to debug a collision problem with the emulator that makes playing _Chip Shot - Super Pro Golf_ and other games quite difficult.

This issue can be closed.
