### ISSUE TITLE
o2em problem/input?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#125]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.4
  * retroarch used (filename): km_RetroArch Standard (4-28-18)
  * hmod(s) used by the game you are having problens with (filenames): km_O2EM (4-28-18)
  
### Step 2: Describe the problem:
  
The emulator seems to work fine in terms of loading the games. But I immediately get to a screen which asks something like 'Number of players?' and I can't find a way to get past this, or an way to configure the controller to enter 1 or 2. Is there a way around this please?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by gingerbeardman** [comment]
Have a look at this video: https://youtu.be/vt8HpIDGtEs
