### ISSUE TITLE
Amiga .uae path problem

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#126]
### Step 1: Describe your setup:

  * hakchi2 CE version:1.2.4
  * retroarch used (filename): km_RetroArch Standard (4-28-18)
  * hmod(s) used by the game you are having problens with (filenames): km_P-UAE (4-28-18)
  
I have followed online guides for adding Amiga games, and I think I'm nearly there. The problem I have is setting my paths in the (game).uae files when I add them.

I am using a USB stick which contains my hakchi folder, with a layout like this...
![1](https://user-images.githubusercontent.com/39167008/40269357-2124c83a-5b6d-11e8-9393-da6c4173527e.JPG)

My Amiga games are inside the '001' folder (each in their own "CLV..." folders of course).

The one I am using as a test is Agony, for which I used the specific games template from the core-set.

I haven't seen any guides that refer to this particular layout before, and I think that is why I'm struggling with setting my path in the .uae file. I've tried lots of combinations, but none have worked.  
kick31.rom is in the USB's: hakchi ->libretro -> system
WHDLoad.hdf the USB's: hakchi ->libretro -> system
agony.hdf and agony.uae are in the USB's: hakchi -> games -> snes-eur-> 001-> CLV-V-ZMPCC

Can you advise what I should use for the following...

kickstart_rom_file= ? ? ? ? ? ? ? ? ? ? /kick31.rom
hardfile=read-write,32,1,2,512,/ ? ? ? ? ? ? ? ? ? ? ? ? ? /WHDLoad.hdf
hardfile=read-write,32,1,2,512,/ ? ? ? ? ? ? ? ? ? ? /agony.hdf

As a side note, when I add my games to hakchi on my PC, it stores them in the hakchi -> games_originals folder. I 'Export' them to the USB using Hakchi.

My Hakchi command line is... /bin/puae /var/games/CLV-V-ZMPCC/agony.uae

I'd love to get these running, but I'm stuck. Please help!
  * _____
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by bolton80** [comment]
Hi. I've gone into Hakchi -> games-eur -> CLV... and you are right. The games are not in there. Instead I have found them in Hakchi -> games_snes -> CLV.

I don't mind taking the 'linked' option off, if you can tell me how.

Ideally, I think I saw a method mentioned in: [](https://www.reddit.com/r/miniSNESmods/comments/8dbqv7/guide_playing_amiga_games_on_the_snes_classic/) which shows this method...

> **USB-HOST Tricks**
> Thanks to u/hilly for this! Once you are familiar with the process or already have a good understanding of what to do then you can employ various ways of streamlining the process even more. If you're using USB-HOST and Linked Export the following is the easiest and fastest way of adding games!
> •Create a folder on your USB drive outside of Hakchi e.g. USB: amiga and use it to store all your Amiga BIOS and WHDLoad games.
> •There will then be a single fixed path to all your files. If you update your UAE templates to point to this fixed path then all you have to do in terms of UAE configuration when adding a game is to add the name of your game's HDF file i.e the last few lines of your UAE will look like this -
> 
> ​
> kickstart_rom_file=/media/amiga/kick31.rom
> hardfile=read-write,32,1,2,512,/media/amiga/WHDLoad.hdf
> hardfile=read-write,32,1,2,512,/media/amiga/GAME_NAME.hdf
> 
> •When you create your game HDF file you can write it direct to USB:amiga so that when you add your UAE file to Hakchi you're all set and there's no further configuration or copying files required!
>

**Comment by bolton80** [comment]
Having said that, I am happy to use another method if it is straightforward, including the _dummy folder you mentioned. Just as long as I can access them directly from the SNES mini menu in the folder system. Thanks for your help!

**Comment by KMFDManic** [comment]
In my Xtras/Amiga Folder, look at the linked export Templates, and modify yours to match appropriate paths.  When done, show me your exact finalized uae file.  Notepad++ should be used for any and all modifications:)

**Comment by KMFDManic** [comment]
Test it out and see if it loads.  But, I would recommend using this additional, aggressive adjustment, to help it run somewhat better.

```use_gui=no
show_leds=true
chipset=ocs
cpu_type=68000
cpu_speed=10
finegrain_cpu_speed=5120
chipmem_size=4
fastmem_size=4
immediate_blits=true
gfx_center_vertical=simple
gfx_center_horizontal=simple
gfx_width=640
gfx_height=512
gfx_framerate=2
collision_level=none
sound_output=exact
sound_channels=stereo
sound_frequency=44100
kickstart_rom_file=/etc/libretro/system/kick31.rom
hardfile=read-write,32,1,2,512,/etc/libretro/system/WHDLoad.hdf
hardfile=read-write,32,1,2,512,/media/hakchi2CE/games_snes/001/CLV-V-ZMPCC/agony.hdf
```

**Comment by KMFDManic** [comment]
Do you by chance use Reddit?  If so, message me under the name MDFMKanic

**Comment by bolton80** [comment]
Just sent a message to MDFMKanic (presuming the spelling wasn't a typo. Please confirm receipt.

gingerbreadman - Thanks for the link. Will look into that too.

**Comment by KMFDManic** [comment]
Keep me posted:)  If still stuck, I can help you out:)

**Comment by bolton80** [comment]
Wow, it's actually working! Thank you so much Kyland! Can I ask one more quick question? What is the best resolution to set in the quick menu > options menu? Or does it value for every game?

**Comment by KMFDManic** [comment]
If you look at the Templates included in the Core Set Update, they have appropriate Resolution, defaulted.  If it isn't big enough for you, you can go into RetroArch, Video Settings, and toggle Integer on/off.  I generally leave it on for most Cores, as it appropriately matches Aspect Ratio.  And, of course, you can do Bezel Mode, where you hold down L1 while loading a game from the Main UI (after selecting Canoe Border) to toggle it on/off for that individual Game.  R1 will do it globally for all Games:)
