### ISSUE TITLE
Gingerbeardman, DanTheMan827, madmonkey, markwkidd, BsLeNuL, you all need to stop being such incredible assets:)

### ISSUE THREAD

**Issue by KMFDManic** [KMFDManic/NESC-SNESC-Modifications#127]
### Step 1: Describe your setup:

  * hakchi2 CE version: X Edition
  * retroarch used (filename): X Edition
  * hmod(s) used by the game you are having problens with (filenames): X Edition
  
### Step 2: Describe the problem:
  
  * I absolutely value anything and everything Gingerbeardman has done on my Github.  He is an exceptional asset, and does more than would ever be expected of him:)  Great work deassembling the Canoe Emulator, as well:)  But, I thank Gingerbeardman, DanTheMan827, madmonkey, markwkidd, BsLeNuL, and countless others, for truly and honesty taking such an interesting in helping me further things for the Scene:)  You all simply rock:)
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by gingerbeardman** [comment]
It's a team effort!
