### ISSUE TITLE
_km_puae_5_21_18 showing under Unknown

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#128]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.5
  * retroarch used (filename): KMFDManic-NESC-SNESC-Cores.5-21-18.7z

fyi the new puae is showing under uknown modules ... mistake?

**Comment by KMFDManic** [comment]
Thanks for the heads up.  I will hotfix it shortly:)

**Comment by KMFDManic** [comment]
@AntiFly Thank you, again!:)

**HOTFIX 5-22-18**

Amiga PUAE Core had minor bug.  Personal thanks to AntiFLy for the heads up!  Here is a temporary link to it, if you do not want to redownload entire Set:)  Just delete _km_puae_5_21_18, and replace with the fixed _km_puae_5_22_18.  I also updated it into the Mega NZ Link!  Sorry for any inconvenience:)  Here is the link:)

https://ufile.io/wvtwr

**Comment by AntiFly** [comment]
HI mate,

got it.

Your scph5500.bin… files dated from 1996 are these the new ones or is the file otherwise spelled?

Thank you

 

Von: Kyland K <notifications@github.com> 
Gesendet: Mittwoch, 18. Juli 2018 02:42
An: KMFDManic/NESC-SNESC-Modifications <NESC-SNESC-Modifications@noreply.github.com>
Cc: AntiFly <mazterz@gmx.at>; Mention <mention@noreply.github.com>
Betreff: Re: [KMFDManic/NESC-SNESC-Modifications] _km_puae_5_21_18 showing under Unknown (#128)

 

This will be here temporarily, respond once you grabbed it:)

https://ufile.io/y224x

**Comment by AntiFly** [comment]
Hi KMFDManic,

 

yeah most appreciated, cant wait to test it ^^

 

Von: Kyland K <notifications@github.com> 
Gesendet: Mittwoch, 18. Juli 2018 11:27
An: KMFDManic/NESC-SNESC-Modifications <NESC-SNESC-Modifications@noreply.github.com>
Cc: AntiFly <mazterz@gmx.at>; Mention <mention@noreply.github.com>
Betreff: Re: [KMFDManic/NESC-SNESC-Modifications] _km_puae_5_21_18 showing under Unknown (#128)

 

@AntiFly <https://github.com/AntiFly>  I will send an Updated one later today.

**Comment by KMFDManic** [comment]
Cat just bumped the keyboard and accidentally updated things:)

https://ufile.io/6l2hd

**Comment by AntiFly** [comment]
Hi there,

 

there is a discrepance to my and the .md file which is telling how to put the bios …

md. file -> sgb_bios.bin

your deployment -> sgb.bios.bin

MGBA = gba_bios.bin (Game Boy Advance),  gb_bios.bin (Game Boy), gbc_bios.bin (Game Boy Color), sgb_bios.bin (Super Game Boy)

 

just info on the kmf…xtrafolder 

new version of Notepad++ available

new version of monkey audio available

new version of 7zip available

new version of DTLiteInstaller available

new version of isobuster_install available

 

for my guessing you could remove these files from your repository (no need):

hakchi2-dantheman827-linked-export-1-24-18.zip

hakchi-gui-win32(official)(1-5-18).zip

hakchi-gui-win32(official)(1-14-18).zip

hakchi-gui-win32(official)(11-28-17).zip

fix.7z

fonts.7z

boot.png

.\ HAKCHI2\

.\ HOTFIX\

 

it seems like you want to archive some of the hmods etc..

you may create a directory _archive to put everything into which is no more in use but just for past reading….

Like ->

_USB-HOST\hmods

_USB-HOST\READMES

HAKCHI2

HOTFIX

MXYZPTLK

SFROMS

Etc…

 

 

On PSP I would miss a .txt which explains why there is a psp directory with emulators for psp… this is confusing me cause I really don’t know why this is there ?!?

Psp saves … structure already changed, do a user has to do something huh ?

 

 

I really appreciate all your hard work and of the other team members… ;-)

Thank you for that.

 

 

 

Von: mazterz@gmx.at <mazterz@gmx.at> 
Gesendet: Mittwoch, 18. Juli 2018 18:35
An: 'KMFDManic/NESC-SNESC-Modifications' <reply@reply.github.com>
Betreff: AW: [KMFDManic/NESC-SNESC-Modifications] _km_puae_5_21_18 showing under Unknown (#128)

 

Hi KMFDManic,

 

yeah most appreciated, cant wait to test it ^^

 

Von: Kyland K < <mailto:notifications@github.com> notifications@github.com> 
Gesendet: Mittwoch, 18. Juli 2018 11:27
An: KMFDManic/NESC-SNESC-Modifications < <mailto:NESC-SNESC-Modifications@noreply.github.com> NESC-SNESC-Modifications@noreply.github.com>
Cc: AntiFly < <mailto:mazterz@gmx.at> mazterz@gmx.at>; Mention < <mailto:mention@noreply.github.com> mention@noreply.github.com>
Betreff: Re: [KMFDManic/NESC-SNESC-Modifications] _km_puae_5_21_18 showing under Unknown (#128)

 

@AntiFly <https://github.com/AntiFly>  I will send an Updated one later today.

**Comment by KMFDManic** [comment]
I temporarily renamed sgb_bios.bin to sgb.bios.bin to test mGBA SGB Enhanced Support.  Yes, it should be sgb_bios.bin  I will Update the HMOD for next "Release":)  Thanks for the overall audit, and I will also look into fixing up a few things in the Xtras!

**Comment by AntiFly** [comment]
Hi,

 

ive tested your bios files with r-type delta psx , it froze after 10minutes testing. 

And was bit of choppy, it runs slower on hires mode as on normal mode.

 

Did I something wrong ?

 

Von: Kyland K <notifications@github.com> 
Gesendet: Donnerstag, 19. Juli 2018 18:47
An: KMFDManic/NESC-SNESC-Modifications <NESC-SNESC-Modifications@noreply.github.com>
Cc: AntiFly <mazterz@gmx.at>; Mention <mention@noreply.github.com>
Betreff: Re: [KMFDManic/NESC-SNESC-Modifications] _km_puae_5_21_18 showing under Unknown (#128)

 

I temporarily renamed sgb_bios.bin to sgb.bios.bin to test mGBA SGB Enhanced Support. Yes, it should be sgb_bios.bin I will Update the HMOD for next "Release":) Thanks for the overall audit, and I will also look into fixing up a few things in the Xtras!

**Comment by KMFDManic** [comment]
@AntiFly Sorry, when running Hi Res mode, go into Core Options and set to 1.  

PS1 and N64 Games can both randomly crash due to dynamic recompiler.  U can offset this by going into RetroArch settings, video settings, and toggling srgb on and off when games slow down.

R-Type Delta didn't crash for me. Try testing again with frame skip set to 1.

**Comment by AntiFly** [comment]
“Sorry, when running Hi Res mode, go into Core Options and set to 1.”
you mean frame skip or something else?

Is it may possible its cause of my version of the game, ive got a pal game converted to pbp?

 

Von: Kyland K <notifications@github.com> 
Gesendet: Donnerstag, 19. Juli 2018 21:36
An: KMFDManic/NESC-SNESC-Modifications <NESC-SNESC-Modifications@noreply.github.com>
Cc: AntiFly <mazterz@gmx.at>; Mention <mention@noreply.github.com>
Betreff: Re: [KMFDManic/NESC-SNESC-Modifications] _km_puae_5_21_18 showing under Unknown (#128)

 

@AntiFly <https://github.com/AntiFly>  Sorry, when running Hi Res mode, go into Core Options and set to 1.

PS1 and N64 Games can both randomly crash due to dynamic recompiler. U can offset this by going into RetroArch settings, video settings, and toggling srgb on and off when games slow down.

R-Type Delta didn't crash for me. Try testing again with frame skip set to 1.

**Comment by KMFDManic** [comment]
@AntiFly Pal games can certainly have issues.  But, still try what I mentioned.

**Comment by KMFDManic** [comment]
@AntiFly Yes, frame skip set to 1.  It won't really appear like its frame skipping.
