### ISSUE TITLE
New N64 Core not available through set emulation Core?

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#129]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.5
  * hmod(s) used by the game you are having problens with (filenames): KMFDManic-NESC-SNESC-Cores.5-29-18
  
### Step 2: Describe the problem:
  
  * Ive added some N64 games, with file extention .z64. i cant select parallel to emulation core via gui cause its just not listed. ive installed the core bevore to snes mini.
* its not listed within known cores and also not listed in unassigned cores.
* games are listet to glupen64 while manual changed to parallel
-> 
[Screenshot](https://abload.de/img/xxxb6si4.png)

is this related to the core or to hackchi ce?

**Comment by KMFDManic** [comment]
You have to manually change it to /bin/parallel The Core is so new it is not added into Hakchi2 CE, as of yet, as far as detecting it as a Core.  Parallel is best for games such as Mario 64!  So, do not expect it to run as many games as Glupen:)  But, feel free to let me know how things test out!  I will relay this information to Team_Shinkansen when they are able to implement it:)  They are always busy with one thing or another, hehe:)

**Comment by AntiFly** [comment]
id gave it a short test on n64, each about 15min play..
 (no freeze in 15min)

Mupen64plus
-> 
bomberman 64
Donkey Kong 64
Kirby 64
legend of zelda ocrana of time
mario kart 64
Star Wars Episode I: Racer

parallelei
->
Diddy Kong Racing
Dr. Mario 64
F-ZERO X
Super Mario 64
Wipeout 64

wipeout and fzero were sluggy at the main menue, but play was quite ok.

im afraid yoshis island des not play at all on paralellei and crashes after some 3-5min on mupen64plus (sad)

Conker's Bad Fur Day does not work at paralellei and mupen64 at all...
