### ISSUE TITLE
[BUG] Some modules of the 10-26 update doesn't work (games won't start)

### ISSUE THREAD

**Issue by hoderer** [KMFDManic/NESC-SNESC-Modifications#13]
games won't start, had to revert back to stella 10-23 (the one before), which is working good.

EDIT: There may be more broken modules in this update. Tried VICE, but - same as stella - games won't start.

EDIT 2: I installed the following modules on my SNESC (EU-Version):

_km_vice_x64_10_23_17 = NOT WORKING
_km_genesis_plus_gx_10_24_17 = NOT WORKING
_km_glupen64_6_26_17 = NOT WORKING
_km_stella_10_23_17 = NOT WORKING
_km_mednafen_pce_fast_10_23_17 = NOT WORKING
_km_snes9x_10_25_17 = WORKING
_km_mgba_10_18_17 = WORKING

If there's anything I could do to help, let me know. Thanks for your awesome work! Another thing: Could you provide that super mario 64 door icon you use on your device? Saw it in your videos but couldn't find it anywhere... that would be nice! Thanks alot!

**Comment by gingerbeardman** [comment]
How come this closed? What was the resolution?

**Comment by blackjack-78** [comment]
Hi! 
The cores have been just re-updated...a few hours ago! 
You just need to re-download the cores-set...again and install the new ones...😉
Hope this can help you...And sorry if my english is crappy...🙃
