### ISSUE TITLE
Mod's missing 

### ISSUE THREAD

**Issue by werebear1977** [KMFDManic/NESC-SNESC-Modifications#132]
### Step 1: Describe your setup:
I am unable to find the _km_retroarch_extreme_filters_    and the km_snes9x_dual_core  ....... Have they been renamed in the folder?

**Comment by KMFDManic** [comment]
There is no need for SNES9X Dual Cores anymore.  Now, there are just SNES9x2002, SNES9x2005, SNES9x2010, and SNES9x2016  If only ONE is installed, use /bin/snes  If more than one is installed, use 
/bin/snes02  /bin/snes05  /bin/snes10  and/or /bin/snes16

km_retroarch_extreme_filters is now known as _km_retroarch_xtreme_shaders_add-on_6_19_18
