### ISSUE TITLE
Game compat? Shienryu

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#133]
### Step 1: Describe your setup:

  * hakchi2 CE version: hakchi2_CE_1.2.5_Release
  * retroarch used (filename): KMFDManic-NESC-SNESC-Cores.6-19-18
  * hmod(s) used by the game you are having problens with (filenames): mame2003_xtreme
  
Hi dude,

ive tried to get Shienryu (shienryu.zip) working for mame2003, mame2010 or mame2014. but unfortunally its not working to me.
could you maybe double check for me on this , if the game is working... "should work" ?
cheers

**Comment by KMFDManic** [comment]
Requires STVBIOS, if it works at all:)  So have stvbios.zip in same directory as the game, and see if it works for you.  If NOT, I would recommend running the PS1 Version, Gekioh: Shooting King, which should work without issue:)

**Comment by AntiFly** [comment]
yes ps1 version is working well, will trie with stvbios.
how do you determine the bios needed ?

**Comment by KMFDManic** [comment]
Generally, you can use same BIOS for the many of the Arcade Cores, aside from ones such as NEO-GEO, which have changed several times.  qsound.zip works fine for me for CPS2 on all Cores.  STVBIOS, I feel, will run incredibly slow and be almost unplayable, though.

**Comment by AntiFly** [comment]
ive extracted stvbios from mame2010 set and put it into the shienryu.zip which should work for my understanding as "leading"bios if its near to the files. but retroarch quits almost instantly after starting this.

so im unsure where the problem is at the moment, cause of the mame cores itself i suggest it should work (at least for pc)
