### ISSUE TITLE
Mame2003 Xtreme running way too fast?!?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#136]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.5
  * retroarch used (filename): _km_retroarch_172_xtreme_6_19_18
  * hmod(s) used by the game you are having problens with (filenames): _km_mame2003_xtreme_6_19_18
  
### Step 2: Describe the problem:
  
  * Suddenly my MAME2003 games have started running way too fast (around 3x normal speed). I'm not sure how this happened, and I can't find any options or controls to adjust this. I tried uninstalling/reinstalling the hmod, but it hasn't made any difference. Any ideas please?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by gingerbeardman** [comment]
Have you activated fast forward by mistake?

**Comment by bolton80** [comment]
How can I check this? I can't find a fast forward option or control?

**Comment by gingerbeardman** [comment]
Start and Select to get to RetroArch menu, then it's in the framerate menu, or input menu to see if any button is set to do that function

**Comment by bolton80** [comment]
Tried looking everywhere, both within retroarch and Mame. Can't find a framerate menu or any function listed to 'fast forward'. Could you be more specific please?

**Comment by bolton80** [comment]
That fixed it! Thank you Kyland (and also to gingerbeardman for his support). I think it must have happened during a tense 2-player game of World Cup '90 I was playing with my son. Much appreciated as always!
