### ISSUE TITLE
Tengai Makyou Zero Not Working

### ISSUE THREAD

**Issue by idontlikepie** [KMFDManic/NESC-SNESC-Modifications#14]
I'm not sure if I'm doing something wrong, but I've installed the new and updated cores, but I still can't get the game to run correctly. For a period of time, I could at least get the game to launch to the Data Error screen, but now it doesn't seem to be doing even that. I've tried the patched and unpatched versions, placing XML files in the rom's directories...what am I missing.

**Comment by blackjack-78** [comment]
Hi!
Make sure of a few things...(i  fact, i had the same problems and now in can run the game)
First, you will need...to install retroarch and the snes9x core with no numbers for the version(not the "2000"ones...).
In second place,  check if you have the good rom(tengai makyou zero [J], the "shonen jump"one doesn't work with the patch...)and patch this"little  baby"...😎
And last, when you're gonna install "the beast", be sure to put to put " --retroarch" at the end of the command line(the space between the two is necessary).
Hope this can help you 😁.

Ps: sorry if my english is bad...^^

**Comment by blackjack-78** [comment]
Hi! You will need the patched version...Just be sure to put" --retroarch" at the end of the command line(once the rom is installed in your games, on the hakchi2 menu{ the space between the two is recquired...}).
Hope this can help you( it will work...i mean...😎).

**Comment by blackjack-78** [comment]
Hi! You will need the patched version...Just be sure to put" --retroarch" at the end of the command line(once the rom is installed in your games, on the hakchi2 menu{ the space between the two is recquired...}).
Hope this can help you( it will work...i mean...😎).
I had the same problem...

**Comment by KMFDManic** [comment]
Thanks for jumping to the answer before I got here, blackjack-78:)  Not everyone realizes --retroarch is the way to go for instances like this:)
