### ISSUE TITLE
PUAE Xtreme not working?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#140]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.5
  * retroarch used (filename): _km_retroarch_172_xtreme_8_11_18.hmod
  * hmod(s) used by the game you are having problens with (filenames): _km_puae_xtreme_8_11_18.hmod
  
### Step 2: Describe the problem:
  
I've uninstalled _km_puae_6_6_18.hmod and then installed _km_puae_xtreme_8_11_18.hmod. Now my previously working Amiga games (command line eg: /bin/puae /usr/share/games/CLV-7-UFJXU/cannon1.uae) no longer work. What am I doing wrong please?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
I retested it and it works fine.  But, if you do not properly uninstall previous one, it may not.  I added another Command Line, so it can be dual installed with old P-UAE.  So, use /bin/puae-xtreme

https://ufile.io/ztz2x

**Comment by bolton80** [comment]
Now this is strange... I was still struggling, so I've uninstalled Hakchi and 'Factory Reset' for good measure. Then I've set everything up again. PUAE and PUAE-Xtreme are still not working. What confuses me more is that the same games work fine with UAE4ARM,

For example...
/bin/uae4arm /usr/share/games/CLV-7-UFJXU/cannon1.uae 
...runs Cannon Fodder in UAE4ARM

But, if I change the command line to...
/bin/puae /usr/share/games/CLV-7-UFJXU/cannon1.uae
or
/bin/puae-xtreme /usr/share/games/CLV-7-UFJXU/cannon1.uae

...it doesn't work. Just returns directly to the SNES Classic menu. I have the 2 latest versions of PUAE and Xtreme installed.

My cannon1.uae file looks like this...

use_gui=no
show_leds=true
chipset=ocs
cpu_type=68000
chipmem_size=4
fastmem_size=4
gfx_center_vertical=simple
gfx_center_horizontal=simple
sound_channels=mixed
kickstart_rom_file=/etc/libretro/system/kick31.rom
hardfile=read-write,32,1,2,512,/etc/libretro/system/WHDLoad.hdf
hardfile=read-write,32,1,2,512,/var/games/CLV-7-UFJXU/cannon1.hdf

Any ideas?

**Comment by KMFDManic** [comment]
You may have been changing command lines incorrectly.  Once you change them, you need to make sure you completely close Hakchi, then reopen it, then resynch/reexport the games.  Also, try this one...

/bin/puae-xtreme /var/games/CLV-7-UFJXU/cannon1.uae

It is starting to seem as if the desktop files didn't save properly.  If you use "Reset" Kernel, it would uninstall all HMODS.  Then, you could install JUST PUAE Xtreme, RetroArch Xtreme, and whatever else you need, and should be fine.  Keep me posted.  Main thing is to always close Hakchi after changing command lines, to ensure they save.

**Comment by bolton80** [comment]
Tried updating the command line as you recommended. Still nothing.

By the way, I notice some of my games automatically have a "/var/games/" command line, while others have a "/usr/share/games/" command line. Which is correct?

**Comment by KMFDManic** [comment]
Try this, once any other game is loaded, pull up RetroArch Settings, then Load Core, then see if you can load P-UAE that way.  Let me know how many P-UAE Cores and what other Cores show up.  I tested this, and it is working on my end.  I had a few others test, and it is working for them, as well.

**Comment by bolton80** [comment]
Right, I did what you said. I loaded a game using UAE4ARM, then went to the Retroarch menu and loaded the PUAE Xtreme core. When I 'Resumed' retroarch, it did not crash. It just stayed on a blank black/greenish screen until I quit.

I have _km_puae_xtreme_8_14_18 and _km_puae_6_6_18.hmod cores installed, with the latest Retroarch. I have a lot of other cores installed, but when I re-installed Hakchi and everything from scratch a few days ago, I began with only the PUAE cores, and had the same problem then.

Does this tell you anything please?

**Comment by KMFDManic** [comment]
If you can, send me a message on Reddit, again, under MDFMKanic.  Like one of the last issues you previously had, I think this is another conflict.  I am not having any problems on my end.  I had a few others test, and they are fine, too.  It is likely a goof with your set-up, which of course I can help on:)  Looking forward to the message and will help you figure things out by tomorrow!

**Comment by KMFDManic** [comment]
If you still need help, let me know:)  But, you should be able to just use Module Uninstall Tab, then install latest P-UAE Xtreme, and be fine.
