### ISSUE TITLE
Super Game Boy border not pixel perfect

### ISSUE THREAD

**Issue by agufungus** [KMFDManic/NESC-SNESC-Modifications#141]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.4.1
  * retroarch used (filename): km_RetroArch 172 Xtreme (8-11-18)
  * hmod(s) used by the game you are having problems with (filenames): km_Gambatte (7-14-18)
  
### Step 2: Describe the problem:
  
  * It's something minor that I've noticed, but the Super Game Boy border, and by extension, the Game Boy screen are not pixel perfect. Compare with the SGB support in mGBA where both the borders and the screen are pixel perfect.  
  * As an additional suggestion, would it be possible to add support for a Game Boy Color border, and a Game Boy Advance border (when using mGBA, that is)?

**Comment by agufungus** [comment]
Yes, that border. Integer scaling doesn't seem to apply when that border is activated.

**Comment by KMFDManic** [comment]
I will look into adding an alternative border that won't override video settings.

**Comment by KMFDManic** [comment]
I will add a Super Game Boy Border that is static, for next Update.
