### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by panic2099** [KMFDManic/NESC-SNESC-Modifications#143]
### Step 1: Describe your setup:. reg nes mini

  * hakchi2 CE version: _____hackchi 2.3.0
  * retroarch used (filename): _____
  * hmod(s) used by the game you are having problens with (filenames): _____
  
### Step 2: Describe the problem: I know nothing about computers so please forgive my ignorance .i learned how to do the mods &hacks from youtube videos.the problem I am having is I cant do anything but add games & sync them.if If I try to flash my custom or orginal kernel or add mods or try to uninstall I get a pop up saying     c:\users\carol\downloads\kachchi:2.30\hackchi2\data\fes1.bin not found     is this what you refer to as the busy box code in your video? could you please give me some insight on these issues thank you for your time&help
  
  * _____
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
@panic2099 Try this.

**Comment by KMFDManic** [comment]
I am assuming your issue is sorted, since you haven't gotten back.  But, I would also suggest you consider updating to Hakchi 3.4.1, since it is actively worked on a daily basis.  Feel free to let me know if you are still stuck!
