### ISSUE TITLE
Atomiswave / Naomi compatibility List

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#145]
Tested GDroms (Atomiswave2Naomi) converted:

Demolish Fist (working)
Dolphin Blue (working)
King of Fighters NeoWave (working)
Metal Slug 6 (working)
Metal Slug 6 Violent (working)
Rumblefish (working)
Rumblefish 2 v4 (working)
NeoGeo Battle Coliseum (working)
Knights of Valour The Seven Spirits_Fixed (working)
Samurai Showdown VI Samurai Spirits v4 (working, major grafic glitches, low performance)
King of Fighters NewWave (not working, just black screen)
King of Fighters XI_v5_AllFightersUnlocked (working)
Guilty Gear Isuka (works great, speed great)
Guilty Gear X v1.5 (works great, speed great)
Capcom_vs_SNK_Millenium_Fight_2000_Pro (error 02)
Ghost_Squad_vA_1GB (Chihiro, error 01, controls)
Ghost_Squad_vA_512MB (Chihiro, error 01, controls)
Guilty_Gear_XX_Reload (error 02)
Gun Spike (working, major grafic glitches, unplayable)
Ikaruga v3 (working, controls drop in stage 2 for about 1min, then working again,vertical)
Marvel vs Capcom 2 (working)
Marvel vs Capcom 2 unlocked (working)
Melty_Blood_Actress_Again (black screen)
Melty_Blood_Actress_Again_(v6) (black screen)
Project_Justice_(unlocked) (working)
Street_Fighter_Zero_3_Upper (black screen)
Street_Fighter_Zero_3_Upper_(alt) (black screen)
Melty_Blood_Act_Cadenza_(RevA) (error 02)
Melty_Blood_Act_Cadenza_(RevB_v3) (working, huge grafic glitches)
Melty_Blood_Act_Cadenza_(RevB2_v3) (black screen)
Guilty_Gear_XX_The_Mignight_Carnival (rom checksum error can be bypassed, character gfx glitches, game freezes after some seconds)
Guilty_Gear_XX_The_Mignight_Carnival_Slash_(v6) (character gfx glitches, game freezes after some seconds)
Guilty_Gear_XX_Accent_Core_(v6) (character gfx glitches, game freezes after some seconds)
GigaWing2 (working, good speed, unplayable cause of invisible enemy projectiles)
Hokuto Renkitoza (working)
Fist_of_the_North_Star_Naomi2_(Fixed) (working)
ChaosField_(v3) (working, very slow, unplayable cause of invisible enemy projectiles)
Capcom_vs_SNK_Millenium_Fight_2000 (working)
Capcom_vs_SNK_2_Mark_Of_The_Millennium_2001 (works great)
Capcom_vs_SNK_2_Mark_Of_The_Millennium_2001_(alt) (works great)
Radirgy_(v3) (errorr 54, wrong game adjustments)
RadirgyNoa_(v6) (working, unplayable cause of invisible player objects)
Rhythm_Tengoku_(fixed) (error 02)
Senko_No_Ronde_(v3) (working, bad control mappings)
Senko_No_Ronde_New_(v6) (working, no controls)
Senko_No_Ronde_SP_(v3)  (working, bad control mappings)
ShootingLove2007_Exzeal_(v6) (errorr 54, wrong game adjustments)
Trigger_Heart_Exelica_(v6) (errorr 54, wrong game adjustments)
Trizeal_(v3)  (errorr 54, wrong game adjustments)
UnderDefeat_(v3) (errorr 54, wrong game adjustments)
Airline_Pilots (error 51, game assinments incorrect)
18_Wheeler_DX (not working, board error not enough switches)
18_Wheeler_STD (not working, board error not enough switches)
Alien_Front (not working, requirenments not satisfied)
Akatsuki_Blitzkampf_Auf_Asche (working, unplayable cause of invisible player objects)
Sega_Clay_Challenge_(Best) (working, no ingame controls)
Sega_Bass_Fishing_Challenge (working, bad controls, major gfx glitches)
CrazyTaxi (not working, crashes into hackchi)
Cosmic_Smash (not working, crashes into hackchi)
Confidential_Mission (not working, crashes into hackchi)
Cleopatra_Fortune_Plus_(v6) (working, grafic glitches on player objects, not good playable)
Burning_Casino_(v3) (working, grafic glitches, unplayable)
Border_Down_(v3) (not working, crashes into hackchi)
Azumanga_Daioh_Puzzle_Bobble_(v3) (working, great)
Dead_Or_Alive_2 (error 02)
Dead_Or_Alive_2_Millenium (error 02)
Illvelo_(v6) (error 54)
Jambo_Safari (not working, boot error, board has not enough switches)
Jingy_Storm_The_Arcade (error 02)
Karous_(v3) (error 54)
La_Keyboard_xyu_(v3) (working, external hardware keyboard not implemented)
Mamoru_kun_wa_Norowarete_Shimatta_(v6) (error 54)
Mobile_Suit_Gundam_Federation_vs_Zeon (error 51)
Psyvariar_2_(v6) (error 54)
Quiz_Keitai_Q_Mode (error 54)
Sega_Marine_Fishing_(EPR-22221_Patched) (not working, boot error fullfil the specs)
Sega_Strike_Fighter (error 51)
Shikigami_No_ShiroII_(v6) (error 54)
Lupin_3_The_Typing (not working, crashes into hackchi)
Lupin_3_The_Shooting (not working, black screen)
KuruKuruChameleon_(v3) (working)
Jingy_Storm_The_Arcade (error 02)
Heavy_Metal_Geomatrix (working, grafic glitches)
Gun_Survivor_2 (not working, black screen)
Gun_Survivor_2_(ncommb) (not working, black screen)
Giant_Gram_2000 (working)
Giant_Gram_(EPR-21820_Patched) (working)
Dynamite_Deka_EX (working, major gfx glitches, unplayable)
Doki_Doki_Idol_Star_Seeker (working, great)
Death_Crimson_OX (working, no controls)
Dead_Or_Alive_2_Millenium (error 02)
Dead_Or_Alive_2 (error 02)
Shootout_Pool_(EPR-23844_v1) (not working, boot error fullfil the specs)
Shootout_Pool_(EPR-23844_v2) (not working, boot error fullfil the specs)
The_House_Of_The_Dead_2_(v2) (not working, boot loop)
The_Typing_Of_The_Dead (working, wtf?!)
Usagui_Yamashiro_Mahjong_Hen_(v3) (not working, boots into service menue)
Virtua_Golf (not working, insufficient controls)
Virtual_On_Oratorio_Tangram_M.S.B.S._(v5.66) (not working, crash into main menue)
Wave_Runner_GP (working, bad controls, unplayable)
World_Series_Baseball (not working, black screen)
Zombie_Revenge (not working, boot loop)
Sega_Tetris (working)
Sega_Strike_Fighter (error 51)
Samba_De_Amigo_(EPR-22966B_Patched) (working, no controls)
Puyo_Puyo_Fever_(v6) (working)
Puyo_Puyo_Da_(EPR-22206_Patched) (working, lack controls)
Puyo_Pop_Fever_(Darksofts_fix) (not working, crash into main menue)
Project_Justice_(RivalSchools2) (working, background gfx glitches)
OutTrigger (not working, control panel not properly connected)
Noukone_Puzzle_Takoron (error 02)
Musapeys_Choco_Marker (working)
MonkeyBall (not working, crash into main menue)
Mobile_Suit_Gundam_Federation_vs_Zeon_DX (error 02)
Zombie_Revenge (not working, boot loop)
Zero_Gunner_2 (working, gfx background glitches)
WWF_Royal_Rumble (working)
Virtua_Tennis_2 (not working, black screen)
Virtua_Tennis (not working, black screen)
Virtua_Striker_2_2000 (not working, crashes into main menue)
Virtua_NBA  (not working, black screen)
Virtua_Athlete (working)
Toy_Fighter (working)
Tokyo_Bus_Tour (error 02)
The_Rumble_Fish_2_(v4)_alt (working)
The_Maze_Of_The_Kings (working, no controls)
Tetris_Kiwamemichi_(v6) (working)
Super_Shanghai_2005_(v6) (working, background gfx glitches, unplayable)
Super_Shanghai_2005_(Rev.A_v6) (not working, crashes into main menue)
Sports_Jam (not working, freeze while loading)
Spikers_Battle (not working, freeze after character selection)
Spawn (working)
Slashout (working)
Shin_Nihon_Prowrestling_Toukon_Retsuden_4 (error02)
Faster_than_Speed (not working, wheel needed)
Faster_than_Speed_(v4) (not working, wheel needed)
Faster_than_Speed_(v5) (not working, wheel needed)
Faster_than_Speed_(v6) (not working, wheel needed)
Sushibar_(v2) (working)
Sports_Shooting_USA (not tested cause of controls)
Sports_Shooting_USA_(v10b)  (not tested cause of controls)
Sports_Shooting_USA_(v11) (working, unplayable cause of controls (gun))
Salary_Man_Kintaro_(JVS_OK_BIOS_OK_Video_OK) (working, no controls)
Animal_Basket (working, lack of controls,vertical)
finished!

Test of  (.dat) roms:
Border Down (Rev A) (working)
Ikaruga (working, no glitches, no controll loss)
Maze of the Kings (not working, crash into main menue)
Melty Blood Act Cadenza (Rev C) (not working, crash into main manue)
Radilgy Noir (error 02)
Senko No Ronde (black screen)
Shooting Love 2007 (error 02)
Trigger Heart Exelica (Rev A)(error 02)
Trizeal (error 02)
Under Defeat (error 02)

// As for these crosschecks it seems to be there is a difference in either the images itself or between .dat files and converted .bin files.

**Comment by KMFDManic** [comment]
Great list:)  If you want to have email communication, you can respond with your email, then just edit it after you post:)  I will still get the message!  But, great list.  I will add to it and post it for next Update:)

**Comment by AntiFly** [comment]
mazterz@gmx.at

**Comment by KMFDManic** [comment]
@AntiFly The one you are using is better!  So, we will stick with that one:)  I am gonna make them aware of this, as they should switch to it officially:)  Great test results!  I will make the post now, and credit you as testing, too!

**Comment by AntiFly** [comment]
i got 106 files left to sort on and check , so im not done yet but ye feel free to go ahead.
theres some potential to get a config adjustment for the 54 errors (if possible, dont know yet).

**Comment by KMFDManic** [comment]
Actually, @AntiFly I am finding from further tests, there are games that work on the expected, officially listed one that do not work on the one you are using, and vice versa!.  So, keep the one I sent you, as well as the one you have!  Guilty Gear Accent works absolutely fine on the one I sent, but not on yours!  So, I will maintain both of them.  Kind of sucks having to choose:)  But, try out one I sent you, you may find it is better.  All the game games are loading for me, plus a few more.  But, try Guilty Gear Accent with one I sent!  And, again, all I had to do to Update was hakchi/transfer and I switched between the 2 sets of BIOS a few times in a row.

**Comment by AntiFly** [comment]
you may give me up to 10 games to crosscheck with the other bios that doesnt worked in my list but worked for you and vice versa ?

**Comment by KMFDManic** [comment]
Ok, ignore my last message.  I am finding, from switching between them a few more times...There is really one big difference.  Naomi Test Menus load up with one I sent, but often times are straight to game with yours.  Otherwise, compatibility seems to be the same!  I retried Guilty Gear Accent, and yes it does freeze.  So, we have same compatibility.  I will probably be in favor of yours.  So, keep testing yours!  Thanks again, man!  I am curious if the First BIOS you found was just a bad one?  Because, I am able to run the games you listed on both yours and mine.  Very interesting subset of games, eh:)

**Comment by AntiFly** [comment]
Hehe ok mate.
Who do you want to inform and make it official, didn't get it!?

Von meinem iPhone gesendet

**Comment by AntiFly** [comment]
bios test done. 
i give now the other bios a shot...

**Comment by caretakerz** [comment]
Hey  guys, I've tried several different bios files.  Not one of them has booted up at all.  Is there a particular set I need to get?, because I'm hitting my head against the wall at this point.

**Comment by AntiFly** [comment]
@caretakerz 
you may have a look into this case. getting this to run made me a headache too ^^
https://github.com/KMFDManic/NESC-SNESC-Modifications/issues/144
post there if this does not help, i trie to help you. keep this ticket here just for compatitiblity.
