### ISSUE TITLE
Bluetooth gamepad crashes Retroarch 

### ISSUE THREAD

**Issue by langrisser1** [KMFDManic/NESC-SNESC-Modifications#146]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.4.1
  * retroarch used (filename): KMFDManic-NESC-SNESC-Cores.9-3-18 => retroarch 1.7.4, with clovercon installed
  * hmod(s) used by the game you are having problems with (filenames): all
  
### Step 2: Describe the problem:
  
Hi mate, I ordered a bluetooth gamepad to replace the original gamepad of the snes mini: 

![1](https://user-images.githubusercontent.com/43528258/45936332-cd72bf00-bfe7-11e8-9025-2bebd3ffbaba.jpg)

I connect the bluetooth gamepad as the 1P plug and leave the 2P with the original gamepad. The wireless gamepad works flawlessly with any core and game. 

However, if I press 'Start' + 'Select' on the wireless controller to pull the retroarch menu during gaming, the retroarch screen is prompted and frozen for 3 seconds, and then crashed. It returns to the game selection menu. 

As a test, I plug back the original gamepad and press 'Start' + 'Select' during gaming to pull the retroarch menu, no problem......

It seems strange, the bluetooth gamepad seems being recognized and functions normally, but crashed when calling retroarch menu during gaming. 

Thanks for your help~

cheers

**Comment by KMFDManic** [comment]
Clovercon supports a ton of generic and official drivers.  Your controller might be an oddball one.  It may need its own special configuration file.  What is the exact controller again, and do you have any means to use it without bluetooth, such as plug in?  USB-HOST, etc?

**Comment by langrisser1** [comment]
Hi mate, it is a cheapy gamepad from china without a brand name. I think it is an knock-off of 8bitdo. It offers a bluetooth receiver and I connect it in front of my snes mini: 
![2](https://user-images.githubusercontent.com/43528258/46185211-98c67680-c30b-11e8-881c-6b64f28428d2.jpg)

It also offers an usb bluetooth receiver. Will test the pad through usb-hub and get back to you soon~

**Comment by langrisser1** [comment]
Hi mate, I tried to connect the gamepad with the bluetooth adpator/an usb wire to my snes mini and my PC as well.

Both cannot detect the gamepad........ 
I expected my PC can recognize it but it fails......

Anyway, do you know any wireless controller that can be recognized by retroarch/clovercon?

Thanks~~

**Comment by KMFDManic** [comment]
@langrisser1 Wireless controllers in general, 8bitdo wise, have been hit and miss with various people as far as being able to use L3/R3, left and or right analogs properly mapped, etc.  Just try to do a little research before taking the plunge on another.  I strictly use wired with an extension cable, as it is absolutely flawless for my needs:)

**Comment by langrisser1** [comment]
For those who brought this controller: 
The controller works as the design. The controller has a shortcut "start + select" to exit the game selection menu, which is the same shortcut of loading retroarch. 

Someone got a workaround on this:
[https://www.reddit.com/r/miniSNESmods/comments/9389uv/wireless_nes_controller_has_selectstart_shortcut/](url)

Start a game, enter Retroarch menu. "Quick Menu" > "Close Content", then follow the above solution to enable an alternative shortcut (UP + Select), then quit retroarch to save the shortcut
