### ISSUE TITLE
hakchi-v1.0.3-110 ???

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#147]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.4.1
  * hmod(s) used by the game you are having problens with (filenames): KMFDManic-NESC-SNESC-Cores.9-23-18.Xtreme
  
### Step 2: Describe the problem:
  there is a core listed under "unknown" hakchi-v1.0.3-110, what is it ?
can it be safely removed, cause i dont have a use for it ^^
cheers

**Comment by KMFDManic** [comment]
Hello mate:) I mirrored the hmods that come prepackaged with CE, to keep them safely backed up when someone empties their user mods folder.  I will email about your other request, once home:)

**Comment by AntiFly** [comment]
All Clear hakchi-v1.0.3-110.hmod got rid of it ^^
