### ISSUE TITLE
arcade_games auto apply to hackchi ?

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#148]
Hi mate,

thanks to madman for thise awesome arcade "best practise" guide... ive just load the most of em right just i thought about.. 
I was wondering myself if there is any issue loading such a game with an other core ??

but the thing what i got first in mind was,... damn how cool it might be if we could apply such a list to the current loaded games into hackchi you know.
just not to have all this work again going through each game... maybe a "semi" automatism ?!

cheers

**Comment by KMFDManic** [comment]
This could be done.  But, it would take a bit of effort to set it up for all the games in the list.  It is a really cool idea, though.  The only problem is, those using incorrect rom sets, will still end up getting the Cores for the "expected" test results:)  But, you and me and MADMAN all know about this fun stuff!  I will email you before bed, mate:)

**Comment by KMFDManic** [comment]
The automated nature could take 14+ hours to run and could potentially freeze Hakchi, based on previous auto fill in Arcade Scripts that have been tested.  I am going to consider this low priority for now.  But, one person I know might be able to pull it off.  I will broach the idea with him when I get the chance.
