### ISSUE TITLE
_km_Xtras_9_23_18\BIOS

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#149]
Hi "again" ^^

I had a short overlook to this Bios guides... 
first i truelly love it to have such ;)

now to my points:
@ BIOS_ReadMe_Advanced!.pdf
- under "_km_reicast_" NAOMI is completely missing! "dc/naomi_boot.bin (Naomi/Atomiswave Bios)
- dc_flash.bin should be "dc/dc_flash.bin (Date/Time/Language)"

@ BIOS_Cheat_Sheet_Printer_Friendly.pdf
- This document hase different informations about Cores (eg. km_yabause "slow core") than the advanced one. (I would expect the advanced one just printer friendly as overview)

@ BIOS_ReadMe_Basic!.pdf
- outdated.
- merge needed data (if not still exist) to "BIOS_ReadMe_Advanced!.pdf"
- delete BIOS_ReadMe_Basic!.pdf from repository

My Suggestions to make it simple and easy to update!
**
- wipe out the bios files needed from (BIOS_ReadMe_Basic!.pdf)
- keep the corename + core info about emulated systems
- udate core data from newly added/missing cores
- rename file to CORE_Emulation_Overview.pdf
**
I like the idea to strip colums from the excel sheet. keep that going but:
- why did you named this cheat sheet, i don´t get it, it should more like "BIOS_ReadMe_PrinterFriendly.pdf"
- mainly update the "BIOS_ReadMe_Advanced!.pdf" (merge missing NEEDED data from "BIOS_Cheat_Sheet_Printer_Friendly.pdf to "BIOS_ReadMe_Advanced!.pdf")
- for updating the printer friendly version then just hide the related columns. that will prefent mixed informations here and will keep it clean ;)

@ BIOS_ReadMe!.txt
- merge the (if not still exist) needed informations to "BIOS_ReadMe_Advanced!.pdf"
- delete BIOS_ReadMe!.txt from repository

AND
for mainly all of the guys out there "we" should add a column "MD5 CheckSum" where we can add the checksum of positive tested or "recommended" bios files.

cheers

**Comment by KMFDManic** [comment]
@AntiFly I have decided we can work on the Wiki Portion of my Github.  justme488 started one as an example.  But, we can fuller flesh this out with whatever ideas you both have, as well as mine and anyone else interested in helping the experience out:)

https://github.com/KMFDManic/NESC-SNESC-Modifications/wiki

Feel free to do whatever you wish!

**Comment by Justme488** [comment]
@AntiFly  My idea was to have a list of common systems in the wiki, with a page for each system that has what cores work with that system , bios, md5, file extensions,and command lines. I know it's a lot of work, but I think it would be a great go to reference. What do you think?

**Comment by gingerbeardman** [comment]
The retropie wiki is a great example. https://github.com/RetroPie/RetroPie-Setup/wiki/Supported-Systems

**Comment by ArieKindicator** [comment]
Set up a wiki overview is a good idea. When file checksums make the list, please add the crc32 checksum. WinRar, 7-Zip, etc. show this by default for other checksums you might need an external program or online service. Obviously not a big issue, but crc32 is more convenient.

**Comment by KMFDManic** [comment]
@ArieKindicator I will include a tool to make checking things more optimally easy.  I will also give information about the various BIOSES needed.  The expected ones are not always the "Only" ones:)  I will cover this whole scenario so many understand the nuances of the whole shebang, so to speak.

@gingerbeardman Thanks for stopping in.  Always a pleasure!  

@AntiFly Same to you, always appreciate your input.  Will keep optimizing the BIOS PDF as future Updates occur, to coincide with any pertinent changes.

@Justme488 Ping:)  Glad to have you on board!  Thank you so much for helping make things better for all involved!

**Comment by AntiFly** [comment]
for the moment im into testing the amiga shit... kyland got me dingered on that fuck ^^

**Comment by KMFDManic** [comment]
@AntiFly Down to just BIOS Print Sheet for now.  Wiki and that file will be updated for Next Next Update:)  ScummVM this time around, along with a few other nice additions:)
