### ISSUE TITLE
Cores not showing up

### ISSUE THREAD

**Issue by djritz0** [KMFDManic/NESC-SNESC-Modifications#15]
Uninstalled prev cores and tried to install the new ones, they arent showing up. Am I missing something?

I placed new cores in user mods folder, added new modules, then flashed custom kernel. Shouldve showed up under retroarch cores no?

**Comment by djritz0** [comment]
@kmfdmanic also, since tryin to upload your cores I’ve been getting this message:

“Invalid Kernel Size 6849468”

How do you fix this? Never had these problems before

**Comment by KMFDManic** [comment]
You ran into the Classic Access Denied Error:)  Easily fixed...

https://www.youtube.com/watch?v=mGooTybpodM&t=4s

And, the Cores, I would suggest copying and pasting them into your User Mods Folder, removing or deleting the old ones before doing so!  Just updated the Core Set a few minutes ago, as well:)

**Comment by KMFDManic** [comment]
Due to lack of response, I am assuming that my last message helped resolve the issue:)
