### ISSUE TITLE
P-UAE Saving ?

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#150]
hi dude,

I´ve finally managed to convert the games I want to give it a trie to .hdf with all the bios stuff installed.
And yes its working (hilarious)... haha^^

But some thing is a bit sad, ive found no way to save for now.
is there any way i could savestates or do a save... how should this be handlet ??

ive tried save states, wont work
ive tried exit retroarch wont work
i looked into config , there is selected autouse savestates... 
i have no idea so far how this could be done ... any help pls ;)

ive tried 
pirates
patrician (crashes while saving ingame)

by the way ue4arm can not load .hdf files directly isnt it ? ive tried to load the core and then load a .hdf but it always switches automatically to puae !?
cheers

**Comment by AntiFly** [comment]
###############################################
-----------------------
Working Amiga Games
-----------------------
###############################################
Agony (with UAE over uae4arm)
AlienBreed (PUAE) 2 Player
AlienBreed Special Edition (PUAE) 2 Player
Apidya (PUAE)
BattleSquadron (PUAE) 2 Player
Benefactor
Deliverance
DisposableHero
Flashback
Flood
FlyHarder
Frenetic
Indiana Jones and the Fate of Atlantis (Ingame Save/Load works)
IndianaJonesTTOD  (Ingame Save/Load works)
LamborghiniAC
Lionheart (with UAE over uae4arm)
Odyssey
Pang
ProjectX
ProjectXSE






--------- IsSUES -------------
2nd test with uae4arm... coming soon...

Banshee (MC68020 CPU needed)
BattleIsle (MC68020 CPU needed)
BattleIsleDD (MC68020 CPU needed)
ChaosEngine (MC68020 CPU needed)
ChaosEngine2 (chipmem 2mb needed)
Fireforce (chipmem 2mb needed)
GundbeeF99 (MC68020 CPU needed)
Historyine (MC68020 CPU needed)
PiratesGold (MC68020 CPU needed)
Roadkill (MC68020 CPU needed)
RuffNTumble (slave error on puae)
AlienBreed 2 (AGA)




--------- NOT WORKING ---------
AlienBreedTA (PUAE) illegal exception
Apocalypse (PUAE) lack of controlls
ApanoSinDE
Datastorm (lack of controls)
RocketRanger (lack of controls)

**Comment by AntiFly** [comment]
Template from Lionheart.uae is a bug : 

hardfile=read-write,32,1,2,512,/etc/libretro/system/WHDLoadCheats.hdf
should be
hardfile=read-write,32,1,2,512,/etc/libretro/system/WHDLoad.hdf

and 
hardfile=read-write,32,1,2,512,/media/amiga/Lionheart.hdf
hardfile=read-write,32,1,2,512,/var/games/CLV-Folder-here/Lionheart.hdf

even 
hardfile=read-write,32,1,2,512,<PATH TO GAME>/Agony.hdf
is for the most of the users not understandable ^^ (i guess so)
^^

**Comment by AntiFly** [comment]
ive tried with Agony.uae but system give message that i have to put in DH1 ... whatever that is ôO

**Comment by KMFDManic** [comment]
@AntiFly Good test results.  DH1 error is due to improper uae and/or slave.game being incorrectly set-up.  The 2 MB games may be able to be worked out with uae configs, too.

Amiga, in general, is an emulator that many have abandoned due to the logistics of its overall complexities.  We will definitely keep on keeping on and try to make things better every Update:)  Much appreciated, your test results.  I will have something else for you to test out, if you are up to the task:)

**Comment by AntiFly** [comment]
@KMFDManic 
so the same .HDF file is working good for PUE just slow, i would suggest the .hdf file is good on that one. and i used your sample agony.uae... so whats wrong here ?

haha what do you have in mind to test `?

**Comment by KMFDManic** [comment]
You've probably learned by now, @AntiFly , that dynamic recompiler helps UAE4ARM run much faster than P-UAE!  That is why Agony runs so fast on UAE4ARM, but slower on P-UAE.  There is a config file to help it somewhat.  But, ideally, it should only be played on UAE4ARM:)  Aladdin suffers the same fate as do many other AGA and 1200 games.

**Comment by AntiFly** [comment]
the speed inreasment is true, but i felt on many game that there is lack of controls and gfx missing.
dunno why but this uae4arm feels incomplete to me.

**Comment by KMFDManic** [comment]
UAE4ARM has a lot of things that are not fully functional, such as .uae script perimeters not being able to be used, etc.  But, with Dynamic Recompiler, it is a very fast Core!  Saves will be something on my agenda, along with DOSBox.  These may not be as easy to pull off, overall.  The saves may need to be done a special way for either or.
