### ISSUE TITLE
FBA Can't run Metal Slug 3, 4, 5 and Strikers 1945 Plus?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#151]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.4.1
  * retroarch used (filename): km-Retroarch 174 Xtreme
  * hmod(s) used by the game you are having problens with (filenames): km_FBA 2012 and km_FBA 2016
  
### Step 2: Describe the problem:
  
  * Is there a known issue with these Neo-Geo games? My other 80+ Neo Geo games run perfectly, but I can't find a version of any of these 4 games that will run at all. Some just freeze before starting, occasionally one will start stuttering out the Neo Geo start-up screen before crashing. If they DO work, can you please help identify the correct version of the roms? I've tried every one I have found.

Any ideas please?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
All of these games run fine.  Your issue would be directly related to a combination of BIOS, rom set used, and which way you are utilizing the BIOS.  What exact Command Lines are you using for the games?

**Comment by bolton80** [comment]
My neogeo.zip looks like this:
![neogeo](https://user-images.githubusercontent.com/39167008/46420031-aa9a8600-c71e-11e8-83be-442009fd84de.jpg)

The neogeo.zip is in the same folder as my mslug.3.zip.

My command line is: /bin/fba2016 /usr/share/games/CLV-Z-OAESQ/mslug3.zip

**Comment by bolton80** [comment]
Other than downloading several gigabytes of .zip files to extract just the bios, is there a good way of identifying and downloading them?

**Comment by AntiFly** [comment]
have a look into your mslug4.zip

![mslug4](https://user-images.githubusercontent.com/38633765/46428567-a1241480-c744-11e8-9204-39f6ed211236.jpg)

i overlooked your neogeo.zip looks pretty similar to mine (i got some extra thing included but they wont effect to metal slug)

**Comment by bolton80** [comment]
My mslug4.zip doesn't look like that. This is what I have...
![mslug4](https://user-images.githubusercontent.com/39167008/46429081-1a1b7000-c735-11e8-84b2-01db056c4516.JPG)

Looks like I am using a different version of the rom. Exactly which romset do I need to use for FBA2012 and FBA2016?

**Comment by bolton80** [comment]
It might sound obvious, but none of the versions seem to be clearly labelled anywhere online.

**Comment by AntiFly** [comment]
@bolton80 
if you use neogeo.zip from fba2016 which u do (what i can say cause of the crc32) than u needthe roms from the 2016 set to be good to go.
in some cases it might be possible a old version from an older set is working (if there was no change on that particular one) but better run the roms with the correlated bios ;)

**Comment by bolton80** [comment]
Right, here's the full picture of what I am now using.

Command Line: /bin/fba2016 /usr/share/games/CLV-Z-GLCXI/mslug4.zip

The game folder looks like this:
![capture](https://user-images.githubusercontent.com/39167008/46430194-daa25300-c737-11e8-9a52-afccf09f4394.JPG)

The mslug4.zip looks like this:
![mslug4](https://user-images.githubusercontent.com/39167008/46430223-e5f57e80-c737-11e8-8440-56bd30245642.JPG)

The neogeo.zip looks like this:
![neogeo](https://user-images.githubusercontent.com/39167008/46430233-eee65000-c737-11e8-9bf6-cc87392dcbd0.JPG)

It still doesn't load. When I try to start it, I get a black screen for about 10 seconds, then another 10 seconds of the SNES Mini border with just a blank screen in the frame, then it returns to the SNES mini menu.

**Comment by AntiFly** [comment]
@bolton80 
you got the neogeo.zip within the folder of the game. 
you may trie to remove this and install kmfds bios hmod with the neogeo.zip inside and give it another trie.
otherwise it looks ok for me tho.

It looks like you ran the stuff inside the snes mini without usb-host so make sure the mods are correct installed and not overwritten cause of a space issue (ive got that once, ive installed to many hmods to snes and they overwrote themselves and this caused strange behavior of emulation)

**Comment by KMFDManic** [comment]
@bolton80 You have combination of bad BIOS/rom set set-up.  You can send private message on Reddit, and we will go from there:)  MDFMKanic
