### ISSUE TITLE
PPSSPP 3rd Birthday moving not possible

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#153]
hi there,

ive tried the 3rd birthday shown from your video here https://www.youtube.com/watch?v=_nwXujyYidw&t=570s 
but unfortunally i cant move at all, if i push the cross i just moving the camera view. i already did the setting you showed, but nothing changed.
using classic snes controller came with snes mini.

it just worked after i manually switched the dpad buttons to y+- and x+- ?!
did i missed something here ?

hint appreciated 
cheers

**Comment by KMFDManic** [comment]
I have gone over this a few times in various PSP Videos.  But, going into controls, and disabling left analog will fix movement issues, as the real PSP had one analog, and changing this option will separate the dpad and analog:)

**Comment by AntiFly** [comment]
really strange, this "move" does not work with my snes.... ;(

**Comment by KMFDManic** [comment]
Once you reinstall RetroArch with the Update, try going to RetroArch/Controls/and Left analog turn to off.  This fixes nearly every game that has goofy control/HUD/Items popping up, etc issues on my end, as well as many others who have had same issues.  With it on, several games merge the controls of D pad and Left analog, which creates conflicts.  You should be fine with the disabling of left analog.  It worked flawlessly for me with 3rd Birthday:)
