### ISSUE TITLE
Some more SEGA DreamCast Test

### ISSUE THREAD

**Issue by ghost** [KMFDManic/NESC-SNESC-Modifications#154]
ive got tested some unoffical DC Games  if thesewill work.

here are the results with RetroArch 1.7.5 and Reicast Xtreme :
Alice Dreams (working)
Alice's Moms Rescue (Joshprod) (France) (working, flicker on main menu, no flicker ingame)
DUX 1.5 (2014)(Hucast.Net) (working)
DUX 1.5 (2014)(Hucast.Net)_alt (working)
Frame Gride Final version (NTSC-J) (working)
Geist Force Resorted (not working, black screen)
DUX (2009)(Hucast.Net) (not working, black screen)
Sturmwind (working,great,very few hickups) [COOL]
Fast Striker Ver. 1.0 (2010)(NG.DEV.TEAM) (working)
Fast Striker Ver. 1.5 (2010)(NG.DEV.TEAM) (working)
Feet.of.Fury (working)
Fire Pro Westling (eng.prepatched) (working)
Flag to Flag (not working, lack of controls)
Flashback (working)
Geist Force (not working,freeze on game start)
Ghost Blade (2015)(Hucast.Net) (not working, c7 error)
Gunlord (2012)(NG.DEV.TEAM) (working) [COOL]
Gunlord (2012)(NG.DEV.TEAM)_alt (workin)
Half-Life_Repack (not working, c7 error)
Hellgate-IND (not working, c7 error)
Last Hope - Pink Bullets (2009)(NG.DEV.TEAM) (working) [COOL]
Last Hope - Pink Bullets (U) (2009)(NG.DEV.TEAM) (working)
Last Hope (2006)(NG.DEV.TEAM) (working)
Last Hope (U) (2006)(NG.DEV.TEAM) (working)
Millenieum Racers 2017 (RF) (working, lack of controls)
NEO XYX (2014)(NG.DEV.TEAM) (working) [COOL]
Propeller_Arena_USA_DC (not working, lack of controls, c8 error)
Redux - Dark Matters (2014)(Hucast.Net) (working) [COOL]
Rush_Rush_Rally_Racing_PAL_DC (not working, freeze on boot)
The_Flintstones_Viva_Rock_Vegas-SGMX (not working, lack of controls, gfx glitches)
Toe Jam And Earl 3 (not working, major gfx glitches)
Volgarr (working) [COOL]
WhatsShenmueENG (working, lack of controls)
Wind and Water Puzzle Battles (working)
Zia & the Goddesses of Magic (World)(2016)(Orion) (working) [COOL]

#################################
Results with Retroarch 1.7.4 + Reicast (KMFDManic-NESC-SNESC-Cores.9-23-18.Xtreme)
Fast Striker (SHMUP) 2011 (working,bit stuttering,playable)
Gunlord (Platform,Shooter) (not working, c7 error)
Neo XYX (Zaikusu/Zaiksu)(SHMUP) 2014 (DC) (not working, freeze)
Last Hope: Pink Bullets (DC) (not workin, freeze)
Last Hope (DC) (not working, freeze)
Volgarr (PORT) (not working, freeze on sega logo)
Sturmwind (SHMUP) 2013 (DC) (not working, black screen after logo)
DUX (2009)(Hucast.Net) (DC) (not working, freeze)
DUX 1.5 (2014)(Hucast.Net) (DC) (not working, freeze)
Redux - Dark Matters (2014)(Hucast.Net) (DC) (not working, freeze)
Hellgate-IND (not.working,c7error on menu)
Last Hope - Pink Bullets (U) (2009)(NG.DEV.TEAM) (not.working, freeze)
Alice Dreams (not working, crashing, after menue)
Alice's Moms Rescue (Joshprod) (France) (not working, freeze)
Drill (working)

so i would like to test the missing roms for me too, but couldn´t find them. ;)
feel free to bumb the keyboard me for those, most appreciated
- Battle Crust (SHMUP) 2018
- Breakers (Fight) 2017
- Hermes (Platformer) 2017
- Drill

**Comment by KMFDManic** [comment]
I have a feeling Unofficial DC games, as of yet, may mostly not even work.  Gunlord would be awesome, though!  I will check if I have the other ones you mentioned:)

**Comment by gingerbeardman** [comment]
I'm playing a lot of DC at the moment, feel free to bump me on twitter @ gingerbeardman

**Comment by KMFDManic** [comment]
@AntiFly Once I post Update later today, try a few again with Reicast Xtreme and 1.7.5 RetroArch Xtreme Combo.  Like PSP with homebrew games, these are very hit and miss.  One homebrew game that does work on DC, however, is Drill!  So, add that to your "working" list:)

**Comment by AntiFly** [comment]
> 
> 
> I'm playing a lot of DC at the moment, feel free to bump me on twitter @ gingerbeardman

sry i got no twitter either no facebook or flicker or whatsoever ^^. i dont need it.

**Comment by AntiFly** [comment]
I will rework the DC test, the first game ive tried which didn´t worked on 1.74 with reicast now works. so better check again.
gimme some time on that one.

**Comment by AntiFly** [comment]
Do you think multi disc games would work ?
eg Skies of Arcadia ?

**Comment by KMFDManic** [comment]
@AntiFly Multi Disk games have been a thorn in the sides of many Cores for several years now.  But, I devised a very cool workaround to playing several of these on the Mini and will be posting a video tutorial to coincide with Next Update.  The manual method I will showcase can benefit as a future change directly into CE.  I will show how to do it for a few different Cores.  Dreamcast should benefit from the Tutorial, too.  I will use Skies of Arcadia as a test example if it can appropriately work.

**Comment by AntiFly** [comment]
N1, im patient and wait for it ;)

 

Von: Kyland K <notifications@github.com> 
Gesendet: Mittwoch, 31. Oktober 2018 13:25
An: KMFDManic/NESC-SNESC-Modifications <NESC-SNESC-Modifications@noreply.github.com>
Cc: AntiFly <mazterz@gmx.at>; Mention <mention@noreply.github.com>
Betreff: Re: [KMFDManic/NESC-SNESC-Modifications] Some more SEGA DreamCast Test (#154)

 

@AntiFly <https://github.com/AntiFly>  Once I update, those pesky .lst files will not longer be needed:) By tomorrow, my friend:)

**Comment by AntiFly** [comment]
Hi mate,

 

belonging to 

REICAST XTREME = dc folder = airlbios.zip (Airline Pilots), awbios.zip (Atomiswave), dc_boot.bin, dc_flash.bin (Dreamcast), f355bios.zip, f355dlx.zip (Ferrari F355), hod2bios.zip (House of the Dead 2), naomi.zip, naomi_boot.bin (Atomiswave, Naomi)

 

From which mame version did you got these bios files or is it not relevant?

cheers
