### ISSUE TITLE
Vice (9/23) black screen with latest retroarch neo & xtreme

### ISSUE THREAD

**Issue by hoderer** [KMFDManic/NESC-SNESC-Modifications#156]
* hakchi2 CE version: 2.21f
  * retroarch used (filename): Hakchi_Retroarch_Neo_v1_7_2a
  * hmod(s) used by the game you are having problens with (filenames): _km_vice_x64_9_23_18
  
  
  * I get a blank screen when using the latest VICE plugin. I tried a lot of things and different retroarch versions, but no luck. Can't figure it out by myself. Can you reproduce it?

**Comment by KMFDManic** [comment]
Will test and fix for Release.  Thanks for the heads up!

**Comment by hoderer** [comment]
thanks ALOT! I really appreciate it! :)

**Comment by KMFDManic** [comment]
Fixed:)
