### ISSUE TITLE
Update FBAlpha Core

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#157]
Hi mate,

could you please update the FBAlpha Core because as i recently told you daisenpu (twinhawk) is no more working.
it got fixed. look here for info:
https://github.com/libretro/fbalpha/issues/239

the build we currently use is "bad".
i bumb keyboard for a reference set 2018 none-merged if u need, ive got done last days ;)

thanks

**Comment by KMFDManic** [comment]
Perfect timing for Release.  You should be fine now.

**Comment by KMFDManic** [comment]
Updated:)

**Comment by AntiFly** [comment]
thanks, working again ;)
