### ISSUE TITLE
outdated information on some core infos...

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#158]
Info on current .hmod is pointing to just retro arch version 1.7.1 - 1.7.4 Xtreme Variant.... 

should be 1.7.1 Xtreme Variant "or newer" , just that you dont need everytime you update retroarch .hmod need to update this information.

valid for:
_km_retroarch_xtreme_database_add-on
_km_retroarch_xtreme_shaders_add-on
_km_RetroArch Xtreme DS Add-On

cheers

**Comment by KMFDManic** [comment]
Will Update this too:)
