### ISSUE TITLE
Speed Gonzales and Los gatos Bandidos (V.1.1)

### ISSUE THREAD

**Issue by flavioliu** [KMFDManic/NESC-SNESC-Modifications#16]
Hi,  KMFDManic . Thank you for you last reply about the Higan/Bsnes Core. AS I told you on the other post, the Snes Game - Speedy Gonzales and Los Gatos Bandidos (v1.1) freezes on any version of snes9x core. As today I had some free time, my wife and I played the game untill it freezes - Check it here: https://youtu.be/ulZX0YI2_M8 . 

I saw that on your last updates you have made possible to use 02 GBA emulators at the same time. Could you please make the Bsnes/Higan core mod, and make it possible to use 02 Snes Cores at the same time too? 

This way, we could use snes9x 1.54 for other games and Bsnes/Higan core for only this game (speedy gonzales). Hope you can help us. 

Thank you.

Ps: I've also tried to reach byuu on his twitter, to obtain a fix so we can implement it on snes9x, but had no reply from him yet. 

Here is a list of snes games that run better/only on bsnes/higan: 
https://floating.muncher.se/byuu/accuracy/

**Comment by KMFDManic** [comment]
I can give bsnes another shot.  But, last time I tried it, it was pretty slow.  Cross your fingers, and maybe I will get better results with another attempt at it.  In the case of bsnes, it can be done in such a way where you can factor in speed versus accuracy!  I will see what happens next time I get a chance to test.

**Comment by KMFDManic** [comment]
UPDATE: It works.  But, it plays slow.  So, if you want to run it, I can make that possible.  But, beware, it will run slow.  You may get a kick out of playing it pseudo Matrix Style, and finally being able to beat it, hehe:)  Let me know, and I can make the Core available to you sometime today.

**Comment by gingerbeardman** [comment]
Maybe play the game in babes only to press the button, then continue playing it in another emulator?

**Comment by flavioliu** [comment]
KMFDManic great news, please make the core available and I will test it today. It is a great plataformer. Kids love them, and I owned the cart when I was 12, now I am 29.
Thank you once again for your amazing work. 


Gingerbeardman, yes on pc I can beat it on higan. I just want to make our snes mini, to play 99.9% of all games. Higan/bsnes is capable of that.

**Comment by KMFDManic** [comment]
As mentioned, this Core runs slow!  But, you should be able to fully play your game, if it has the "support" for the game, as mentioned!  If we could pinpoint how it was fixed for bsnes, then we can possibly get it fixed in snes9x!

Temporary Link til i post it into my set:)

https://ufile.io/3f73v

**Comment by blackjack-78** [comment]
Hi!
This proplem grabbed my curiosity...After a few research, i found that this is not an emulator problem just a bug in the original game...But...Despite the fact i knew nothing in term of programming, i came with a solution( yeah, i've feel your passion for this game dude, so i've wanted to do something for you...).
Try this: https://www.youtube.com/watch?v=ulZX0YI2_M8
Hope this work for you!

**Comment by gingerbeardman** [comment]
@blackjack-78 are you just running over the button? I'm not familiar with the game so I'm not sure what and when your solution is in that video?

**Comment by blackjack-78** [comment]
Yeah, that's it!
Don't step,run or kick...in, on"this" button in particular...
You just need to run and jump for passing on the other side( because the electric ground is waiting for you, downstairs...) (^_^).
