### ISSUE TITLE
tecmo world soccer 96 graphic issue

### ISSUE THREAD

**Issue by alptolga** [KMFDManic/NESC-SNESC-Modifications#165]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.2
  * retroarch used (filename): km_retroarch175 xtreme
  * hmod(s) used by the game you are having problens with (filenames): km_mame 2003 xtreme
  
Tecmo world soccer 96 works with km_mame 2003 but it has graphic issues. Is there any solution to fix the issue?

**Comment by gingerbeardman** [comment]
If you're using the correct ROM in that it is recognised by MAME, then the only thing you can do is try another version of MAME with its matching rom version of tws96

**Comment by alptolga** [comment]
Thanks for your reply. I tried different romsets that I could find and also emulators.

**Comment by gingerbeardman** [comment]
Then it would be a good idea to report it to MAME project.

**Comment by alptolga** [comment]
I find the problem. The rom files that I used are not fba based. Everything is working right now.
Thanks for your interest.

**Comment by gingerbeardman** [comment]
But you said you were using MAME? Are you using FBA instead?

**Comment by alptolga** [comment]
Tecmo world soccer 96 also works with mame2003 too but it has graphic problems. I tried many different roms for different platforms. This game is only playable with fba based roms.

**Comment by KMFDManic** [comment]
@gingerbeardman Thanks for stepping into help while I was AWOL:)  I was going to try to do a retest, as I also recalled this one working fine in later Cores.

@alptolga Glad it is sorted:)
