### ISSUE TITLE
L2 and R2 buttons wont remap as L2 and R2

### ISSUE THREAD

**Issue by bbaggins19** [KMFDManic/NESC-SNESC-Modifications#166]
I am using: 
 * hakchi2 CE version: _latest version____
 * retroarch used (filename): _retroarch_175_xtreme.hmod
mod used: pcsx_rearmed_neon.hmod
 
The L2 and R2 Buttons wont remap when using retroarch.  When I press L2 to map as L2, it shows as L1 input.  When I press R2 to map as R2, it shows as R1 input.  Thanks for your assistance.

**Comment by KMFDManic** [comment]
You are likely using a controller that isn't fully supported.  Which one are you using?

**Comment by bbaggins19** [comment]
You are absolutely correct!  I was using an 8bitdo adapter and a PS4 controller, and the L2 and R2 buttons were only registering as L1 and R2.  When I switched to a wired Wii pro controller, the L2 and R2 buttons did work properly.  Thanks for your assistance and guidance!  And thanks for the great program!!
