### ISSUE TITLE
dsp2.bin and dsp4.bin md5 reversed?

### ISSUE THREAD

**Issue by romadu** [KMFDManic/NESC-SNESC-Modifications#168]
Hi, when checking bios files, I believe that md5 codes for dsp2.bin (md5): f229fda2d7b33c5a218cba28147ab9b8 and dsp4.bin (md5): 9ebbdcec67c0c01d5a0593d3cf167c9e might be accidentally incorrect, and actually apply to dsp4.bin and dsp2.bin respectively.

For the files I've found, md5 are as follows:
dsp2.bin (md5): 9ebbdcec67c0c01d5a0593d3cf167c9e  
dsp4.bin (md5): f229fda2d7b33c5a218cba28147ab9b8

**Comment by KMFDManic** [comment]
@romadu Thanks for the heads up.  I will change the md5 for the next Update.  Just an oversight when setting up Bright:)  Hope you are enjoying the Core and Top Gear 3000, etc!

**Comment by KMFDManic** [comment]
@romadu Changed for the Update.  Thanks again for the heads up:)
