### ISSUE TITLE
New graphical glitches on updated _km_pcsx_rearmed_neon_xtreme

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#170]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * retroarch used (filename): _km_retroarch_175_xtreme
  * hmod(s) used by the game you are having problems with (filenames): _km_pcsx_rearmed_neon_xtreme
  
### Step 2: Describe the problem:
   * Since updating to the newest release I have found that Micro Machines V3 now has corrupted background graphics on the menu screens. This was never an issue before. I tried replacing the eboot with a new copy in case the file had become corrupted, but it made no difference. I have been using the US eboot (SLUS-00559) all along. 

  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo/Sega/Sony Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
Did you try with /bin/pcsx-standard to see if issue still persists?  Thanks for the feedback.

**Comment by bolton80** [comment]
Hi, Tried that. No change.

**Comment by bolton80** [comment]
![IMG_20190419_232936](https://user-images.githubusercontent.com/39167008/56447268-36f94880-62ff-11e9-9bd0-19568605374b.jpg)
This is what you get on the menu screens now.

**Comment by KMFDManic** [comment]
You referring to aspect ratio cut-off?

**Comment by bolton80** [comment]
Graphical glitches. The backgrounds of the menus are a mess. This was never an issue until the last update (or maybe the one before).

**Comment by KMFDManic** [comment]
I will post something for you to test with sometime tonight.  If it works, will update it into the next Release.  Thanks again!

**Comment by KMFDManic** [comment]
@bolton80 Try this.  Replace current ones with these, and reinstall.  Let me know if issue still exists, or is gone.

https://ufile.io/d5297twi

**Comment by bolton80** [comment]
Hi Kyland. Tested these. The problem is the same.

**Comment by KMFDManic** [comment]
@bolton80 Try one more test, using PCSX1 instead.  /bin/pcsx1

**Comment by bolton80** [comment]
Same issue with PCSX1. I presume this means it's a Retroarch issue rather than the cores themselves?

**Comment by KMFDManic** [comment]
@bolton80 it would seem you may have another conflict, as RetroArch and the PCSX Cores, and your testing...point more in that direction.  I will give the game a personal test.  Usually, from experience, running into graphical glitches on PS1 games can be result of bad rips, bios conflicts, and a few other causes.  I will try it out and get back to you.  What is the full command line, by the way?

**Comment by bolton80** [comment]
I've tried it with /bin/pcsx and /bin/pcsx-standard.

I am using the bios from the PSP. It worked fine with those bios until recently.

**Comment by KMFDManic** [comment]
I mean that it may be another conflict.  But, I will give it a test.  Being a Micro Machines fan, did you ever play Micro Maniacs?  Also, for your own personal knowledge.  Micro Machines NES only works properly on Nestopia.

**Comment by bolton80** [comment]
Never heard of Micro Maniacs. I'll have to Google that now! The Megadrive/Genesis versions of Micro Machines are still my favourites.

**Comment by bolton80** [comment]
Hi Kyland. I think I've worked it out. If I turn "Enable Interlacing" off, the backgrounds are normal.

**Comment by KMFDManic** [comment]
Awesome.  I was gonna test it this AM.  Glad you got it sorted out.  That only affects a few games.  I believe one of the Ridge Racer games may be the 2nd known instance.

**Comment by bolton80** [comment]
Hope this info is useful to you. Keep up the good work! 

ps. Any chance the o2em core can be fixed so it plays more than just 2 Odyssey2 games?

**Comment by KMFDManic** [comment]
Videopac+ should work on it, too.  Did you get to check out Micro Maniacs?

**Comment by bolton80** [comment]
Yes, I've added it to my SNES Mini. Looks interesting. I'll be trying it out 2 Player with a friend on Friday night. He's a MM fan too. Thanks for letting me know about it!

I'll check out some Videopac+ games too. I had no idea they worked.

Thanks again.
