### ISSUE TITLE
access to nestopia machine menu and dip switches 

### ISSUE THREAD

**Issue by yepyepyep4711** [KMFDManic/NESC-SNESC-Modifications#171]
hi everyone,

I hope I'm answering all the questions in the template.

I'm using hakchi CE 3.5.3, with km_RetroArch 1.7.6, installed via KMFD's Mod Hub.
I'm trying to run Nintendo World Championship 1990. It works, with the following command line /bin/nestopia /var/games/CLV-H-HQISU/Nintendo_World_Championships_1990.nes.7z (generated by right-clicking on the rom in hackchi and selecting emulation core)

This seem to work fine, the in-game menu says 1.7.6 - Nestopia 1.50-WIP 44800c5
Now I need access to those dip switches in the cartridge, to change the game duration. This is the reason for running nestopia.
This is supposed to hide in a machine -> dip switches menu somewhere, but as far as I can tell the frontend I'm getting is the one from RetroArch, which doesn't show this. Or am I missing something? I first ran the game just with the --retroarch parameter to the original command line, so I can see it's the same in-game menu.

Cheers all  

crosspost from here: https://github.com/ClusterM/hakchi2/issues/1471 , I discovered this github afterwards and I'm at a loss which is the "right" one

**Comment by KMFDManic** [comment]
@yepyepyep4711 This appears to be a standalone Emulator ability on PC, for Nestopia.  Have you seen a blue triangle that you can select, when loading the rom?  If not, this is something that we would likely need to see if they are willing to try to code in for Nestopia.  It might potentially need to be a Core Option, to avoid conflicts with the other stuff that runs on the Core.

**Comment by yepyepyep4711** [comment]
@KMFDManic nope, no blue triangle

**Comment by KMFDManic** [comment]
@yepyepyep4711 Asked for feasibility of this being implemented on our side, per the reference, above.  Too bad there isn't a "hack" to make this an easier scenario!

**Comment by KMFDManic** [comment]
@yepyepyep4711 If you can, try a test with the last RetroArch 1.7.7 Xtreme I posted, and /bin/fceumm with the Nintendo World Championships.  The actual game never had appropriate mapper support.  Dip Switches and mapper support is becoming better and may work properly with both Fceumm and Nestopia by next Update.  But, for now, confirm how it works with /bin/fceumm

I will post another Update that will have changes for both of the above mentioned Cores.

As far as your other question regarding separate game libraries for your kids and yourself, you just read a little too much into my words.  All I meant for you to do was simply create use 2 different hakchi directories:)  One for yourself, one for the kids.  That way, there can be zero confusion over safe and ok games:)  I do this for many of my test set-ups.  If you need anymore specifics on any of these 2 scenarios, feel free to ask!

**Comment by yepyepyep4711** [comment]
@KMFDManic how do I update RetroArch? :D Just install again through the Mod Hub?
And about those Hakchi directories, I'm still not quite sure how you mean that.
There's a "Hakchi2 CE" folder in the "Team Shinkansen" folder under "Program files". Are you saying I should just make a copy of that "Hakchi2 CE" and name it ""Hakchi2 CE kids" or something, and I'll be set?
The reason I'm asking is because I can't find the place where hakchi saves preferences and directory structures, used roms, etc. So copy-pasting the program folder doesn't seem to make much sense?

**Comment by KMFDManic** [comment]
@yepyepyep4711 Just download latest RetroArch via Mod Hub.  But, install it via Modules, install Modules Tab, within hakchi.

For Hakchi 2 CE, Whatever your current folder is, just copy that entire folder elsewhere, and rename it.  Keep one for you, one for the kids.  You can then amend a folder structure for each, simply by going to Structure next to the game library, when you first open Hakchi...have Custom toggled on, so that it opens every time.  You can hold down left Shift and highlight and uncheck all games, if you so choose to.  Or, hold down left CTRL and uncheck them selectively.  Once in folder structure, if you delete any from there, just make sure to delete that recycle bin before synching/exporting.  This obviously will not delete games from the Main Library...only folder structure.

**Comment by yepyepyep4711** [comment]
@KMFDManic that's interesting. What is the difference between downloading in the hub and installing through the menu as you said instead of just pressing "download and install" in the hub?

Anyways, I updated as you said and switched from nestopia to fceumm and sure enough, I could then see the dip switches. They were even preset to third switch on, which is supposedly correct. Sadly, the time is completely wrong. It's way too short, and every setting I've tried is not remotely as long as it should be. Also, there are two unnecessary green dialogues popping up after a short time in the bottom left corner, reminding everyone that this is emulated, which is really unwanted. So I switched back to nestopia, which has no dip switch settings but plays the correct time, plus no ugly messages. Then I realised the dialogues where from 1.7.7, not from fceumm, so I deleted 1.7.7 too and reinstalled 1.7.6, now everything is back as before :) 

So I guess fceumm emulation of that game is not working yet.

Regarding the folders, I'll have to try and find out how it works. I've finally discovered where hakchi saves configuration settings, it's in the "my documents" folder. So there are two "hakchi folders" on a windows machine, one under "Program Files (x86)\Team Shinkansen", and one under My Documents. You're saying I should copy-paste the program folder, right? I wonder how conflicts are prevented. I theory the second instance of hakchi has no way of knowing it's the second instance and could overwrite the settings of the first, since these are not saved in the program folder. Hmmm

**Comment by KMFDManic** [comment]
@yepyepyep4711 The dip switches were functional with fceumm?  Just not the way you expected them to be?

As far as the Notifications, they are on by default with 1.7.7, as they greatly help with troubleshooting, such as in cases like even this:)  You can easily toggle them off, however, as I detail in the other issue currently open on this Github.  

As far as the dip switches, I will test the newer coding, and see how it fares.  At least we are getting somewhere:)

**Comment by yepyepyep4711** [comment]
@KMFDManic yes, the dip switch do *something*, but the time is wrong nevertheless, and by a long shot. 3 mins something instead of 6:21 mins, for example.

**Comment by yepyepyep4711** [comment]
@KMFDManic so, copy-pasting the program folders certainly doesn't produce the intended result (a deleted game in one instance results in it being deleted in the other). As I said, this is only logical, as no settings are in the program folder. Copying the folder under my documents is the same. Could it be you're using a portable version where everything is in one folder?
Could you describe exactly what it is you're copying? When you mention a folder, can you please give its path?

**Comment by KMFDManic** [comment]
@yepyepyep4711 Main thing to remember is, best to not do it as a program install.  I use the Debug version, which is manually extracted.  I simply copied the entire directly to another location on another harddrive, or same harddrive, or whatnot.  And, then, any changes I make within that folder, stays within that folder.  Any I make to the other folder, stay within that folder.  That is all it is, just same folder, two locations, but the changes update to each specific folder.

**Comment by yepyepyep4711** [comment]
@KMFDManic ah. That explains why we were not understanding each other :) Let's call that an _undocumented feature_, shall we? ;) I'll open a feature request in hakchi for set management. It should be fairly easy to do with the current folder structure, just needs a few dialogues.

**Comment by KMFDManic** [comment]
Hakchi already has this ability, and it is considered a Custom Preset.  But, the way I suggested makes the two different libraries super easy to maintain, since only games for the kids can be accessible in the one folder.

**Comment by yepyepyep4711** [comment]
if you mean the presets und file -> selection presets, this is how I'm doing it at the moment and is super tricky. You have to remember to save under the same name before switching presets or you lose everything and/or make changes in the wrong set. Also, you don't see which set you're working on at any given time, so if you're trying to build a set from another you _will_ make mistakes and it is frustrating. I understood what you said about the debug version, but I'm using the installed one, which I think is the one many people will use, and I'm trying to help make the UX better. Whether or not this change makes it in the product is not up to me. of course :) But considering there are quite a few issues open wishing for some kind of list/set/preset management, I'm not the only one with the problem. I'll document these in my issue.

**Comment by KMFDManic** [comment]
Install version is meant more for those who are less initiated with general extraction.  I would recommend you simply use two mirrored debug versions, and simply cater the game library in one to be specific to the kids.  It is super simple to keep things organized that way, with no hassle whatsoever.

**Comment by KMFDManic** [comment]
@yepyepyep4711 Hope all is well on your end!  Be sure to try FCEUMM, etc, again, Next Update.  There is only so much that can be done with the "dip switch" games.  But, will keep trying to poke around with them, in the future:)

**Comment by yepyepyep4711** [comment]
@KMFDManic it's really interesting, because on a pc or on android, the timing is correct with FCEUMM

**Comment by KMFDManic** [comment]
I am curious if it would work with MESS 2016.  I will have to try, if the game is even supported.  For now, retry it in both in my latest Update.

**Comment by yepyepyep4711** [comment]
sure. I'm waiting for it to be available through the hub. RIght now I only see 6-15-19 there

**Comment by KMFDManic** [comment]
6-15 is the updated one.  I kept the date the same to make the set easier to manage for the specific files I updated.  Grab RetroArch Xtreme now.  Hopefully, the dips function better for you.  Other dip games work, too, now

**Comment by yepyepyep4711** [comment]
so I did update. The time is now correct in FCEUMM so I guess that's a win, but the switches are disregarded. I changed from only switch 3 as intended to all of them, and the time didn't change.

**Comment by KMFDManic** [comment]
@yepyepyep4711 you may be good to go as of my next update, as the dip switches can now be altered via core options.

**Comment by yepyepyep4711** [comment]
yes! Times are shown for each switch and work as advertised! Many thanks! :)
