### ISSUE TITLE
Original (preinstalled) SNES emulation not working since update?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#173]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * retroarch used (filename): 176
  * hmod(s) used by the game you are having problems with (filenames): NA_
  
### Step 2: Describe the problem:
  
  * I found last night that after updating my SNES mini with the most recent retroarch and core versions, suddenly my SNES games are no longer working with the standard built-in non-retroarch default emulator (is is called Clover?).

Any idea how I can resolve this please?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo/Sega/Sony Classics Discord](https://discord.gg/bX9PqrC)

**Comment by bolton80** [comment]
Just to clarify, neither the preinstalled 21 SNES games, nor the ones I added through Hakchi are working. All Retroarch cores and non-SNES games are working fine.

**Comment by KMFDManic** [comment]
@bolton80 Nothing in the Update would have affected Canoe (default SNES Classic Emulator).  So, this would mean you've simply run into another conflict, somehow.  Have you attempted to do kernel install/repair, as of yet?  Additionally, I just did a retest of Default/Canoe added games, and they ran fine on my end.  No worries, though, we will get this sorted!  

And, did you decide to stick with Notifications?

**Comment by KMFDManic** [comment]
Just remember, from a fresh install, and a kernel install/repair of hakchi, SNES games, default ones...should run, as well as .Sfrom (Canoe driven ones) that are added afterwards, whether or not you have RetroArch or any other Cores installed.  So, this would definitely be indicative of another conflict.  But, an install/repair of the kernel should sort you out.

**Comment by KMFDManic** [comment]
@bolton80 I am going to assume things are sorted since you have not responded back.  A kernel repair/reset should have instantly fixed the set-up, as far as default, etc not working.  Keep me posted if you have anymore issues:)  I will respond to the Notifications Topic, as well.

**Comment by bolton80** [comment]
The Kyland. Yes, a reset fixed the issue. Thanks for the reminder. I was busy with other stuff and didn't get round to replying.
