### ISSUE TITLE
Snes Classic netplay help!!!!!!

### ISSUE THREAD

**Issue by karokong2488** [KMFDManic/NESC-SNESC-Modifications#174]
i am running hackchi2 v 3.5.3 and am trying to connect the snes classic to the internet, i have a TP Link TL-WN725N 150mbps network adapter.  
  
### Step 2: Describe the problem:
 i open the telnet client and enter root which gives me access to the command prompt i thought from here all i had to do was enter wifi-wpa-setup to start entering my network information  but when i do  it returns -sh; wifi-wpa-setup: not found and i can progress no further. it has me perplexed can you help me ??

 
![image](https://user-images.githubusercontent.com/43355849/57632312-43d52900-7599-11e9-9723-4f9a5970b7d4.png)

**Comment by KMFDManic** [comment]
This is my Online Tutorial on how I got up and running:

https://www.youtube.com/watch?v=i06ZEBysq1Y

Text Tutorial Here:

https://hakchi.net/KMFDManic/NESC-SNESC-Modifications/KMFDManic-S-NESC-PSC-Cores_4-29-19/_km_Xtras/WI-FI/

This still works for me, without issue.  Keep me posted:)

**Comment by karokong2488** [comment]
hi yes this is a different method which i had not tried before but it still results in the same outcome.
![image](https://user-images.githubusercontent.com/43355849/57708344-118efe80-7661-11e9-922c-ce76fa4e7bae.png)
this is just before i load the command prompt using your method notice the ip address and port number  isnt showing up regardless though i gain access then when i enter root then wifi-wpa-setup it returns not found image below:
![image](https://user-images.githubusercontent.com/43355849/57708583-7ea29400-7661-11e9-8ee3-9b4c98d8dd57.png)
should i revert back to  hackchi 3.5.2 would that make a difference ??
thanks for your help also dude.

**Comment by karokong2488** [comment]
i tried downloading an older version of hackchi2 3.5.2 to an external hard drive and repeated the process but i just got the same result

**Comment by karokong2488** [comment]
Solved i uninstalled the WPA supplicant and re installed it then it allowed the wifi-wpa-setup command to execute thanks
