### ISSUE TITLE
REQ: Please implement .sbi handling for PCSX ReArmed NEON Xtreme on .pbp converted games.

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#175]
### Step 1: Describe your setup:

  * hakchi2 CE version: hakchi2-ce-3.5.3-release
  * retroarch used (filename): 1.7.7
  * hmod(s) used by the game you are having problems with (filenames): kmfd
  
### Step 2: Describe the problem:
  
  hi mate, ive tested two libcrypt protected pals FFVIII and Fear2. 
So on FFVIII there is a "fix" for another emulator, I hope you can implement such feature into PCSX ReArmed. 

here the links to what i have found (already tested it on the current hmod and hackhi, endup in blackscree) same iso not .pbp converted (cure/img) is working.

should already work?
http://docs.libretro.com/library/pcsx_rearmed/

https://retropie.org.uk/forum/topic/13403/playstation-sbi-files-with-pbp-or-even-multidisc-pbp/2

https://github.com/libretro/beetle-psx-libretro/issues/241

https://github.com/Kippykip/SBITools
cheers

**Comment by KMFDManic** [comment]
I am pretty sure .sbi may already work with .pbp  I remember helping someone else with a few games awhile back.  

The .sbi files just need to be in same directory as the .pbp and named exactly the same..:

Resident_Evil_3.pbp and Resident_Evil_3.sbi  Then, it should work fine.  I included a ton of .sbi patches in the Xtras, PS1 Folder.  Did you use exact naming?

**Comment by AntiFly** [comment]
yeh was that me dude ? ^^
ive already packed all games into .pbp but i didnt managed to get them working with the multidisk protected one (Final Fantasy VIII).

**Comment by KMFDManic** [comment]
Ah, the problem isn't necessarily..sbi for FFVIII, as the game simply does not work in one single eboot.  It cannot fully read the memory.  Try it with Resident Evil 3, if you get a chance:)

**Comment by KMFDManic** [comment]
@AntiFly as mentioned, some of the 4 disk games, do not at all fare well when in a single Eboot.  Final Fantasy VIII is one of these.  That one will only work if separate.

**Comment by KMFDManic** [comment]
@AntiFly Did you try using the "same" .sbi file, renamed to match each separate disk?  This is a very curious scenario, as you "can't" have them all in one single eboot, due to memory constrictions.  Keep me posted if you followed up, otherwise.  I can confirm .sbi works fine with eboots, though.  Resident Evil 3 loaded without issue.

**Comment by AntiFly** [comment]
Eboot and sbi is not working for multi disc based games at least for me. You need to male sure using a libcrypt protected unpatched iso as source.
But anyway i found the psn source which van be decrypted and encoded to eboot as well and this works. 

Von meinem iPhone gesendet

**Comment by KMFDManic** [comment]
Definitely shouldn't be very many that are multi disk and have need for .sbi.  Good on finding the source. By the way, be sure to email me.  I'll have something else you will like to try out.

**Comment by AntiFly** [comment]
Yeh ok, email u after work ;)

Von meinem iPhone gesendet
