### ISSUE TITLE
Lost remaps. settings and save states when updating Retroarch and cores?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#177]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * retroarch used (filename): 177
  * hmod(s) used by the game you are having problems with (filenames): various
  
### Step 2: Describe the problem:
  
  * Every time I update my Retroarch and hmods (ie, everytime Kyland posts updates for them), I update using the following process...
1 - uninstall retroarch and current hmods
2 - install new hmods
3 - install new retroarch

I find that after this, I regularly lose my saved key remaps (Fuse, Vice etc), settings, and also save-states. 

Am I missing something? Please advise!
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo/Sega/Sony Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
@bolton80 If you uninstall stuff, you will typically lose settings.  I have things set up in such a way that if you are on my set to begin with, you can simply Update without needing to uninstall.  Cores and RetroArch should replace previous builds.  

As far as specific settings, I can help you maintain them, if need be...especially if they relate to overlays/borders, other such game/core designations.

Save states should be fine, and have worked in testing, aside from Fceumm, which I will account for in this upcoming Release.  Which save states were you having issues with, exactly?  

Lastly, let me know what you might need help maintaining settings wise, and we can go from there.

PS.  When I update, simply "force" install the Cores/RetroArch atop the current ones.  Even if they show up as grey in hakchi, they will be fine to just update.  If there is a time when something does need uninstalled, I typically notate that.  For now, updating is fine:)

**Comment by bolton80** [comment]
Ah, good to know. Thanks.
