### ISSUE TITLE
Is it possible to load .cas files on BlueMSX?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#178]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * retroarch used (filename): km_RetroArch 177 Xtreme
  * hmod(s) used by the game you are having problems with (filenames): km_BlueMSX
  
### Step 2: Describe the problem:
  Is there a way of automatically loading .cas (cassette) files on BlueMSX? When you try to start a .cas file in BlueMSX using the standard command line, it just loads the normal MSX start screen. Presumably this is because there is a command that needs to be entered before it would load a .cas file. I wonder is there a way of doing this without a keyboard or ridiculously long-winded remapping process?
  * _____
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo/Sega/Sony Classics Discord](https://discord.gg/bX9PqrC)

**Comment by gingerbeardman** [comment]
See the BlueMSX manual http://www.msxblue.com/manual/runningcas_c.htm

**Comment by KMFDManic** [comment]
@gingerbeardman Thanks for the assist on this.  @bolton80 Yes, they do work.  But, you'd want a little experience, plus a keyboard, to pull these off.  Definitely, if at all possible, try to run rom or disk versions, as gingerbeardman suggested.  If you do have a keyboard and USB-HOST, however, you should be able to handle this, if you generally know how to handle .cas games on the real hardware with the appropriate commands.  The documentation above should help:)

**Comment by KMFDManic** [comment]
@bolton80 Can confirm these do work.  They just aren't user friendly.  If you have any specific ones you are hoping to play, feel free to respond.  I will see if I can help or find an alternative solution that is more user friendly:)

**Comment by gingerbeardman** [comment]
I would say that there are few reasons to use .cas files these days. If you look a little more, you'll find better sets.

- prefer .dsk or .rom
- if required you can even convert from .dsk to .rom (read only) using https://www.msx.org/news/software/en/dsk2rom-080

Plus, there are compilation selections of older cassette games as MSX Mania Collection, or Rompocalypse sets of disk games, TOSEC which contains all formats.

What .cas file are you trying to run?
