### ISSUE TITLE
NEStopia Cheats $6000-$7FFF Memory Range

### ISSUE THREAD

**Issue by lowbred** [KMFDManic/NESC-SNESC-Modifications#179]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.2
  * retroarch used (filename): 1.7.4 - 1.77
  * hmod(s) used by the game you are having problems with (filenames): All NES cores
  
### Step 2: Describe the problem:
Is it possible to access SRAM addresses $6000-$7FFF with any NES core? If not, is this something that will be soon or in a future release?
Big THANK YOU KMFDManic for all your YouTube vids! Informative and entertaining.
  
### Notes: Are you in the right place?
Hope so...

**Comment by lowbred** [comment]
There are many games that implement cartridge RAM... I'm sure you know. One specific cheat would be "Inventory Modifier..." for SMB3 / https://gamehacking.org/game/31021
The desktop v's of Nestopia and FCEUX allow access to this memory range. For the first time, after creating this thread I tried the desktop v of RetroArch and with all the NES cores there was no access to the memory range. If this is a limitation of RetroArch and or the cores it would be a great addition to one or the other or both.

**Comment by lowbred** [comment]
RetroArch cheats allow...
cheat??_address = "??"
The RAM address for "Inventory Modifier..." for SMB3 is 7D80:??, that hex is then converted to decimal = cheat??_address = "32128"
I hope I'm correct and RetroArch doesn't use some other conversion above a certain memory range. With all the research I did with google, I couldn't find any info to make me think otherwise.

**Comment by KMFDManic** [comment]
Was finishing up with work and another Update.  Did you, by chance, try manually patching codes like these to the games, then attempting to run them with the Cores?  Just curious.  This will take a little more looking into to see how it would behave.

**Comment by lowbred** [comment]
Always something to do, right. I've never made a patch for a NES game. It's something I may research into. I figured I would go right to the man who taught me everything I needed to know about the mini classics, if it's not possible to do this as of yet... I'm glad I have your wheelhouse going a bit :) and hope it will be implemented in a future update. Thanks.

**Comment by KMFDManic** [comment]
@lowbred I am referring to something more akin to GGGuy (Game Genie Guy), a tool that will allow you to patch codes permanently to NES roms, etc.  Some cheats did not work for Turbografx-16 on the Mini Classics.  So, I devised that workaround to account for that:)

https://hakchi.net/KMFDManic/NESC-SNESC-Modifications/KMFDManic-S-NESC-PSC-Cores_6-15-19/_km_Xtras/PERM-CHEATS-PATCHING/

Just because a Core may possibly not support certain values, does not mean you can't apply them elsewhere and still run the games on said Cores.  You aren't changing the mappers:)

**Comment by lowbred** [comment]
@KMFDManic "This will take a little more looking into to see how it would behave."
I'm gonna give this a go and give you an update.
Off topic... RA 1.77 clover pop-up message in the lower left corner "Nintendo Clovercon #1 configured in port #0...
Is there a way to adjust the position of this pop-up message like the notifications from RA? I searched reddit and I seen you replied to a couple posts about disabling it, do not want to do that. I use the mini on my TV and the left side and the lowest part of the font is just off-screen.

**Comment by KMFDManic** [comment]
Check for an overscan or aspect ratio setting on your tv, as it should display it all.

**Comment by lowbred** [comment]
Duh... Me over thinking it maybe just a little... Always had it on 16:9, there was a 'Fit to screen' setting. Thanks :) I'll get back to you by the end of the weekend.

**Comment by lowbred** [comment]
GGGuy was a no go. It's a dumbed down cheat system RA has. It would be nice if Libretro develops a more advanced cheat system but it's not something that is a must "game changer." Pun intended... I'm out of ideas, if you have any other suggestions, let me know. Otherwise, I think this thread can be closed down. I'll keep YouTuning in. Thanks.

**Comment by KMFDManic** [comment]
@lowbred Two things you can do.  One, open up a "feature request for this" on RetroArch, Nestopia Repos.  

https://github.com/libretro/nestopia (rdanbrook) is great!

https://github.com/libretro/RetroArch (in the event it needs done RetroArch wise, like last years cheats overhaul!)

Either way, despite cheats being low priority...there is still a chance it could be worked in, if it doesn't already exist...in some capacity:)
