### ISSUE TITLE
GBA Saving Bug

### ISSUE THREAD

**Issue by Grumstrum** [KMFDManic/NESC-SNESC-Modifications#18]
Some GBA games are not saving correctly. People have around found there is a fix by changing the sleep value

https://www.reddit.com/r/miniSNESmods/comments/76g7r4/mother_3_isnt_saving/

**Comment by gingerbeardman** [comment]
see: https://github.com/ClusterM/retroarch-clover/issues/80

**Comment by KMFDManic** [comment]
I was aware of this for awhile.  But, I will apply a fix to RetroArch in my Core Set today, as well as do a video.

**Comment by KMFDManic** [comment]
Fixed in my latest update:)
