### ISSUE TITLE
FDS Disc Swapping not working?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#181]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * retroarch used (filename): 177 xtreme
  * hmod(s) used by the game you are having problems with (filenames): nestopia
  
### Step 2: Describe the problem:
  
I've finally added some FDS games to my SNES mini. I have the disksys.rom file in the system folder, the games start up ok, but when it gets to the "Please insert Disc B" screens, I can't get any further. I've checked and L and R are set for Disc Eject and Swap Disc, but neither of them are doing anything when I press them. Each game only seems to come in one .fds file, so I don't think I'm missing anything in terms of files. Please advise?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo/Sega/Sony Classics Discord](https://discord.gg/bX9PqrC)

**Comment by bslenul** [comment]
Hm no problem here, tested with Zelda, with Nestopia simply press L once and wait 1-2 second it should automatically switch side.

With FCEUmm you have to press R to eject, then L to swap and R again to insert.

**Comment by KMFDManic** [comment]
@bolton80 I will need to do an Updated video on this:)  An oldie, but still applicable!

https://www.youtube.com/watch?v=XcBTny_tCCo

**Comment by KMFDManic** [comment]
@bolton80 If you still have any trouble, let me know:)  But, the video I showcased should work perfectly as far as running games that "do" work!

**Comment by bolton80** [comment]
Hi Kyland,

Sorry for not replying sooner. I've got the disc-swapping working after watching your video. Thanks!
