### ISSUE TITLE
Bezel mode not working in new update (15/06/2019)?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#182]
### Step 1: Describe your setup:

  * hakchi2 CE version: 5.3.5
  * retroarch used (filename): 177 xtreme
  * hmod(s) used by the game you are having problems with (filenames): most of them
  
### Step 2: Describe the problem:
  
  * Since updating my retroarch and cores with yesterday's update, my bezel mode isn't working properly. I've tried holding R when starting a game (which always worked in the past), but it isn't working. Is there some other setting I should try?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo/Sega/Sony Classics Discord](https://discord.gg/bX9PqrC)

**Comment by AntiFly** [comment]
I guess you need to activate it first as per game or per core within retroarch.

Release notes ;
changed bezel-mode like I did with RA Neo in the past: L on start toggle for game, R for core (not EVERY game anymore, which seemed a bit pointless tbh).

**Comment by bolton80** [comment]
That's what I have tried. For some reason it works on certain cores (mame 2000 / genesis plus gx), but not on most others. It always worked until yesterday's updates.

**Comment by bolton80** [comment]
Here's a few of the cores where I cannot enable bevels...
- stella
- fuse
- PCSX ReARMed Neon
- Vice x64

Bevels ARE working on:
- Mednafen PCE Fast
- Mednafen SuperGrafx
- MAME 2003 Xtreme

I haven't tried the others yet.

**Comment by bslenul** [comment]
Thanks for the report, this is happening because of bundled overrides, I'll take a look and see how I can handle that differently. I'll keep you updated 👍

**Comment by bslenul** [comment]
https://www.mediafire.com/file/x9xswabjl33szv9/_km_retroarch_177_xtreme.hmod/file (temporary link until its updated in the Mod Hub)

Updated, should work fine now, thanks again for pointing this :)

**Comment by KMFDManic** [comment]
@bslenul Thanks!!!

@bolton80 Will be on Mod Hub in a short bit.
