### ISSUE TITLE
folder directory of hmods showing with a space hint does not show in hackchi

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#183]
[hmod_audit.txt](https://github.com/KMFDManic/NESC-SNESC-Modifications/files/3294320/hmod_audit.txt)
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * hmod(s) used by the game you are having problems with (filenames): 15.06.2019
  
### Step 2: Describe the problem:
  
  * bios and ppsspp font core completely missing in this update
-> KMFDManic-S-NESC-PSC-Cores_6-15-19.7z

removing the filesize after the dir will make them appear again (.567bytes).

so i completely missing ppsspp fonts and bios hmod within hackchi if just copy paste your pack ;)
please fix.

**Comment by KMFDManic** [comment]
This is also fixed, and reposting in a few:)
