### ISSUE TITLE
NeoCD not working

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#184]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * retroarch used (filename): 06-15-19
  * hmod(s) used by the game you are having problems with (filenames): _km_neocd.hmod
  
### Step 2: Describe the problem:
  
  * updated the new bios files onto the existing ones. (same md5, added unibios 3.2)
* core shows files as present.
 * game start does not work, black screen and fallback to hackchi game selection.

reflashed the device twice... ;(

![grafik](https://user-images.githubusercontent.com/38633765/59569318-1263e780-9088-11e9-9c8a-a85971ee2c21.png)

**Comment by KMFDManic** [comment]
@AntiFly Fixed:)

https://drive.google.com/open?id=1-ZL9WKM2L5wOktwKLgc_3mtp1q_2DoYP

You rock, as always:)
