### ISSUE TITLE
Hotfix touch date within core note updated

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#185]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * hmod(s) used by the game you are having problems with (filenames):currently updated hotfixes
  
### Step 2: Describe the problem:
  * I know this is crying at high level but the touch date (within core/hackchi) isn´t correct as the hotfix should be dated to 06-17-19 not 06-15-19 ;-)

no bug buts kinda hart for non experienced users to know if the file is up to date (hotfix) or not ;)
cheers

**Comment by KMFDManic** [comment]
I kept 6-15 to keep things in synch with the update.  Everything is updated now:)  Next full update, things will change:)

**Comment by AntiFly** [comment]
yeh I can understand that. I just wanted to give the information, because its from the point of my view a unluckyly state ;)
as you saw it could unsettle peeps not to determine whats the newest file (obviosly no version number or hint through the date) xD

**Comment by KMFDManic** [comment]
@AntiFly Hot Fixes are usually pretty rare:)  I just wanted to avoid having too many of the HMODs off of the base point date.  We are already working on the Next Update, with more great additions for RetroArch.  Will be fixing up over 100 games:)  And, several Cores will load and exit faster!  With the new Server Hosting Site I am on now, can get Advanced Music Hack/Arcade Borders, and other stuff back up, too.  MZ cut down the limits to 15 GB, which wasn't quite enough for what I wanted to keep live:)  Confirm NEO-CD is working for you!  Working great on my end!

**Comment by AntiFly** [comment]
Yup neocd is working like a charm.
Thank you, kinda awesomeness xD

Von meinem iPhone gesendet
