### ISSUE TITLE
Games not working on PUAE-Standard and PUAE-Xtreme?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#186]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * RetroArch used (filename): 177 extreme
  * hmod(s) used by the game you are having problems with (filenames): PUAE & Extreme
  
### Step 2: Describe the problem:
  
  * Some of my Amiga games don't work with either Core. e.g. Cannon Fodder 1 & 2. The games appear to lead normally, but the input doesn't work. Even pressing Start and Select to access the Retroarch menu is delayed (it may or may not appear 30 seconds after pressing). Is there a solution to this?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo/Sega/Sony Classics Discord](https://discord.gg/bX9PqrC)

**Comment by bolton80** [comment]
'lead' should say 'load'. That's what happens when you're drinking vodka whilst typing :-)

**Comment by KMFDManic** [comment]
```P-UAE = kick31.rom, WHDLoad.hdf containing kick34005.A500, kick37175.A500, kick40068.A1200, and kick33180.A500
Direct Load feature, additionally, requires kick34005.A500, kick40063.A600, and kick40068.A1200, in system. (Amiga) ```

You can use Direct Load, as far as non AGA games.  The LONGER load time might be a result of an install conflict, and/or even OTG going bad.  I just had an OTG go bad, the Inateck, in fact:)  But, I have unplugged and plugged it in thousands of times, hehe:)

In any case, if you are suddenly getting longer load times, it would be an install conflict or OTG going bad...sometimes just the hard drive/flash drive needing a little check-up.  Inputs not working, you would push L2, if you have it, to switch between Joy/Mouse mode..Whilest on Joy mode, you can start games with the A button.  Hope that helps!  

I did a retest, and as of the time of this post, games/cores, you refer to...both loading absolutely fine.

**Comment by bolton80** [comment]
Hi Kyland, I'm trying to find the additional kick34005.A500, kick40063.A600, and kick40068.A1200 roms needed. Once I find them I'll give it a try. Don't suppose your cat is near your keyboard again is he?

**Comment by bolton80** [comment]
I can't find the kick34005.A500, kick40063.A600, and kick40068.A1200 roms anywhere online. Does anyone know where to get them please?

**Comment by KMFDManic** [comment]
@bolton80 grey area:)  You ever join our Discord, as of yet?

https://discord.gg/SpGNDf2

You can join and communicate with me there, directly, and will try to help resolve your Amiga woes.

**Comment by bolton80** [comment]
Hi Kyland, I've now joined Discord. I probably sound like a completely out-of-touch idiot, but how do I contact you on Discord? My username is bolton80#2264

**Comment by gingerbeardman** [comment]
> I can't find the kick34005.A500, kick40063.A600, and kick40068.A1200 roms anywhere online. Does anyone know where to get them please?

google: _kick34005.A500 "index of"_

http://files.swos.eu/amiga/kickroms/
