### ISSUE TITLE
Philips CD-I won't run?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#187]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3  * RetroArch used (filename): 177 Xtreme
  * hmod(s) used by the game you are having problems with (filenames): MESS
  
### Step 2: Describe the problem:
  
  I've followed your instructions, but I can't get CD-I games to start. 
- Downloaded the new updated cores.
- I've installed the updated MESS dependencies hmod (as it was, I didn't need to add bios to it did I?)
- I've installed the updated MESS hmod
- I've installed the updated Retroarch 177 hmod
- I've added Hotel Mario (Europe).zip to Hakchi. It contains the .cue and .bin files.
- I've then opened the CLV folder, created a 'cdimono1' folder in it, 
- I moved the Hotel_Mario.zip file into the cdimono1 folder
- I then added the cdimono1.zip file (bios) to the cdimono1 folder
- My cdimono1 folder therefore contains the Hotel_Mario.zip file and the cdimono1.zip bios file
- In Hakchi I changed the command line to: 
/bin/mess /var/games/CLV-Z-QVUMW/cdimono1/Hotel_Mario.zip
- I closed Hakchi, opened it again, and then synchronised my USB stick to upload the new game

When I try to then open Hotel Mario on my SNES mini, I get a blank screen for around 15 seconds, and then I just get the Retroarch menu showing nothing is loaded.

From there I even tried to 'Load Content', browsed for the Hotel Mario.zip file and tried to load it that way (using the Multi - MESS core), but I get the same result.

I tried the same process with Link: Faces of Evil with the same result.

I MUST play Hotel Mario again after all these years (I played it once at a promotional CD-I stand at Wimbledon when it was released).

Where am I going wrong please?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo/Sega/Sony Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
@bolton80 In Xtras/MESS, is the set of CDI_blank.files you need to run the game.  You would copy whichever mario hotel zip file, for example, hotmario.zip or hotmariou.zip.  THIS is what gets added as a game, not the actual game.  THEN, you would create cdimono1 folder and have hotmario.zip, the cdimono1.zip bios AND the fully extracted CD-i game in there.  You also need the MESS Dependencies HMOD installed.  I will try to get a Tutorial up for this over the next few days.

**Comment by bolton80** [comment]
Thanks Kyland. I haven't managed to get it running still, so will look forward to the tutorial

**Comment by KMFDManic** [comment]
@bolton80 Due to the more complicated nature of running CD-i, you can go to our Discord and ping or pm me there, and I can directly assist you, if you still want to have these games running:)
