### ISSUE TITLE
How to transfer NAND save states to USB drive

### ISSUE THREAD

**Issue by langrisser1** [KMFDManic/NESC-SNESC-Modifications#188]
### Step 1: Describe your setup:

  * hakchi2 CE version: _3.5.3____
  * RetroArch used (filename): _1.7.6____
  * hmod(s) used by the game you are having problems with (filenames): _____
  
### Step 2: Describe the problem:
  
Hello mate,

I am still using the old RA 1.7.6. The save states are on NAND while the game roms and other settings are on USB drives. 
If I update the RA to the latest RA xtreme, how can I move the save states from NAND to the usb drive? 
Will the save states being automatically moved from NAND to "usb:\hakchi\retroarch\states" after the latest RA xtreme update?

Thanks for your help~ :)

sam

**Comment by KMFDManic** [comment]
That path is for RetroArch saves.  Normal saves would be hakchi/saves  You can make sure the hakchi/saves directory is created on USB, and then all NEW saves will go there.  To move old ones, use this:)

https://hakchi.net/KMFDManic/NESC-SNESC-Modifications/KMFDManic-S-NESC-PSC-Cores_7-23-19/_km_Xtras/_USB-HOST/Saves/

**Comment by langrisser1** [comment]
Thanks~~~
