### ISSUE TITLE
_km_uae4arm_xtreme.hmod gone ??

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#189]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3..5.3
  * RetroArch used (filename): latest
  * hmod(s) used by the game you are having problems with (filenames): _km_uae4arm_xtreme.hmod
  
### Step 2: Describe the problem:
  
* hi mate, i am missing _km_uae4arm_xtreme.hmod, where did it go ?
 I looked over the latest news but only read about puae not uae4arm ... so why this is missing?
does puae will take place for it ?

cheers

**Comment by KMFDManic** [comment]
UAE4ARM Xtreme is no longer needed, whatsoever.  P-UAE Xtreme can now handle nearly every game, with far better sound than UAE4ARM (which, despite having dynamic recompiler, has "warped" sound.  You may have seen my latest video, where I run Agony way better with P-UAE Xtreme?  As always, you are welcome to email me, if you need anything, mate:)
