### ISSUE TITLE
easyrpg mod (rpg maker on snesmini)

### ISSUE THREAD

**Issue by altlyser** [KMFDManic/NESC-SNESC-Modifications#190]
Hi.
I use EasyRpg in my SNES mini. Version: 9-9-19 HMOD By: KMFDManic
I am using the link to the INI file and I have a red screen error “invalid encoding: ibm-5346_p100-1998”.
If I link to a zip file with the game, EasyRpg does not find any games, but it starts mod.
Please help, thanks.

**Comment by KMFDManic** [comment]
@altlyser You closed the issue.  I was looking into it and was able to get it running on other platforms.  It is still stubborn on the Mini Classics.  Did you find anything else out, test wise?

**Comment by altlyser** [comment]
does not work, but I wrote in chat chatting with rpgplayer dev and they don't know the solution. The problem is with the game, IUC files (or somehow). 
They said that, I don't know :(

**Comment by KMFDManic** [comment]
By the way @altlyser this is fixed now!

**Comment by altlyser** [comment]
wow nice, but now... i have a playstation classic :) (with retroarch).
somewhere I will find a working version for psc?

**Comment by KMFDManic** [comment]
I posted it for PSC, too.  If you go to my Release page, Google Drive link, PSC, folder, you can use AB, modification, then install the Xtreme Core Set injector. No matter the case, I can help you get it up and running now.

**Comment by altlyser** [comment]
Wow, it really works !!!
https://i.ibb.co/WKxS9rd/IMG-3694.jpg
Thanks for the help.
Finally, I will turn on my first game from 2003 ... :)
Thanks also to Ghabra - he helped me a lot on Discord.
