### ISSUE TITLE
New Update 9-9-19 and fbneo/mame2014

### ISSUE THREAD

**Issue by altlyser** [KMFDManic/NESC-SNESC-Modifications#191]
hello KMFDManiac. I recently updated my cores in Hakchi (CE 3.5.3) to version 9-9-19 and fbneo (and MAME 2014) have stopped working.
before I didn't have BIOS MOD, only I put BIOS files into roms.
I can't install bios in this version :(
either I have a bad bios or I install it wrong, but it worked before.
can I download previous versions of mod fbneo and mame2014 somewhere?

games know that they work on the previous version
`88 Games Konami, requires no BIOS, and doesn't work now

**Comment by KMFDManic** [comment]
Both of these should work, as of the last Update.  There is a possibility you overloaded NAND with too many Cores/etc.  For SNES Classic, however, I would most recommend using MAME 2003 Plus/Xtreme and FBA 2016, for the best combination of Arcade awesomeness.  88 Games does work fine with Xtreme.  Keep me posted:)  I will retest these when I post next Update tomorrow:)

**Comment by altlyser** [comment]
Ok thanks, works fine with FBA 2016.
