### ISSUE TITLE
OC Check

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#194]
Just as an Idea here.
how about a OC "benchmark" test for the device could be a link on the screen which will just render anything or stress the cpu for some minutes, if this will pass we will know if our device is OK for OC or not ;)

This could test different ocs. Level1 - Level 3 or so... if l1 pass user can l2 and so on and find out hardware capability of possible oc for his device ;-)
yeh well im fully fucked on this because mine even cant use the current one but others would benefit from this.

**Comment by KMFDManic** [comment]
This was a proposed idea of DanTheMan827, as well!  The execution of said idea would just need to be figured out.  But, kind of like a diagnostic test, of sorts.  I would actually love to test 1.5 Ghz, as well.  But, there is a "block" somewhere preventing it from going past 1.34 Ghz!

**Comment by KMFDManic** [comment]
@AntiFly 

This will give you MAIN UI accessibility to turning OC on/off, on the fly, and does NOT require OC HMOD to be installed.  It will just automatically revert to 1.2 Ghz on shut-down.  This will be in Next Release.  Feel free to test, if you'd like:)  Huge thanks to a great mate, bslenul, for working in this stuff!

[Easy_Overclock.zip](https://github.com/KMFDManic/NESC-SNESC-Modifications/files/3811901/Easy_Overclock.zip)

**Comment by AntiFly** [comment]
@KMFDManic  ye this is working for me. 
will there be more switches as i mentioned to increase and decrease the amount of overclock in the future ?
