### ISSUE TITLE
Dosbox gamepad mouse emulation not working

### ISSUE THREAD

**Issue by sionisaac** [KMFDManic/NESC-SNESC-Modifications#196]
### Step 1: Describe your setup:
Autobleem 0.7.1 clean
Latest version of  psc xtreme core injector
DOSBOX SVN Core

  
### Step 2: Describe the problem:
 Mouse control via gamepad is not working.  No matter if I turn on core options and advanced options.  Enable gamepad mouse emulation.  Set input device to keyboard and mouse.  Cannot assign mouse controls to gamepad or analog stick.  Tried with input set on gamepad and joystick too.  Works fine on windows vanilla retroarch.  Tried third party mouse driver for DOS inside the Dosbox core as well even though it wasn't necessary on the PC version.  Still no joy.  I'm pulling my hair out with this because there are some awesome DOS games that need mouse control.  And I've got hundreds already setup with conf files on PC, Wii, Xbox, Rpi.  Any help appreciated.

**Comment by KMFDManic** [comment]
I will be posting an updated DOSBox SVN within a couple days.  Which controller are you trying to run with, as I have been running mouse games with my controller without issue?

**Comment by sionisaac** [comment]
Dual shock 3.  But also tried the standard psc controller.  Neither work or allow mouse controls to be mapped to the gamepad.

**Comment by sionisaac** [comment]
Figured it out.  Retroarch hadn't setup my dual shock 3 correctly.  I thought that the auto map had set it all up but I noticed that when I played Ape Escape on psx the right analog wasn't working properly.  I've got it working now but for some games having the mouse mapped to the right analog is really difficult to control.  I find that I'm holding the controller right hand side grip in both hands just to get more control.  I had it setup to the left analog on my pc and retropie but I believe I had to use an xbox360 driver for the pad.  Is there any way to setup left analog to mouse controls on psc?
Also tried the latest update with new Dosbox SVN core and it's playing havoc with a lot of my existing conf files that were working on the last version.  Games that were working but are now glitched to pieces include Burn Cycle (on windows 3.1), 11th hour, lba2, Voyeur II.  I notice that there are a lot more options for the core so maybe it's just a case of playing around with these.  It's just unusual because I thought that when you load a conf file in Dosbox it overrides any other settings.  Surely if they were working before on the previous core they would still work on the updated core because game specific configs had not changed.  I'll try and upload a video in next few days to show a comparison.  

Great work on the Saturn update btw just been playing Nights into dreams and it's well playable.

**Comment by KMFDManic** [comment]
Awesome.  Glad you got things sorted out! I will follow up with you on DOSBox.  You are referring to the PSC, or no?

**Comment by sionisaac** [comment]
Psc.  I'll try and get some video done in next few days of the old core against the new one.  I'm just wondering if I've already got the setup how I want in the conf file how do I get the new dosbox svn core to ignore the core settings in favor of the conf settings?

**Comment by KMFDManic** [comment]
I can post some test setups for you to try.

**Comment by sionisaac** [comment]
Awesome!  Please.

**Comment by KMFDManic** [comment]
Thanks for being patient.  With the next Release I post, there will be 3 DOSBox Cores you can mess with!  Between the 3 of them, you should be in a better place!  And, as far as ignoring Core Options PER Game, the best way to go about this is to go to Core Options, Save GAME Options Override, then set them as you need for THAT game, then back out, and Game Override:)  But, again, there will be 3 completely different DOS Cores to play with Next Update!  They each have their perks and negatives.

**Comment by sionisaac** [comment]
That's awesome.  I'll hold off doing a video comparison until the next release.  In regards to the game specific configs.  My Dosbox setup with the release prior to the newest was to have a conf file for each game and in that conf file would be the settings for the environment cycles, processor spec, memory etc.  I've always used this method to setup the Dosbox environment per game hence I wrote the wiiflow Dosbox plugin specifically to load conf files.  So you can imagine how many conf files I have.  My whole DOS library.  Using the conf method seemed to work great on retroarch with the previous Dosbox core once I'd figured out the mouse emulation and mapping the keyboard controls so it was easy to edit the existing conf files just changing the path which I did with a script so took no time.  But when I upgraded to the newer SVN core I noticed that all the environment settings in the conf files were being ignored in favour of the new core options.  When I attempted to mirror the conf settings with the core options and make game specific options I noticed that some of the games with jittery compared to the last core and some games didn't even run.  My windows 3.1 games were running ok on the last release with my specific settings but one the newest release with the same settings in the core options it seems to be a lot slower.  E.g. Burn Cycle would start windows with no splash and autorun the game in about 10 seconds on the old setup but on the new with exactly the same conf settings and core options it takes about twice that time and crashes on the game intro unless I press a button to skip it.  Anyway I'll wait for the next release and put it through the paces.  It's all good btw and I like challenge.  I'm loving your core sets and being a real old school gamer I have loads of ideas for improvements especially for the older systems (I'm talking stuff that can only be emulated with the MESS core in retroarch)

**Comment by KMFDManic** [comment]
@sionisaac You should be fine with latest Release:)
