### ISSUE TITLE
Quake Mission Paks not working

### ISSUE THREAD

**Issue by sionisaac** [KMFDManic/NESC-SNESC-Modifications#197]
### Step 1: Describe your setup:
Autobleem 0.7.1 clean
Latest version of psc xtreme core injector
Tyrquake core
  
### Step 2: Describe the problem:
Official mission paks will not work. I have the following folder structure:
Quake/Id1/pak0.pak
                     pak1.pak
            /rogue/pak0.pak
            /hipnotic/pak0.pak
            /dopa/pak0.pak

Quake shareware and full game work fine.  But any other mission pack returns to retroarch.  Did a bit of searching the forums and an older version of the core had an issue with folder structure where all mission folders had to be put under the Id1 folder so I tried that also but still not working.  Can anyone share a working quake1 playlist file so I can see the folder structure that works please.

**Comment by bslenul** [comment]
That's on SNESC but it should work the same, this is my folder structure and it works perfectly fine:

```
Quake/
├── id1/
│   ├── pak0.pak
│   └── pak1.pak
├── hipnotic/
│   └── pak0.pak
├── rogue/
│   └── pak0.pak
└── dopa/
    └── pak0.pak
```

**Comment by sionisaac** [comment]
I'm using exactly the same folder layout and paks dopa from the same source too.  Do you have a playlist you can share?

**Comment by bslenul** [comment]
```
{
  "version": "1.2",
  "default_core_path": "",
  "default_core_name": "",
  "label_display_mode": 0,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "items": [
    {
      "path": "/path/to/Quake/rogue/pak0.pak",
      "label": "Quake Mission Pack 2: Dissolution of Eternity",
      "core_path": "/path/to/core/tyrquake_libretro.so",
      "core_name": "Quake (TyrQuake)",
      "crc32": "38B70CE8|crc",
      "db_name": "Quake.lpl"
    },
    {
      "path": "/path/to/Quake/id1/PAK0.PAK",
      "label": "Quake (v1.06)",
      "core_path": "/path/to/core/tyrquake_libretro.so",
      "core_name": "Quake (TyrQuake)",
      "crc32": "74E3B084|crc",
      "db_name": "Quake.lpl"
    },
    {
      "path": "/path/to/Quake/hipnotic/pak0.pak",
      "label": "Quake Mission Pack 1: Scourge of Armagon",
      "core_path": "/path/to/core/tyrquake_libretro.so",
      "core_name": "Quake (TyrQuake)",
      "crc32": "D17835FB|crc",
      "db_name": "Quake.lpl"
    },
    {
      "path": "/path/to/Quake/dopa/pak0.pak",
      "label": "Episode 5: Dimension of the Past",
      "core_path": "/path/to/core/tyrquake_libretro.so",
      "core_name": "Quake (TyrQuake)",
      "crc32": "8A68D267|crc",
      "db_name": "Quake.lpl"
    }
  ]
}
```
That's the content of my Quake.lpl playlist (I added dopa manually, it didnt scan).

Of course replace the `/path/to` with correct paths for you :p

**Comment by sionisaac** [comment]
Tried a different approach.  I deleted the Quake1.lpl and did a rescan of the quake folder which is an exact mirror for your setup except the Quake folder is inside roms folder.  Inside the Quake folder is 4 folders Id1, rogue, hipnotic and dopa (using that exact case just incase the thing is case sensitive).  So exactly the same as in the playlist example.  It picked up the pak0.pak from Id1, rogue, hipnotic but not dopa.  Tried to run the games and it wouldn't run any of them even the the original game not the mission paks.  So I tried opening the content manually and it still wouldnt work.  the only way I can get it to play just the original quake (not the mission paks) is to copy pak0.pak and pak1.pak into the root Quake folder so that there is paks in Quake folder and duplicates (exactly the same files) inside Quake/Id1 folder.  None of the mission paks work no matter what I try.  (Uppercase pak file names doesn't work either).  This might work on the snesc but not on the psc.  I would like to see some proof that anyone has got the missions to work on the psc.  The mission files are correct also they run absolutely fine on pc retroarch, xbox quake port and wii quake.

**Comment by bslenul** [comment]
It should be `id1` not `Id1` for base game.

But yeah, it's possible that there's an issue with the PSC version, but I can't test with that unfortunately.
Does RA on PSC generates logs somewhere? That could be helpful.

**Comment by sionisaac** [comment]
Omg how stupid can you get.  Changed the folder name from Id1 to id1

**Comment by sionisaac** [comment]
Thanks for your help.  can't understand why the pc version is fine about the folder names and the psc version is'nt.
