### ISSUE TITLE
Slowdown of the bluemsx core when Retroarchs Rewind option is enabled.

### ISSUE THREAD

**Issue by ArieKindicator** [KMFDManic/NESC-SNESC-Modifications#198]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3 (debug); latest release
  * RetroArch used (filename): _km_retroarch_181_xtreme (KMFDManic-Mini_Classic-Cores_11-26-19)
  * hmod(s) used by the game you are having problems with (filenames): _km_bluemsx (and bios files installed)
  
### Step 2: Describe the problem:

When the rewind option of RetroArch is enabled, the blueMSX core slows down to ± 42-44 fps (stable) from 60 fps (MSX2+) or 50 fps (EU MSX2 machine). Arcade games (Mame 0.78/FBA 0.2.97.42-44), and other 8 or 16 bit cores don't slow down when the rewind function is enabled.
Retroarch Rewind option: enabled, using the default settings.

  This also happens with previous _km_retroarch_xxx_xtreme: 175-177. (I haven't tested older versions)

**Comment by KMFDManic** [comment]
Unfortunately, this is case by case, with the various Cores.  For example, SNES9x 2010/2016/2018 do not handle rewind well.  But, 2005 does.  You can also try fMSX to see if that fares any better.

**Comment by ArieKindicator** [comment]
Okay, thanks. I'm not a fan of fMSX.
