### ISSUE TITLE
picodrive: not saving (Mega Drive game)

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#2]
I'm playing [New 3D Golf Simulation: Waialae no Kiseki](https://www.segaretro.org/New_3D_Golf_Simulation:_Waialae_no_Kiseki) on Mega Drive.

Performance is much better (especially fast forward) in picodrive, but it will not save.

I have to use genesis plus gx, which is slower (no real fast forward), and it does save.

If it's easier to test feel free to use the only Western release in that golf series [Pebble Beach Golf Links](https://www.segaretro.org/Pebble_Beach_Golf_Links). 

After loading the game: 
- Create Data
- Register 
- Change the name 
- End
- Press B to go out of that menu and then go back in
- You should see the saved name you previously entered

This is just one example, other things that should save in the game also do not.

Any ideas?

**Comment by KMFDManic** [comment]
What is the exact command line for the game you are using?

**Comment by gingerbeardman** [comment]
My laptop is out of battery and it's past midnight here so I'm out of time for today.

But if you went to, say, emuparadise and downloaded a certain file I'm sure you could reproduce the issue. 

I also get the issue not using the command line, using "load content", "load archive" and then choosing the picodrive core.

**Comment by KMFDManic** [comment]
Which way are you doing Fast Forward in PicoDrive/Genesis Plus GX?  The way I do Fast Forward, which worked quite well in my test, is this...

RetroArch Settings, Frame Throttle, Enable Rewind, Back to Settings, Input, Input Hot Key Binds, Choose Fast Forward Toggle, and bind a key to it:)

Video of me doing this, but using Rewind, instead, is linked to below!  It works very nicely on Genesis Plus GX!  Also, in options, in the Updated Genesis Plus GX I just added, is a CPU Overclock function, to change speed from 100 percent to 125/150/175/200!  This should work for you, regarding your Golf Game, especially the fast forward function I stated above.  

https://www.youtube.com/watch?v=v2pU0x2LwVs&t=3s

As for the sram save issue, that seems to be a problem with PicoDrive, from version 1.91 and up that is still being looked into, from what I gather in my brief check!  Hope this helps!  Genesis Plus GX is quite an amazing Core!

**Comment by gingerbeardman** [comment]
I've just been setting the Hot Key Bind (as SNES pad R trigger button) and that worked fine in PicoDrive (but not Genesis Plus GX, as previously described).

I never use rewind, my use of fast forward is to just speed up the game whilst the computer player is taking their turn on the golf course.

Also: the CPU overclock function is awesome - makes the game smoother but not faster! Thanks for that

**Comment by gingerbeardman** [comment]
I got fastforward working! 

The issue for me that I was using BLARGG crt filter and that must really stress the system as FFWD doesn't gain any speed with it on.

**Comment by KMFDManic** [comment]
The cpu overclock helps in snes9x 2010, as well.  Issue can now happily be closed.  I will do more updates later:)

**Comment by gingerbeardman** [comment]
Just so it's not lost after the resolution of an issue with Genesis Plus GX... saving is still broken in PicoDrive (known problem)

**Comment by gingerbeardman** [comment]
Apparently this is fixed in 1.92? I'm yet to check myself

**Comment by KMFDManic** [comment]
Don't worry, I am still keeping tabs on it.

**Comment by gingerbeardman** [comment]
Case in point, latest PicoDrive in 3DS nightly is 1.91

**Comment by KMFDManic** [comment]
This is where things get weird.  Coding may work differently on the Mini NES/SNES, than on Android and/or PC.  So, we may use the exact same Core on 3DS and have it save.  But, on Mini NES/SNES, no.  Cores tend to have elements that cater to each platform.  But, sometimes, things get lost in transition.  But, yeah, 1.91 added 32x support.  But, lost sram save ability.  I will keep an eye out for 1.92 and see if it helps on our platform.

**Comment by gingerbeardman** [comment]
I might try my hand at merging 1.92

**Comment by KMFDManic** [comment]
I would recommend you be patient, as 1.92 is very new.  Barely over a week old, from what I am seeing.  I sense 1.92 will make it into the source very soon, on its own:)  Notaz decided to come back to it for 2 specific games.  So, I expect this to trickle down in our favor soon.

**Comment by gingerbeardman** [comment]
OK. I'm a patient man

**Comment by KMFDManic** [comment]
I will certainly compile it the moment it turns up:)  You now have pc-98 to play with, once u get snesc back.  So, the wait will not be so bad.

**Comment by gingerbeardman** [comment]
Apparently it was checked in over the last 24 hours, I'll wait for it to hit the nightlies for 3DS

**Comment by KMFDManic** [comment]
I will have to see what size I can get Surgical Strike 32x Sega-CD to, and hope its small enough to run on the Mini NES, at least.  The Mega Drive Cave Story will not be a problem running, though.  At least I have the perfect game to test!  Your Golf Game.  The BSX I Love Golf Game will be in my next video.  BSX Games are hella fun.

**Comment by gingerbeardman** [comment]
That's a great golf game too

**Comment by KMFDManic** [comment]
Picodrive Fixed!  And, it will be in my next update:)

**Comment by gingerbeardman** [comment]
Sweeeeeeet.

**Comment by gingerbeardman** [comment]
How did you go about it?

**Comment by KMFDManic** [comment]
Updated the code to 1.92:)  I will post the update tomorrow am.  It works great, though.  Notaz really did an excellent job with the update.  I am gonna have to try out the Cave Story MD.

**Comment by KMFDManic** [comment]
When do u expect to get your SNESC back?

**Comment by gingerbeardman** [comment]
Likely not this week, but don't worry about me

**Comment by gingerbeardman** [comment]
Out of interest, what games made notaz return to PicoDrive.

**Comment by KMFDManic** [comment]
Surgical Strike 32x Sega CD, and Cave Story MD.

**Comment by gingerbeardman** [comment]
Thanks to those, then!

**Comment by gingerbeardman** [comment]
Any chance you could look into picodrive 1.92 on 3DS? Nightly builds have stopped. Would appreciate it very much!
