### ISSUE TITLE
ViceX64 plugin: Cursor of keyboard disappeared and save states doesn't work

### ISSUE THREAD

**Issue by hoderer** [KMFDManic/NESC-SNESC-Modifications#20]
Sadly it's gotten worse with the vicex64-plugin: when I press Y and the keyboard shows up, there's no cursor. Also save states and 2nd player still doesn't work. I'm on the latest 11/2-update.

**Comment by KMFDManic** [comment]
This Core was not meant for the NES/SNES Mini.  So, we lose a little in transition.  I will retest Core changes in the morning to verify the cursor issue.  As is to be expected, save states do not function with all Cores.  Several are unreliable or non-existent when it comes to saving.  There are factors such as eeprom issues with MAME 2003.  I will look into these 3 things, and respond with follow-up.

**Comment by KMFDManic** [comment]
Thanks for the heads up on the "Cursor" Issue.  I will be rolling back the Core to fix this.  I will look more into the 2nd Player, when I can.

**Comment by hoderer** [comment]
That's great! Thanks alot!!!

**Comment by KMFDManic** [comment]
Updated.  Will check more into Player 2, when I can.

**Comment by KMFDManic** [comment]
@hoderer This should do the trick, for you...

1.  select+start, obviously, to pull up RetroArch Options
2.  Settings
3.  Input
4.  Input User 1 OR 2 Binds
5.  Select the button you want to change, then tap A, then tap the button you want it changed to!
6.  Keep in mind, if your B button is BACK in the RetroArch Options, and you reconfigure it to Y, Y will then become your back button!
7.  Avoid changing select+start, as then you will end up breaking your ability to use RetroArch Options!  And, you will need to uninstall RetroArch, then reinstall it!
8.  If you screw up, simply choose User 1 OR 2 Bind Default ALL!  
9.  Just back out to quick settings, then resume the game, to test things:)
10.  If satisifed with the mapping, leave it alone:)  It should save.  I powered off the system and back on and it worked absolutely perfectly.  
11.  Use Bind Default ALL when you want to revert.  And, do not forget, if you truly screw things up...Just uninstall RetroArch/Reinstall RetroArch:)  

This should do the trick:)  It also works with pretty much every other Core I tested:)
