### ISSUE TITLE
Atomiswave crashing again

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#200]
current Flycast hmod.

hmpf unfortunally i dont have your core release from september this year (that was the last working updated)
I have found the release for _km_flycast.hmod from 06-26-19 as working as well for me.
If you can supply me the release from 09-xx19 would be nice ? 

could it be also possible to build a flycast switch use .lst files again to work ?
because the .lst setup is at least working for me ;)
for dreamcast anyway i use reicast.

**Comment by KMFDManic** [comment]
I am gonna help you get them going on current Flycast, once I email you.  Your issue is one you don't even realize.  But, once I sort you out, you will be fine.

**Comment by AntiFly** [comment]
most appreciated ;) then i will wait for your mai.
thx

**Comment by KMFDManic** [comment]
@AntiFly Email me again, as somehow I am not seeing your latest emails in my inbox or sent.  In any case, I have the solution for you running Atomiswave/Naomi Games, and it may surprise you:)  I will run a few things by you BEFORE the Next Release, and include them in said Release if you sign off on them:)  I was working a bit of Overtime with my jobs, so didn't have a whole lot of time to dig too deep til just a few days back.  But, I also have bin/dats running fine with latest Flycast Xtreme!  I will get you to where you need to be to run these, and Overclock is NOT mandatory to run them:)  I will also post another video on how to run Atomiswave even faster, with me running Dolphin Blue practically full speed mode activate:)  Thanks, mate:)

**Comment by KMFDManic** [comment]
@AntiFly The provided email solution should fix your issue.  But, if you still have problems, I can get the Legacy Support posted, within a few days:)  Enjoy Amiga CD32, etc, for now:)  Email, and let me know:)
