### ISSUE TITLE
km_P-UAE Xtreme and IPF disk image support

### ISSUE THREAD

**Issue by ZzackKbin** [KMFDManic/NESC-SNESC-Modifications#201]
I dont know how run ipf disk image with km_P-UAE Xtrem Amiga core.

capsimg.so doesn't work in retroarch\system 
https://github.com/libretro/libretro-uae

**Comment by KMFDManic** [comment]
Install puae-xtreme and retroarch xtreme and .ipf games will work:)

**Comment by ZzackKbin** [comment]
For widnows capsimg.dll working but capsimg.so exmaple for retroboot playstation classic wont start working :(

**Comment by ZzackKbin** [comment]
Working capsimg.so with Retroboot PSC is in amiberry-rpi-v2.25.zip  and now ipf disk images works :)
https://github.com/midwan/amiberry/releases/tag/v2.25

**Comment by KMFDManic** [comment]
I actually already had ipf working on PSC for awhile.  U likely did not use the Xtreme Core Injector I posted.

**Comment by ZzackKbin** [comment]
I am new. I use this version: https://github.com/autobleem/AutoBleem/releases  
Are there differences between the cores of this version and the Xtreme  Core Injector?

**Comment by KMFDManic** [comment]
@ZzackKbin Using Injector in my PSC Folder, IPF games will work, as I have things set up that way.  Also, with the Amiberry Implementation that was just added to the Release.  Have fun!
