### ISSUE TITLE
Problem with Fuse - can't reset settings!

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#202]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.6.0
  * RetroArch used (filename): 179 Xtreme (W/Auto OC)
  * hmod(s) used by the game you are having problems with (filenames): Fuse
  
### Step 2: Describe the problem: This is my own fault. I adjusted a setting in Fuse, changing the emulated system to 'Pentagon 128' rather than a normal Spectrum model. Immediately when I tried to load a game, it crashed back to the SNES Mini main menu. The problem is, it saved the Pentagon setting, so now as soon as I try to open anything in Fuse it immediately crashes and I can't get back to the options menu to change it back to a normal Spectrum (which would presumably fix the problem).

I've tried uninstalling and reinstalling Fuse, but that makes no difference. How can I fix this please?
  
  * _____
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
Reinstalling retroarch should negate this.  Let me know:)

**Comment by bolton80** [comment]
That did it. Thanks Kyland and Merry Christmas!
