### ISSUE TITLE
Retroarch extreme 181

### ISSUE THREAD

**Issue by sebyd1** [KMFDManic/NESC-SNESC-Modifications#203]
Kyland there is a problem with the retroarch extreme 181 hmod it automatically changes the controller configuration on the snes mini classic I get message says
**nintendo clovercon controller not configured** 
I had to reinstall retroarch after playing N64 games with my wii pro controller
on the snes mini classic because I could not use the controller in port 1

**Comment by KMFDManic** [comment]
Should be fixed now @sebyd1

**Comment by sebyd1** [comment]
Kyland I solved the controller not configured problem in Retroarch Ozone for the Sega Genesis Mini all you need to do is format the usb flash drive to Fat32 not NTFS
