### ISSUE TITLE
Bezel Mode not working?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#204]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.7.0
  * RetroArch used (filename): RetroArch 181 Xtreme XMB
  * hmod(s) used by the game you are having problems with (filenames): Any
  
### Step 2: Describe the problem:
  
Bezel mode is not working properly. I have followed instructions, and am using border_with_scanlines.cfg but neither border nor scanlines are showing, despite them being selected and active in Canoe mode.
If instead of selecting border_with_scanlines.cfg  I select one of the Canoe borders, it DOES show that, but I want the standard borders AND scanlines. What should I do to resolve this?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
Should be fixed now @bolton80

**Comment by bolton80** [comment]
Hi Kyland, is there a new version posted or something?

**Comment by KMFDManic** [comment]
@bolton80 Had a few bugs I was able to fix up once I got heads up about them.  Just redownload, reinstall RetroArch Xtreme from KMFD Mod Hub, and you should be fixed on Bezels.
