### ISSUE TITLE
Various CD32 issues

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#205]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.7.0
  * RetroArch used (filename): RetroArch 181 Xtreme XMB
  * hmod(s) used by the game you are having problems with (filenames): _km_puae_cd32_xtreme
  
### Step 2: Describe the problem:
  Great to see CD32 support finally added (I used to own this system), but a few issues I have encountered...

FLINK - Runs but no sound

BUMP 'N' BURN - Starts up but locks-up on black screen before a race begins

SAVING doesn't seem to work. Any way of emulating the CD32s  RAM storage for game saves? The standard Canoe save process works, but as soon as the system tries to load  the next set of data it just freezes. Saving is vital for a lot of CD32 games (Cannon Fodder, Simon the Sorceror etc).

Hoping some of these issues can be ironed out in future releases?
  * _____
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
Flink should run when I do the next Update, with sound.  But, it may still not be super fast.  You can alternatively play the Sega CD version, which does run with sound and at full speed.  Save wise, I am adding a save hmod, which MAY work for CD32.  It is already testing to work fine with normal Amiga.  I will see if Cannon Fodder works with it, in the WIP I have going.

**Comment by KMFDManic** [comment]
@bolton80 CD32, like many other Cores, will be consistently WIP.  Hopefully, more and more will improve over time, and already will Next Update!  Thanks for the feedback, as always!
