### ISSUE TITLE
Retroarch Ozone

### ISSUE THREAD

**Issue by sebyd1** [KMFDManic/NESC-SNESC-Modifications#206]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.2
  * RetroArch used (filename): Retroarch Ozone
  * hmod(s) used by the game you are having problems with (filenames): Retroarch Ozone
  
### Step 2: Describe the problem:
  Kyland I modded the Sega Genesis Mini did the USB-Host mod I get error message in Retroarch Ozone says missing assets use the online updater controller not configured
  * _____
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
Did you, by chance, also install External RetroArch @sebyd1

**Comment by sebyd1** [comment]
Yes

**Comment by KMFDManic** [comment]
@sebyd1 I would recommend not using External RetroArch, as it is really not needed anymore, due to compressed Core Support, and additional NAND Memory unlocked on the Minis.

You will need to do a kernel uninstall, install/repair, install latest Ozone from Mod Hub, and you should no longer get the assets error.  Also, reinstall any other Cores/BIOS you need.

**Comment by sebyd1** [comment]
Perfect Thank you so much for your help

**Comment by sebyd1** [comment]
Kyland thanks after I followed your steps the assets error is gone but I
still get the controller not configured error problem

**Comment by sebyd1** [comment]
Kyland with USB-Host mod using hakchiCE for the Sega Genesis mini you still
need to install the external Retroarch because it's the only way you will
be able to install or copy and paste the bios files into the libretto
folder it creates via FTP with Filezilla

**Comment by KMFDManic** [comment]
@sebyd1 be careful when replying to emails, as your personal information will display here.  

No, you do not need External RetroArch for BIOS.  Use RA Master Bios Module from Mod Hub.  Copy BIOS into it, then install entire HMOD.  

If you get controller not configured, you may be using an unsupported controller and/or have an install conflict.

On MD, uninstall kernel, install/repair, install ONLY RetroArch, and test an NES game, then go from there.

**Comment by sebyd1** [comment]
I will try that thanks but for the controller I am using the official sega
genesis mini controller that came with the sega genesis mini you may need
to build a hmod for the controller not configured problem

**Comment by KMFDManic** [comment]
3 or 6 button?

**Comment by sebyd1** [comment]
3 button

**Comment by sebyd1** [comment]
Thanks for fixing the controller not configured problem I updated to latest
version of hakchiCE and installed Retroarch xtreme Ozone everything works
perfect I also installed the RM Master bios template but the bios files are
missing in Retroarch under the information core information section

**Comment by KMFDManic** [comment]
@sebyd1 If you view information via hakchi, while Master BIOS Module is selected, it will give you exact, case sensitive names you must use for said BIOS.  If you still need help, feel free to respond.  But, your initial issue is resolved, so closing the issue.

**Comment by sebyd1** [comment]
Retroarch xtreme Ozone works perfectly on the SNES mini but on Sega Genesis
Mini I get a message says controller not configured so I can't use the
controller at all
