### ISSUE TITLE
Samples not working in Mame2003 Xtreme since update?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#207]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3,8,0
  * RetroArch used (filename): 184 Xtreme Ozone
  * hmod(s) used by the game you are having problems with (filenames): mame2003 xtreme
### Step 2: Describe the problem:
  
  *I've noticed Space Invaders (invaders) and TARG (targ) samples are no longer working in Mame 2003 Xtreme since the last update. The sample files are saved correctly in the system/mame2003/samples folder and worked until now.
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
mame2003-xtreme is new path, to avoid conflicts with those on other platforms who choose to use the Core.
