### ISSUE TITLE
3DO (Opera) no disk swapping option?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#208]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.8.0
  * RetroArch used (filename): _km_retroarch_184_xtreme_ozone
  * hmod(s) used by the game you are having problems with (filenames): _km_opera
  
### Step 2: Describe the problem:
  
Now 3DO emulation is finally playable on my SNES mini (great work Kyland and co),  I'm trying to add a couple of multi-disc games (eg. Night Trap), but I can't find any option for disc swapping. Is there a way of doing this? I am using .chd files if that makes any difference? (Night_Trap_Disc_1.chd and Night_Trap_Disc_2.chd)

Opera doesn't seem to accept m3u files and none of the menus seem to have an option for swapping discs. Any guidance please?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
On the Mini Classics, if there is no Disk Swapping Option, it isn't as easy to tether saves from one Disk to the next.  The only thing I can suggest you try, for now, is to get to end of Disk 1, and hopefully it saves.  Then, copy that save to the location where Disk 2 is.  And, hopefully, when you load Disk 2, it loads.  I have been able to successfully do this with a few other ones, such as Zelda BS Ancient Stone Tablets, for example.

**Comment by KMFDManic** [comment]
@bolton80 If you have any other issues, let me know.  Another Update will be out within a few days:)  Stay Safe:)
