### ISSUE TITLE
Unable to launch ScummVM titles from NESC UI

### ISSUE THREAD

**Issue by Wilmatron** [KMFDManic/NESC-SNESC-Modifications#209]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.8.0 - Debug
  * RetroArch used (filename): _km_retroarch_184_xtreme_ozone
  * hmod(s) used by the game you are having problems with (filenames): _km_scummvm
  
### Step 2: Describe the problem:
  
  * I am unable to launch ScummVM titles from the main NESC User Interface after repeated attempts at following instructions provided by KMFDManic and following online tutorials. When attempting to launch from the UI, the screen goes black for a split second and then back to the UI again. Interestingly, the games launch successfully from Retroarch directly via 'Load Content'. I therefore suspect the issue is with the command line launch parameters in the Hakchi front-end.
For info, my command line is as follows:

**/bin/km_scummvm /var/games/CLV-S-ZTPCU/Beneath_a_Steel_Sky.scummvm**

Attempts include:

1. Installing the latest ScummVM HMOD and pre-prepared games from Hakchi Mod Store (to include Beneath a Steel Sky and Flight of the Amazon Queen'.
2. Re-creating the .scummvm launch file manually
3. Deleting and re-adding relevant game files to the game directory
4. Transferring game location from hakchi folder (USB-Host) to dedicated folder on the root of USB device.
5. Installing all Xtra ScummVM HMODs including the patches for 2.1.0 version
6. Adding the game manually via the ScummVM core launcher (as would be required for PC setup)

All of these methods have failed and I am now at a complete loss! Just to re-iterate, the games **do** launch and are fully playable when loading from Retroarch directly - I'd like to understand why I can't load the games directly from the NESC UI. Your help on this subject would be much appreciated - very fond memories of this platform.

## Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
In hakchi, go to KMFD Mod Hub, Games Tab, and grab Beneath a Steel Sky from there, and test it.  Also, try changing your command line to /bin/scummvm  I will do another test with both /bin/scummvm and /bin/km_scummvm before Next Release.  But, last test I did, I was able to run games with both of those.  Confirm.  Thanks for the feedback:)

**Comment by Wilmatron** [comment]
Hi Manic,

I appreciate the time you've taken to reply, and as suspected, the issue **was** the command line parameters. Let me explain...

When adding 'Beneath a Steel Sky' via the Hakchi Mod Store the command line is revealed to be **/bin/scummvm**  when selecting the game.

However when selecting the game and going to '_select emulation core_' via Hakchi, it "appears" that there is no core description associated with the game. When selecting the core 'ScummVM' from the drop-down this auto populates the command line parameters to **/bin/km_scummvm** which subsequently fails to launch the game from the NESC UI.

Having tested both **/bin/scummvm** and **/bin/km_scummvm** this evening I can confirm that **/bin/scummvm** works whilst **/bin/km_scummvm** does not.

Hopefully you will be able to fix this before the next release, but certainly not a show stopper - as long as you use **/bin/scummvm** you are gravy. Many thanks for helping me crack this one, and keep doing what you're doing. Amazing work.

All the best from England,
Wilmatron.

**Comment by KMFDManic** [comment]
@Wilmatron It is just one of the few Cores where I had to manually fix saves for it via script.  I will do what I can for the upcoming Update, and thank you for your feedback:)  km_ should work for nearly every Core, as I did placeholder shortcuts.  But, ScummVM may require a little additional scripting to fix.  I will look into it:)
