### ISSUE TITLE
Any specific configuration for save states in Snes mini?

### ISSUE THREAD

**Issue by Acc94** [KMFDManic/NESC-SNESC-Modifications#21]
Good afternoon, thank you for this amazing work but I have some issues with the saving thing. In N64 core, Im unable to save anything once the console is reload. In gba core, the in game save works but not the save state once I exit. 

Any option may I change in retroarch?

Thanks.

**Comment by KMFDManic** [comment]
Look at today's Core Update.  You will need RetroArch installed, from my set, in order to utilize In-Game Saves.  Manual Saves do not function properly.  GBA Saves, upon exit, are fixed:)  View the latest Update Info, and you will be fine with today's Cores:)
