### ISSUE TITLE
_km_retroarch_184_xtreme_ozone Themed

### ISSUE THREAD

**Issue by sebyd1** [KMFDManic/NESC-SNESC-Modifications#212]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.8
  * RetroArch used (filename): _km_retroarch_184_xtreme_ozone Themed
  * hmod(s) used by the game you are having problems with (filenames): No emulator problem 
  
### Step 2: Describe the problem:
Kyland I put the Nintendo 64 on the Sega Genesis Mini I mapped the super nintendo INNEXT usb controller in retroarch xtreme ozone to use the X Y A B buttons because I need the select button to play arcade games but when I use the generic Nintendo 64 usb controller and overwrite the A and B button I am unable to save the autoconfig and backout of retroarch also I can not use the A and B button in retroarch anymore
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
Things can be a little finicky with the Genesis Mini as far as controllers that are 3rd party and such.  Best way to remap is to do the mapping, then FTP it in.  You have any other Minis?

**Comment by sebyd1** [comment]
Kyland I found a solution you can use a SNES usb controller to navigate and
launch your N64 game on the Sega Genesis Mini then in game play switch
controllers to the N64 USB controller and continue your game play you don't
need to map the controller works great I already tried it with Mario Kart
64

**Comment by sebyd1** [comment]
Solved the issue
