### ISSUE TITLE
Failed to load Commodore Vic20 core

### ISSUE THREAD

**Issue by Wilmatron** [KMFDManic/NESC-SNESC-Modifications#213]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.8.0 (Debug)
  * RetroArch used (filename): 184 Xtreme Ozone (version April 27th 2020)
  * hmod(s) used by the game you are having problems with (filenames): VICE Xtreme (version June 21st 2020)
  
### Step 2: Describe the problem:
  
  * Neither **/bin/vic20** nor **/bin/km_vice_vic20_xtreme** load the core in Retroarch. Error message reads 'failed to load core'...

**Comment by KMFDManic** [comment]
I already have this fixed up for the very Next Update.  Retail games will mostly work, as well.

**Comment by Wilmatron** [comment]
Excellent. Thanks for the feedback, I look forward to the update in due course.

When the update hits will the Vic20 core come with its own specific core options (for changing memory allocation / region  etc) or will this need to be passed through via the command line in Hatchi?

**Comment by KMFDManic** [comment]
@Wilmatron Should be good to post this on Oct 6th.  And, those options will primarily be Core Based, not relative to hakchi at all.  Thanks for the feedback, and enjoy the Update once it posts in the next several days:)
