### ISSUE TITLE
N64 Games not working anymore

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#215]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.9.1
  * RetroArch used (filename): 1.9
  * hmod(s) used by the game you are having problems with (filenames)
  * 
- km_parallel_n64_xtreme
- km_glupen64_xtreme
  
### Step 2: Describe the problem:
  
  * Bomberman 64 not working properly (/bin/km_glupen64_xtreme) many glitches, windows not visible. parallel not working at all anymore, crash to snes menue. not working on MUPEN64 plus/xtreme as well.

* Yoshi's Story (not working on both, crash to snes menue
  
Both games worked on the core last year ;)

**Comment by AntiFly** [comment]
Yoshi's Story is working on Mupen64 Plus

**Comment by KMFDManic** [comment]
You on NES or SNES Classic? @AntiFly And, one thing to note is that "frame buffers" is a really bad issue with many games for N64 Emulations.  Once we get into more details, I am sure we can resolve whichever issues:)

**Comment by AntiFly** [comment]
snes mini ;)
bomberman is not that important for me, take it as a note that its not working (in my test) tested all of my added n64 games. this one was the only one i could not get to work again.

**Comment by KMFDManic** [comment]
One thing to note, the way I set up these Cores is, like for LudicrousN64..In Core Options, you can Overclock as well as Turbo Boost.  If you set Turbo Boost to X2 for a game like Smash Bros, it would run it considerably better.  Buffers do not emulate properly or well for ANY of the Mini Classics.  So, when they are in use, crashes, freezes, general instabilities may occur.  So, a game like Bomberman, you would need to run with Parallel.  Parallel should boot fine with Bomberman, as myself and another tested it.  If you FTP into your Mini, into etc/libretro/system/delete ALL N64 Folders that are there, completely!  These are unnecessary cache files that may conflict with current setup.  

If running games on whichever N64 Core, you CAN, for a select number of games, toggle frame buffer ON.  But, be prepared for some nasty issues, if you do turn it on.  Be careful:)  Keep me posted with parallel!  I can do a retest before next, fairly soon to be Release.

**Comment by AntiFly** [comment]
yeh i was running it with parallel all the time since last updtae, not working anymore. thats why i came up with this ;)
never mind. its not that important for me.
br

**Comment by KMFDManic** [comment]
@AntiFly Every bit of feedback matters!  If it does need fixed, I can see what can be done:)

**Comment by KMFDManic** [comment]
@AntiFly Be sure to keep in touch!  I will be doing a more comprehensive Update sometime in May.  Bomberman 64 is the primary game that you stated gave you issues with Parallel?  If you see my latest video with Excitebike, that will be one major fix up with Parallel, come that Update.  I still need to boost Amiga some more, as well!  In early WIP testing, I even have Amiga CD SFII working pretty damned nice!  And, Dreamcast will better handle those Atomiswave/Naomi Games!  Thanks for sticking by my side the last few years, and helping immensely with testing:)  You rock!  And, thanks again!  Be sure to give me a small list of bullet points, if there are any immediate things you feel I should try to account for with the May Release!

**Comment by AntiFly** [comment]
@KMFDManic 
Hey mate, I will test the next update after ready for service in time ;-)
For the Atomiswave/Naomi games, I completely removed them as the last major update broke it to play for me since I am not able to overclock my system (gets faulty while overclock).
have a good time ;-)
