### ISSUE TITLE
Google Drive Full obsolete stuff

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#216]
google drive ->

2GB obsolete file !
KMFDManic-Mini_Classic-Cores_02-28-21\_km_Xtras\GAMES\KMFDManic-Mini_Classic-Cores_06-22-20.7z

C:\SysDown\KMFDManic-Mini_Classic-Cores_02-28-21\_km_Xtras\KMFDManic_Info_ReadMe!(1).txt

C:\SysDown\KMFDManic-Mini_Classic-Cores_02-28-21\_km_Xtras\BIOS\BIOS_ReadMe!(1).txt

cheers

**Comment by KMFDManic** [comment]
Those files should have been deleted, but may show traces left behind.  I will take a look at the clutter:)

**Comment by AntiFly** [comment]
you noted.

**Comment by KMFDManic** [comment]
@AntiFly I upgraded Google Drive to 2 TB:)  There will be a private section of that that I will give you and a few others access to, once I get things settled!  Thanks, as always, for your continued support.  Told you I would do what I could, once you asked about Amiga being better!  Be sure to notate ANYTHING else that you think I should still look into, mate:)

**Comment by AntiFly** [comment]
@KMFDManic 
It is just amazing that you still are going to these stuff.
Very welcome mate ;)

**Comment by KMFDManic** [comment]
@AntiFly Many have moved back to reality, or gotten Nintendo Switches.  Nice to see you keep up on these things, too!  And, despite Flame Zapper having slowdown, it was a fun play!  I am trying to juggle my hectic schedule so I can finalize some of the recent showcased Cores.  The Amiga fix-ups I just need to make compatible for SNESC, which I will probably get to by next week!  Main thing is, AGA games are ALL nicely playable, now:)  For more specifics, since I am still working on this, feel free to shoot me an email:)

**Comment by AntiFly** [comment]
@KMFDManic 
yah true. The SNESC is something special. Its kind of a great memory and the system is so powerfull with your additions that its worth to keep an eye on this (at least for me). dont rush it , its more important that this is not breaking any other core , so reliability is still on a great level.

so what came to my mind as I read your text with AGA. there so many switches you cover with the command line at the moment, does it maybe make sense to have this with an addition to the hakchi environment. you know. checkbox AGA , checkbox CORE XY etc.. (which are just visible and available for a specific core, that it will not overload the GUI).
But well, its late with the minis, so probably these guys wont implement it ^^

cheers

**Comment by KMFDManic** [comment]
Amiga is gonna be a bit different than you are used to with the upcoming Update.  There will be 2 Cores.  One of them will work whether or not you have BIOS installed!  You will just get a few second message saying they are missing, if they are!  Most games will run fine with that Core.  But, if you wanna run the AGA, advanced graphics architecture games, which ALL run slower, in general...you will want to run those with the other Core I post.  I will have notes regarding this.  A1200, AGA are the same thing.  And, in fact, you can take a game like Aladdin, and rename it to Aladdin_AGA.hdf and it would Automatically know that it is meant to run with the AGA destination on the Non-Bios Core.  But, you can just run it, AS IS, on the other Core, and it will be fine, as well:)  Both Cores will have their pluses and minuses.  But, you can now run 99.5 percent of any Amiga Library you attempt to run, in contrast to being a bit more limited in older Releases.

I may add a few more changes to either/or Core.  Just depends on how much more I want to get involved in it before finalizing Both Cores for this upcoming Release.  I obviously have 20+ other Cores to finalize, too!  Fceumm will be much better for homebrew games, including Halloween 85 finally working, which is a great little gem to check out:)
