### ISSUE TITLE
Paper Mario

### ISSUE THREAD

**Issue by Grumstrum** [KMFDManic/NESC-SNESC-Modifications#22]
Paper Mario seems to crash after Mario wakes up from falling off the castle in the beginning of the game.

**Comment by KMFDManic** [comment]
The only suggestion I can make is you use a No-Intro Version of Paper Mario, and try it in Mupen64Plus and/or Glupen, to see which works best for you.  N64 is very unreliable on the NES/SNES Classic Systems.  Games tend to crash after 20 Minute Play Periods.  You should shut down periodically to clear the cache.  It truly is what it is.  But, many games do play pretty well!  Be sure to grab today's Core Update, which helps address some Save Issues!
