### ISSUE TITLE
puae-xtreme-amped not working?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#220]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.9.2_____
  * RetroArch used (filename): 198 Ozone
  * hmod(s) used by the game you are having problems with (filenames): puae-xtreme-amped
  
### Step 2: Describe the problem:
 My puae and puae-xtreme are working fine. However, when I try to use puae-xtreme-amped, I get the message "Please insert Volume DH1". 

The message comes up for anything I try to load using this command line, including games that worked ok with the non-amped command lines. Agony is one example of this. Please advise how to resolve this?

I also hear the CHD files should work with puae-xtreme-amped. Am I just supposed to add the chd directly to retroarch and use puae-xtreme-amped to launch it? If so, which version of CHDman is best for CD32/CDTV games please?
  * _____
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by AntiFly** [comment]
Hey, no I do not have reddit therefore I post nothing there ;)
