### ISSUE TITLE
Swap file create failed xtreme ram failing

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#221]
### Step 1: Describe your setup:

  * hakchi2 CE version: latest
  * RetroArch used (filename): latest
  * hmod(s) used by the game you are having problems with (filenames): xreme ram usb
  
### Step 2: Describe the problem:
  
Problem:
  * while starting Swap file create failed xtreme ram (and some borg whatsoever notice)

Sidenote:
  * /Snes16 string is gone (So, there is no longer an SNES9x 2016 or 2016 Bright or 2018) but not described in what it is phased to ? 2010/2005/9x what is the equivalent to 16? 9x or 2010 whats the difference ?

OUTDATED - 
km_command_lines_ReadMe!.txt is dated to February 2021 and does not contain the latest changes about the command lines ;) ???

cheers

**Comment by KMFDManic** [comment]
@AntiFly Thanks for the heads up on the improper command on Atmosfear:)  I work today, then will try to clean some of these conflicts up over the weekend, and drop google drive link/s for ya:)

**Comment by KMFDManic** [comment]
@AntiFly Updated Release, let me know if anything is amiss.  Thanks again for your dedication in helping pinpoint a few bugs!  And, hope the best for you in all you do!
