### ISSUE TITLE
Extend readme with project description.

### ISSUE THREAD

**Issue by uli42** [KMFDManic/NESC-SNESC-Modifications#222]
I suggest to start the readme with one or two sentences about what this whole project is about. The readme is only readable/of use if you already know what it is talking about. Nothing for newbies...

**Comment by KMFDManic** [comment]
The very top of the latest Release, I adjusted to clarify exactly that my Github is meant primarily for those with Mini Classics, such as NES, SNES, MD, PSC.  Thank you for your feedback:)
