### ISSUE TITLE
Swap file create failed xtreme ram failing (#221)

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#223]
Step 1: Describe your setup:

    hakchi2 CE version: latest
    RetroArch used (filename): latest
    hmod(s) used by the game you are having problems with (filenames): xreme ram usb

Step 2: Describe the problem:

Problem:

    With the current update still ... while starting Swap file i see the mb that are "loaded" and then create failed xtreme ram (and some borg whatsoever notice)
the swap file itself has been created but the error still pops up every bootup.
I would appreciate if it could be disbled at all displaying there anything except the loading screen.

cheers

**Comment by KMFDManic** [comment]
All good now, thanks for the testing mate:)
