### ISSUE TITLE
Not able to select cores in RA on PSClassic

### ISSUE THREAD

**Issue by parkesto** [KMFDManic/NESC-SNESC-Modifications#224]
Just grabbed the latest cores and installed via the exe on usb.

All the cores are there for me to "load core" but any time I pick a rom for any console none of the cores actually show up? So I can load it initially, but then when I go to play SNES/NES it wants me to pick another core?

The PS1 cores work fine when I load it and choose External and boot up a game, but all other consoles don't seem to work?

**Comment by KMFDManic** [comment]
The Cores that are selectable for any given game will ONLY display if the games are valid.  If you are using fake games, or bad games, they simply will not work as being selected.  IE: If you opened Fceumm Core, and then went to load content, tried to load a game, such as Blaster Master.nes, it would allow you to select the Fceumm as the Core.  If you didn't properly install the injector, or the games are bad or fake, it would not.  The setup I post strictly works after first installing AutoBleem or RetroBoot.  It isn't intended for any other modifications.

**Comment by parkesto** [comment]
I am using Project Eris on the PSC and literally any core I drop in aside from yours work perfectly fine, any of the stock libretros etc or other forks are able to be selected without issue, only your cores do not show up despite running the injector and all the cores being listed in the directory. 

I can load your cores themselves just fine (via Load core), but any .nes/.smc/.bin/.cue etc does not allow your cores to be selected, despite them being properly installed etc.

**Comment by KMFDManic** [comment]
@parkesto Since the set-up I post is meant strictly for usage with AutoBleem, it is best you stick to what you are currently running with Eris, unless you decide to try or switch to AutoBleem.  Then, what I post will work effortlessly there.
