### ISSUE TITLE
Game Music EMU Core not functioning

### ISSUE THREAD

**Issue by RavingDragon22** [KMFDManic/NESC-SNESC-Modifications#225]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.9.3
  * RetroArch used (filename): 1.9110 Xtreme SC!
  * hmod(s) used by the game you are having problems with (filenames): _____
  
### Step 2: Describe the problem:
  
  *I have tried multiple "supported" file types using the  Game Music Emu core and none of the work. Specifically NSF and GBS files. I tired multiple different NSF/GBS files, and tested them on PC emulators to make sure they were functioning files. They are. I even tried opening a game in retroarch, closing the game and loading the NSF from the menu to which I received a fail to load message on the Games Music core.
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)

**Comment by KMFDManic** [comment]
@RavingDragon22 Since I helped you on Reddit, and this is going into the Next Release, I am gonna close this for now:)  Thanks again for the feedback!
