### ISSUE TITLE
Playstation classic turbo boost

### ISSUE THREAD

**Issue by Jmcdonald9700** [KMFDManic/NESC-SNESC-Modifications#226]
### Step 1: Describe your setup:

  * hakchi2 CE version: _____
  * RetroArch used (filename): _____
  * hmod(s) used by the game you are having problems with (filenames): _____
  
### Step 2: Describe the problem:
  
  * _____
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Rockin' The Classics Discord](https://discord.gg/bX9PqrC)
Hey I installed autobleem Xtreme and core injector whenever I activate turbo boost I get taken to the Rubik's cube. I can't get Sega Saturn to run at 60 fps like in your videos. What should I do? Thank you for your time

**Comment by KMFDManic** [comment]
@Jmcdonald9700 You opened an issue without any information, whatsoever:)

**Comment by Jmcdonald9700** [comment]
What kind of info do you need? I just want the games to run at 60 and am not sure what to do
