### ISSUE TITLE
Controllers not working (only) with RetroArch 1.9.10 Ozone

### ISSUE THREAD

**Issue by EricRueil** [KMFDManic/NESC-SNESC-Modifications#227]
### Step 1: Describe your setup:

  * hakchi2 CE version: v3.9.3
  * RetroArch used (filename): RetroArch 1.9.10 Ozone
  * hmod(s) used by the game you are having problems with (filenames): KMFD RetroArch 1.9.10 Ozone
  
### Step 2: Describe the problem:
  
  * Everything has always worked well with my SNES Classic Mini that I have been using with KMFD Retroarch for several years.
  * Yesterday I updated Hakchi successfully, and saw the mods updated list provided with this KMDF repo: there are only 2 versions of Retroarch: "1.9.10 Ozone" and "1.8.4 Extreme SC!".
  * But when I install "1.9.10 Ozone" and then launch Retroarch from the SNES main menu, RetroArch opens well, but none of the 2 controllers work. I cannot move through the items in the menu. The only thing that works is pressing "Down+Select" to go back to the SNES menu.
  * With "1.8.4 Extreme SC!" everything works fine, but I don't like much its GUI (fonts, colors and background)
  * I have tried several times to uninstall all Retroarch and cores mods and then reinstall them, but get always the same issue.

Hopefully, you can help?
Best regards,
Eric

**Comment by KMFDManic** [comment]
Unfortunately, the only proper way to update to 1.9.10, Mini Wise, is to do an "uninstall" kernel, then "install/repair".  This occurs if you've used any other RetroArchs previous to the newest one, in the way of "old remnants".  1.8.4 is still the best and most reliable one for most usage.  To use the newest one, you will need to do the uninstall kernel, then should be fine.

**Comment by EricRueil** [comment]
Hey,
Ok, I missed this information, and did "install/repair" only. I will keep 1.8.4 for now as you mention it is more reliable, and I found how to de-customize the bakcground ;-)
Thank you very much!
