### ISSUE TITLE
Issue with in game saves Ocarina of Time

### ISSUE THREAD

**Issue by Acc94** [KMFDManic/NESC-SNESC-Modifications#23]
Hi again!

I've tried the updated Retroarch and I'm still sufering of saving issues once I shutdown the console. If I close Retroarch and start OoT again, the save is still there. But once y restart the console, it is gone.

May I change any setting in Retroarch? (as Player 1 pak or something in the saving part?)
Inside the game, when I open retroarch menu this is what appears at bottom:

1.6.7 - GlupeN64 GLES2 2.5 7b7cb25. Is that the right version isnt it?

Thanks!

**Comment by Acc94** [comment]
Okey, after changing a couple of settings in the saving part, it seems it's working! Thank you very much!

**Comment by KMFDManic** [comment]
Youre very welcome:)

**Comment by gingerbeardman** [comment]
@Acc94 what did you change?
