### ISSUE TITLE
Windjammers Question

### ISSUE THREAD

**Issue by Grumstrum** [KMFDManic/NESC-SNESC-Modifications#24]
Fantastic work on all the updates! I was wondering if its possible to save soft dip settings? When I change the windjammer's time limit it resets after I turn off my snes mini.

**Comment by Grumstrum** [comment]
Actually I seem to have issues running windjammers in general now. I was wondering if you could tell me which modules I have to have installed and which neogeo bios to use

**Comment by KMFDManic** [comment]
Use MAME 2003, from main folder, with the Bios designated for MAME 2003.  If you are to run WindJammers on FBA 2012 or FBA 2012 NEOGEO, or FBA 2016, you'd need either of the other Bios:)  Of course, you need the proper command line and rom set.  But, it works pretty damned nicely on MAME 2003, which I showcase in THIS video..

https://www.youtube.com/watch?v=2kfYH234l6E

**Comment by Grumstrum** [comment]
If I want it to work with FBA2012 do I need to enable just the fbalpha2012.hmod then put a neogeo.zip in the game folder? Or do I also need to enable fbalpha2012_neogeo.hmod. Not that experience with this and a bit confused.

**Comment by KMFDManic** [comment]
You can use the Bios NeoGeo Mod for FBA 2012 or Unibios.  But, if you use either of these Mods, you will not be able to run NeoGeo via MAME 2003.  So, pick MAME 2003, or FBA 2012, 2016, MAME 2010, MAME 2014, which all work with the 2 Non-MAME 2003 Bios.  Alternatively, you can run NeoGeo in MAME 2003, as well as any of the other Cores, by copying the proper NeoGeo Bios into the directory of any given NeoGeo Game.  So, you definitely have options:)

**Comment by Grumstrum** [comment]
Thanks man! That cleared it up for me!

**Comment by KMFDManic** [comment]
Uni-Bios with FBA 2012 NEOGEO Variant...You may need to enable via RetroArch options.
