### ISSUE TITLE
N64 games don't load

### ISSUE THREAD

**Issue by brothan323** [KMFDManic/NESC-SNESC-Modifications#25]
Hello. Both of the 64 cores do not work, glupen and mupen. They do not load vanilla 64 games or patched ones.

**Comment by KMFDManic** [comment]
Both of the Cores work just fine.  You need to have either Glupen or Mupen64Plus Installed, as well as RetroArch.  Once you add an N64 Game via Hakchi, which I would keep to 1st party ones, such as F-Zero, Wave Race, Legend of Zelda - Ocarina of Time, etc...and have proper command line, /bin/n64  You should be fine.  Sometimes, you need to Flash Custom Kernel for games to take.  You may potentially be loading incorrect Rom Sets, or Games that are not supported, which would cause non-load issue.  But, hundreds have been using these 2 N64 Cores, from my set without issues other than Save Ability, which I addressed with my most recent Update:)  Let me know how things go.

**Comment by brothan323** [comment]
Can you run patched 64 games on the snes mini?

**Comment by KMFDManic** [comment]
@brothan323, this you would only know by "testing" them.  But, generally, hacks, translations, patched games, can be pretty hit or miss, depending on which Core you use.

**Comment by brothan323** [comment]
Could you try booting Last impact or star road and tell me if it loads for
you? I just want to know if I'm doing something wrong, or have a bad rom.

**Comment by KMFDManic** [comment]
@brothan323 I would try running your Hacks via Glupen &/or Mupen, to see if either load them.  But, for the most part, a lot of N64 Hacks, do not work.

**Comment by KMFDManic** [comment]
Closing this issue, as it is related to potentially non-compatible Roms, not the Cores having an inability to work:)  But, I can follow-up with you, if need be:)
