### ISSUE TITLE
5200/800 core

### ISSUE THREAD

**Issue by jtgillia** [KMFDManic/NESC-SNESC-Modifications#27]
I’ve tried getting 5200 games to run on NES classic, but not having much luck.  Trying to figure out what went wrong.  I’m using 2.21e hakchi, the latest retroarch and your 5200/800 core and 5200 bios are all installed.  When I go to load my 5200 games, I get the 800 computer screen that says “Atari Computer Memo Pad”.  Could it be something I did incorrectly in my script?  Thanks for your help and very much a novice to this stuff!

**Comment by gingerbeardman** [comment]
Charge core settings to Atari 800. 

See this video: https://youtu.be/dlkx_aRxR4U

**Comment by jtgillia** [comment]
It appears I can’t change core settings, and also can’t access retroarch within game.  Perhaps I need clover for NES app too?  Or there’s some config file i’m missing?

**Comment by KMFDManic** [comment]
@jtgillia Grab latest Core Set Update from Releases, Uninstall (Always uninstall before installing new variants) your Current Cores, then install RetroArch HMOD, Atari800 HMOD, no need to install Bios.  Then, select+start should pull up RetroArch options, and allow you to go to Options and select the 5200 System.  Command line for 5200 Games should be 

/bin/a52

I

**Comment by jtgillia** [comment]
Thanks for your help.  I feel sure i’ll get it fixed tonight.

**Comment by jtgillia** [comment]
Got everything working perfectly now except for two games!  One is 5200 Pengo, runs fine but the controls are screwed up.  Could be a bad rom.  Other game is Salmon Run which was a cassette game for Atari 800 computer.  Not sure if cassette games will load in retroarch or not.

**Comment by jtgillia** [comment]
This may sound really entitled or selfish....but do you think we may eventually get a smarter core that can switch between 800 and 5200 games without the user having to change settings in retroarch?

**Comment by KMFDManic** [comment]
@jtgillia This would be an auto-detect, which could get mixed results.  I have never been a fan of auto-detect, as it can limit your ability to do certain things.  It really isn't that much of an inconvenience to switch between 5200/800.  It literally takes 2 seconds, hehe.  As far as Pengo, thanks for the feedback on that.  I will try the game, personally, and see how controls fare for me.  Cassette Games, go into RetroArch Options, and enable Boot From Cassette:)  It should work:)

**Comment by gingerbeardman** [comment]
If the core is run with a52 or a800, or whatever, surely it would be possible to write a line in the config to set that option in the core settings? or not?
