### ISSUE TITLE
Nothing is working for me on the latest _km_mame2003_11_7_17

### ISSUE THREAD

**Issue by creamstick** [KMFDManic/NESC-SNESC-Modifications#28]
I uninstalled _km_mame2003_11_5_17 and installed the latest _km_mame2003_11_7_17 and now no Mame2003 games run at all. I uninstalled _km_mame2003_11_7_17 and reinstalled it - nothing - everything just exits back to the SNES Mini. No matter whether it's CPS2, NEO GEO, or regular games, nothing works.

I uninstalled _km_mame2003_11_7_17 and reinstalled _km_mame2003_11_5_17 and everything that worked before works. Uninstalled _km_mame2003_11_5_17 and reinstalled _km_mame2003_11_7_17 and nothing works again.

I even tried uninstalling everything, and going back to stock, then reflashing and still nothing.

**Comment by KMFDManic** [comment]
I fixed it:)  I will be posting an updated, and better version of it, in my very next release:)  I am aware of this, already:)  But, thank you!  You may also see I credited you in the readme for FBA 2012 NEO GEO:)  MK & NBA Jam, etc, have nice sound now in MAME 2003!  Check it out in my very next update, which I will try to post before I go to sleep today!

**Comment by creamstick** [comment]
The three greatest words in the English language - I fixed it! :D Awesome!!
