### ISSUE TITLE
[core feature request] Possibility to disable commandline options

### ISSUE THREAD

**Issue by bankaiprimera** [KMFDManic/NESC-SNESC-Modifications#30]
It would be great to be able to **disable** certain commandline options when using your custom RA cores. For example, I want to Picodrive _only_ for 32x emulation. Now, when I use the "md" commandline it launches the Picodrive core for genesis & master system games - not Genesis plus GX (which I also installed). There doesn't seem to be a way to prefer one core over the other, so disabling certain commandline options would solve this. 

I have managed to work around the issue, by using the "sg" commandline for all genesis and SMS games; this commandline is only used by Genesis plus GX. It doesn't seem to matter at all that it isn't actually launching a SG-1000 game :)

**Comment by KMFDManic** [comment]
Ironically, the requests people previously asked for went the opposite direction, asking for more command lines.  But, I will optimally take into account your request for my next update.  And, when I am caught up on other things, may try a special compile of MAME 2000 and see if it works.

**Comment by KMFDManic** [comment]
In Extras & Dependencies Folder:)
