### ISSUE TITLE
Original 30 NES games

### ISSUE THREAD

**Issue by jtgillia** [KMFDManic/NESC-SNESC-Modifications#31]
After adding your mods and working out the Atari 800 core, I noticed that the stock games on the NES classic (original 30) are broken.  They won’t launch and the boxart for them is gone.  Any ideas on fixing other than downloading them separately and adding them in myself?

**Comment by KMFDManic** [comment]
You have too many games per folder.  This has absolutely nothing to do with RetroArch and Core installs, other than the correlation between size that is taken up.  Generally, no more than 100 per folder for SNESC.  And, no more than 60 for SNESC.  Missing folder art, if it existed previously...would point to flashing one too many games in a single directory.

**Comment by gingerbeardman** [comment]
Typo above, first one should be NESC

**Comment by KMFDManic** [comment]
@gingerbeardman Always nice to know I have backup:)  Thanks, my friend:)

**Comment by jtgillia** [comment]
The most games I have in a single folder is 42.

**Comment by KMFDManic** [comment]
@jtgillia To better troubleshoot your current predicament, let me ask you a few questions.

1.  Which Hakchi2 version are you using?
2.  How many total MB in Games are you flashing?
3.  You using an NESC or SNESC, just to confirm, for sure?
4.  The directory that the 30 original NES Games are in, include other Games, as well?
5.  Have you flashed Custom Kernel?

Typically, missing artwork would be from too many games, incorrect command line in desktop file for said art, flashing too many MB in Games, as primary reasons.  Let me know, then I can recommend how you can proceed.

**Comment by jtgillia** [comment]
I flashed the custom kernel again and it took care of it.  Sorry for wasting your time.  Keep up the great work!

**Comment by KMFDManic** [comment]
You didn't waste my time @jtgillia You are fine:)

**Comment by jtgillia** [comment]
Unrelated question- I tried out the Virtual Jaguar emulator and while the games barely run they are so slow they are unplayable.  Is there anything I need to do to improve performance, or is it just that Jaguar emulation is not ready for primetime?

**Comment by gingerbeardman** [comment]
the device is not powerful enough. the core is just there as a curiosity.

it's doubtful there will be any more changes to the emulator core by its original creator at this point.

**Comment by KMFDManic** [comment]
@jtgillia, I did a video on this awhile back...

https://youtu.be/rS5O4jkZsg0

@gingerbeardman, yep...I should be able to get a video on USB-HOST posted later today.

**Comment by jtgillia** [comment]
Watched the video, agree that Trevor McFur was a total gem.
