### ISSUE TITLE
Not an Issue, persay...But, more or less, a tremendous thanks to those of you Following my Github:)

### ISSUE THREAD

**Issue by KMFDManic** [KMFDManic/NESC-SNESC-Modifications#33]
I truly and graciously thank you all for your constant and almost daily feedback and input and testing things independently, as well as the suggestions!  This all goes a long way with saving me time and bettering the Core Set for us all!  I have many, many things planned in my Agenda!  With the advent of USB-HOST Expandable Storage Modification, courtesy of the one and only madmonkey, himself!...Our possibilities are near endless, now!  Expect many more things related to this truly amazing modification!  I communicate regularly with many great people in the Emulation Community.  And, we are all Cogs in this Great Machine!  We have achieved a lot and will continue to succeed more, as we go on!  I will post a video on the USB-HOST Modification, just to give a proper introduction to its setup and what to expect from it, as well as its overall potential!  Thanks Guys & Gals!!!

For today's Update, expect a few fixes to the USB-HOST, which will be explained in the Releases Section:)  Video will be posted, related to it, by Thursday!  Be sure to check for the update later today:)

**Comment by Grumstrum** [comment]
Thanks for all your work! Do you think the USB modification will get to a point where it's user friendly to the average user? Wondering if I should wait to get it a try!

**Comment by KMFDManic** [comment]
I will ease your worries on using it, with my video, no worries:)  Expect the video to drop tomorrow or Thurs.

**Comment by gingerbeardman** [comment]
Thanks! Even though I am still without a SNESC (Nintendo dragging their heels with the repair) I still follow the scene. Though this is the first I am hearing about USB-HOST Expandable Storage Modification?! 

Onwards!

**Comment by KMFDManic** [comment]
@gingerbeardman @Grumstrum Here ya go:)

SNES Classic - USB-HOST Expandable Storage Modification!!!

https://www.youtube.com/watch?v=OxAjQ_7QHmg

**Comment by Grumstrum** [comment]
Do you think this will ever be supported using the Hakchi2 interface? (Like adding the games onto the USB using it)

**Comment by gingerbeardman** [comment]
Just got my SNESC back from Nintendo and have ordered an OTG cable

**Comment by KMFDManic** [comment]
@Grumstrum Look at the picture in my Advanced Users Folder.  One like that will work.

**Comment by KMFDManic** [comment]
MSU-1 Tutorial & Test:)

https://www.youtube.com/watch?v=ZOVwPWEOiUo

**Comment by Grumstrum** [comment]
Looking forward to testing out TurboGrafx games! Like Rondo Of Blood!

**Comment by Astromatik** [comment]
a lot of thank kfmd for all

**Comment by KMFDManic** [comment]
@Grumstrum Rondo runs quite nicely:)

@Astromatik Thanks for the appreciation:)

@gingerbeardman Hopefully, my latest Update and Videos make USB-HOST more user-friendly for you to take on:)
