### ISSUE TITLE
[LINUX]tgbdual-libretro.so not linked to libstdc++

### ISSUE THREAD

**Issue by nono2lozere** [KMFDManic/NESC-SNESC-Modifications#34]
Hello,

I have found this issue with tgbdual-libretro: https://github.com/libretro/tgbdual-libretro/issues/11 and i would like to know if you have fixed it in your build. If not the core won't load and became useless.

Thanks

**Comment by KMFDManic** [comment]
TGBDual works fine in my build.  I rolled it back very recently, in fact, to compensate for this change.  People love their Dual-Link Games:)

**Comment by nono2lozere** [comment]
Good to know, thanks for your hard work!

**Comment by KMFDManic** [comment]
@nono2lozere Applied the fix, and am now updated to current.
