### ISSUE TITLE
snes msu1

### ISSUE THREAD

**Issue by Astromatik** [KMFDManic/NESC-SNESC-Modifications#35]
hello;
do you think its possible with your usb host and your snes 9x mod, we can play msu1 support?

**Comment by KMFDManic** [comment]
Yep:)  This shows me me running MSU-1. I will do a tutorial on how to set it up, sometime in the very near future.

https://youtu.be/OxAjQ_7QHmg

**Comment by Astromatik** [comment]
wow my dream come true lol your in logic sunrise site, many guys got an otg cable where you are one of modder realese it.
I m not a electronic professional and i want show it for made me one.
I just search how can i run this rare chipset underground: The snes CD

**Comment by KMFDManic** [comment]
@Astromatik MSU-1 is my current project.  So, you will hear more from me on this, over the next few days.  I will do a video tutorial.

**Comment by Astromatik** [comment]
very great so cool, you are an real killer man ^^.

**Comment by KMFDManic** [comment]
@Astromatik https://www.youtube.com/watch?v=ZOVwPWEOiUo
