### ISSUE TITLE
Retroarch not mapping all controls on non-SNES controllers

### ISSUE THREAD

**Issue by capran** [KMFDManic/NESC-SNESC-Modifications#36]
I'm hoping you might be able to help with an issue I've discovered. I can't get all the controls mapped for the Nintendo 64 games I've installed.

I got a Euro SNESC a month ago, and 8bitdo Retro Receivers and N30 Pro controllers last week. They work fine for most games on the SNESC, but I discovered that I can't map the right stick at all, the 4 shoulder buttons only act as L & R, not L1, L2, R1, R2, and the DPad and left stick are the same.
I emailed their support (took 2 emails to get a reply), and this is all they said:
    技术支持 to Justin

    Hello there!

    The problem is on Retroarch. We suggest you could wait for the new verison of it.

    Many thanks!
I'm guessing they mean that Retroarch needs a driver or something.

I tried looking at the retroarch.cfg file and comparing it to the one on my Raspberry Pi3 with Recalbox, but the files are very different.

I did find on Recalbox a whole slew of .cfg files for controllers: /recalbox/share/system/configs/retroarch/inputs/udev

But I couldn't find a similar folder on the SNES when using Hakchi and WinSCP. I tried copying all those files to /etc/libretro/joypad_autoconf, but that didn't make any difference.

I also went to /etc/libretro/.config/retroarch and creating an input folder there with the .cfgs. But no difference again.

I just don't know enough about how the Retroarch config files work, and how Retroarch is set up on the Classic to have a clue what to do now.

I'm hoping you might be able help. Thanks!

**Comment by KMFDManic** [comment]
Download my Core Set.  In extras and dependencies folder is firmware that has helped with other 8bitdo controllers on the NESC/SNESC.  I included it for many releases due to so many having the controllers.

**Comment by capran** [comment]
Thanks for replying! I have tried the beta 1.08 firmware, but I went ahead and flashed both my retroreceivers with it again, and then loaded up Super Mario 64. I went into the Retroarch settings screen, then Settings, Input, User 1 binds. The controller is usually recognized as "Unknown", but I can select "Controller" instead. I turn off the Analog-to-Digital type. I hit Bind All, and go through all the controls. 
But it still does not see the difference between the DPad and the Left Stick, or the difference between L1 and L2, R1 and R2,  and the Right Stick (and L3/R3) is not recognized at all.

For good measure, I tried 8bitdo's tool to sync a PS3 Dual Shock controller, and I get the same results. http://support.8bitdo.com/#tab3

Attached are the Retroarch config and remap files from my Classic.

I also included under joypad_autoconf all the controller configs I found on recalbox.

[libretro.zip](https://github.com/KMFDManic/NESC-SNESC-Modifications/files/1485671/libretro.zip)

**Comment by KMFDManic** [comment]
I will include clovercon in my next Update.  This helps with 3rd party controllers.

**Comment by KMFDManic** [comment]
@capran clovercon is in today's Update, within Extras & Dependencies Folder:)  Hope it helps you out!  Otherwise, we may need to set up a manual configuration method, to get things going.  Or, possibly, another alternative.  Keep me posted!

**Comment by capran** [comment]
Well I still can't get it to recognize the extra controls. Maybe I did something wrong?

1. I downloaded KMFDManic-NESC-SNESC-Cores.11-20-17.7z.
2. I made a new user_mods folder in my hakchi2 folder and unzipped it there.
3. I ran hakchi2, and went to Modules, Uninstall Extra Modules.
4. I selected everything and hit OK and let it process.
5. I went back to Modules, Install extra modules. Selected the modules I wanted (I had to drag clovercon in there first for it to show up), clovercon, retroarch, glupen64 and a few other cores.
6. I let that process
7. Synchronized games for good measure.
8. Switched to the SNESC, and loaded up Super Mario 64. 
9. Brought up Retroarch menu with START+SELECT. Went to Settings, Input, User 1 binds.
10. At first the type was Retroarch w/ Analog, but hitting A on that changes to Controller or nothing.
11. I then tried to bind all, but I still cannot bind any extra controls (outside of the SNES controller's).

**Comment by ajmi982** [comment]
Dualshock 4, using the very latest clovercon from yesterday. L3 and R3 cant map. Right analog stick, cant map.

**Comment by ajmi982** [comment]
d pad and left analog i can map

**Comment by KMFDManic** [comment]
@ajmi982 @capran Use the Clovercon I just updated in Today's Update:)  See if that helps!  Remove the previous one that I posted!  Try this updated one:)

**Comment by capran** [comment]
Sorry, still no joy :(

I even reflashed the original kernel and restored everything to factory, then reinstalled hakchi and made sure the clovercon.hmod was installed.

I'm thinking we'll just have to wait for 8bitdo to release newer firmware. The 1.08beta didn't help.

Thanks for trying though!

**Comment by KMFDManic** [comment]
clovercon generally helps with generic wired controllers.  Wireless controllers might require Firmware Revisions to adjust to the Mini NES/SNES Environment.  I originally thought about getting an NES8bitdo.  But, I opted for an extension cable and a Wii Classic Controller instead!  I can run ANY friggin' Core with this set-up:)  And, with USB-HOST, I can now use keyboard and mouse, as well:)  What you may want to do is use 8bitdo for the Cores that work best with it, then something like a Wii Classic Controller, which works flawlessly with N64:)  Well, that is almost an overstatement of sorts, because N64 Emulation kinda sucks for Mini NES/SNES anyways:)  But, many games do run well enough!

**Comment by KMFDManic** [comment]
In checking further, this issue is entirely related to the Firmware for Wireless Controllers.  If you were using Wired Controllers, Clovercon would generally fix this, without much trouble.  Despite them saying it is a RetroArch thing, they are the ones that do the firmware:)  So, it is truly in their hands to listen to feedback from Customers, and get things going:)  I would suggest a Wii Classic Controller as an alternative for the stubborn Cores, with 8bitdo.  Be persistent and contact 8bitdo again, or find Forums to post on.  I don't see why they can't adjust the firmware to handle the controller!

**Comment by KMFDManic** [comment]
@capran @ajmi982 for the hell of it, try these steps:)  This worked for me with several wired controllers, without issue.  Hopefully, it does the trick for you with the wireless ones!

1.  select+start, obviously, to pull up RetroArch Options
2.  Settings
3.  Input
4.  Input User 1 OR 2 Binds
5.  Select the button you want to change, then tap A, then tap the button you want it changed to!
6.  Keep in mind, if your B button is BACK in the RetroArch Options, and you reconfigure it to Y, Y will then become your back button!
7.  Avoid changing select+start, as then you will end up breaking your ability to use RetroArch Options!  And, you will need to uninstall RetroArch, then reinstall it!
8.  If you screw up, simply choose User 1 OR 2 Bind Default ALL!  
9.  Just back out to quick settings, then resume the game, to test things:)
10.  If satisifed with the mapping, leave it alone:)  It should save.  I powered off the system and back on and it worked absolutely perfectly.  
11.  Use Bind Default ALL when you want to revert.  And, do not forget, if you truly screw things up...Just uninstall RetroArch/Reinstall RetroArch:)

**Comment by capran** [comment]
FYI, that is the procedure I've been following. I went ahead and reflashed the SNESC and rebound, but there's no change. Unfortunately I don't have a Wii Classic Controller to test.

Will the USB update allow USB controllers?

**Comment by KMFDManic** [comment]
Yes, USB-HOST should work with USB Controllers.  I am using the 3 usb slots for keyboard, mouse, and flash drive currently.  But, controllers should be fine.

**Comment by ajmi982** [comment]
Hmm. Wonder if I use my own USB Bluetooth adapter with USB host mode. Issue is I would need a new OBT cable because I only have one USB slot. Then I use my own Bluetooth receiver with my Dualshock 4. Hmm but how would it pair?
