### ISSUE TITLE
Sega CD Games Failed To Load

### ISSUE THREAD

**Issue by isodummy** [KMFDManic/NESC-SNESC-Modifications#39]
Hi,

I use the latest hmod set (11_22_17) with USB-HOST and successfully run NES, SNES, Mega Drive, PC Engine & Neo Geo games on USB. When I try to run the Sega CD games, it just show the black screen (BIOS screen not pop).

HMOD installed (Sega CD related):
genesis_plus_gx_10_28_17
retroarch_11_19_17

BIOS installed:
installed by hmod template \segacd.hmod\etc\libretro\system with bios_CD_E.bin, bios_CD_J.bin, bios_CD_U.bin

ROM:
covert to .chd with chdman.exe with correct .cue and .bin files (without rip) and drag the .chd to kakchi2

Hakchi2 game command line:
/bin/segacd /usr/share/games/CLV-Z-GOQGD/Sonic_cd.chd.7z

I wondering it is related to the BIOS not installed correctly, and I noticed that the bios hmod included in old released pack, _km_bios_gen_plus_gx_pico_scd_req.homd, has been removed.

I'm hoping you might be able help. Many Thanks

**Comment by KMFDManic** [comment]
In hakchi2, right click and uncompress the game, so that it is /bin/segacd /usr/share/games/CLV-Z-GOQGD/Sonic_cd.chd

You sir, are running a game that is doubly compressed:)

**Comment by isodummy** [comment]
Oh, after uncompress it could run, also PCE CD games.
Million Thanks !!!
