### ISSUE TITLE
Can you check the Yabuse core is working from the latest pack? - Ignore, I'm an idiot.

### ISSUE THREAD

**Issue by creamstick** [KMFDManic/NESC-SNESC-Modifications#40]
Got my USB all set up and running beautifully, Mame2003, FBA2016, SNES, Mega Drive, NEOGEO, Sega CD, Playstation all working - but for some reason, I cannot get anything to run with Yabuse.

All of my games are bin/cue with a single .bin file, .cue is loaded into Hakchi2. I have tried putting the BIOS file into the same folder as the game, and as a custom .hmod but nothing happens when I try to load the game on the SNES Mini. It just goes to black for a second, then back to the menu.

While I'm here, any tips on which Playstation games work well with the enhanced resolution option?

Cheers!

**Comment by creamstick** [comment]
Fixed it. I had typed Yabuse instead of Yabause. Just realised this after two days of testing.

**Comment by KMFDManic** [comment]
@creamstick Everyone's favorite words, "fixed it":)  As far as enhanced resolution, you will generally have decreased performance when using CPU intensive options.  This will be something you will have to personally make a decision on, whether using it or not.  I would suggest testing it out with a game like Ridge Racer, where you can easily see the difference with it on or off.  I generally just use Shaders for the Cores:)
