### ISSUE TITLE
Hq2x with snesmini (FOR MSU1)

### ISSUE THREAD

**Issue by Astromatik** [KMFDManic/NESC-SNESC-Modifications#41]

**Comment by Astromatik** [comment]
Hello kfmd,
Do You think its possible to make hq2x shader with our snes mini for retroarch ?
Snes Cd make great video.
Thx and Thx one more time for msu1^^

**Comment by KMFDManic** [comment]
Already did a shader set.  It is in Extras & Dependencies Folder...RetroArch Extreme Filters. I use them in these two videos.  Note, some shaders are CPU intensive and will not fare as well.

https://youtu.be/VYyuUEr8peg

https://youtu.be/9CsQ96wcUOI

**Comment by Astromatik** [comment]
thank you very very much for ALL^^
