### ISSUE TITLE
Dip Switches don't work on MAME 2010

### ISSUE THREAD

**Issue by Gumersindo3** [KMFDManic/NESC-SNESC-Modifications#42]
MAME 2010 works beautifully until you want to tweak the dip switches. You push  the ZL button, appears the menu, but you can't choose anything of the options. I don't know if it is a problem of retroarch itself, the MAME 2010 or the hmods.

**Comment by KMFDManic** [comment]
What controller are you using?  I will be Updating my Core Set, and will do a MAME 2010 Test to check into the dip switches, when I do so.

**Comment by Gumersindo3** [comment]
I used the Super Nintendo pad and the Wii pro pad (not the wiimote).

**Comment by KMFDManic** [comment]
Yep, I do vaguely remember the MAME Options not working for MAME 2010, at least on the NESC/SNESC.  They work absolutely fine for MAME 2003, however, as does the Cheats HMOD:)  MAME Options not working is likely a side effect, from it having support for other platforms.  Not sure if it is something that can easily be fixed.  But, I can talk to the people who work on it and see what they say.

**Comment by KMFDManic** [comment]
@Gumersindo3 It is broken for MAME 2010 on the NESC/SNESC.  I would suggest you use MAME 2014, instead, which works perfectly with it.  MAME 2003 and MAME 2014 are best for MAME Options Ability.  2000 is great for games that run a little slower on the other Cores, as well as the obvious Midway/Bally Games that do not run on MAME 2003:)  All of the Arcade Cores have their perks:)  So, try out MAME 2014:)

**Comment by KMFDManic** [comment]
@Gumersindo3 dip switches work fine on PC.  But, being in this environment, it got broken, sort of how Midway-Bally games tend to have issues running on MAME 2003, yet on PC, they do not:)  Use MAME 2003 or 2014, for your dip switches:)
