### ISSUE TITLE
Cdi with MAME emulator?

### ISSUE THREAD

**Issue by Astromatik** [KMFDManic/NESC-SNESC-Modifications#44]
Dear Kfmd,
This is a astromatik question again^^
With MAME is it possible to load Philips CDI iso.
I think is fun to load old games Nintendo CDI on our SNES CD Mini XD
Thank You for all your works.

**Comment by KMFDManic** [comment]
Unfortunately, no.  I wouldn't completely rule Philips CDI out!  But, it just isn't something to expect immediately:)

**Comment by KMFDManic** [comment]
@Astromatik
