### ISSUE TITLE
dosbox or Atari St with MT32 Expander (Roland)

### ISSUE THREAD

**Issue by Astromatik** [KMFDManic/NESC-SNESC-Modifications#45]
I see on your first video You play electro drum ^^,
You make musique on your PC to?
I thinking about windows95 or Atari ST with snes but it is possible to install an old cubase and make music with the snes mini?
With dosbox turbo on Android the team give possibility to play game with the great Expander MT32.
Making sound with good sequencer like Cubase the Dream for geek music

**Comment by KMFDManic** [comment]
Hehe, I played MTV Music Generator, a long time ago on PS1 to dabble in music!  You familiar with that?

You could technically use Windows 95 with Dosbox on NESC/SNESC, using imgmount.  There are many possibilities to run almost anything!

**Comment by Astromatik** [comment]
Ok i tried to install windows 95 first.
I tell you the config that retroarch gives me on the sound card.
it would be possible to put that
 https://sites.google.com/site/dosboxturbo/
Midi section.
I think it would be great to remake mytic games of click and play like the Kyrandia or the Dune 2, it really has the punchy the mt32.
And with cubase ... WouHou Pif !! Paf !!! XD
like your works

**Comment by KMFDManic** [comment]
Imgmount option is what you'd want to use.  And, yes, the sound thing would be fun.  I am not sure how well it would work, because even the x68000 Core has issues running Roland Support.
