### ISSUE TITLE
Daniel User Error

### ISSUE THREAD

**Issue by mrTruch** [KMFDManic/NESC-SNESC-Modifications#47]
I was gonna use last Hakchi mod from Dantheman. I wanted to use it as normal with my NESC, and to new USB method, but several problems with my NESC, first flashing and everything else. I did it with another version, but all my new list was ready with this new Dantheman version so....I use it and it said (in spanish):

Referencia a objeto no establecida como instancia de un objeto.   en com.clusterrr.hakchi_gui.WorkerForm.UploadGames() en X:\Users\Daniel\Documents\GitHub\hakchi2\WorkerForm.cs:línea 887
   en com.clusterrr.hakchi_gui.WorkerForm.StartThread() en X:\Users\Daniel\Documents\GitHub\hakchi2\WorkerForm.cs:línea 300
Referencia a objeto no establecida como instancia de un objeto.   en com.clusterrr.hakchi_gui.WorkerForm.UploadGames() en X:\Users\Daniel\Documents\GitHub\hakchi2\WorkerForm.cs:línea 887
   en com.clusterrr.hakchi_gui.WorkerForm.StartThread() en X:\Users\Daniel\Documents\GitHub\hakchi2\WorkerForm.cs:línea 300
write error: Win32Error

So it is unable to use it.

Thinking about it....maybe this Daniel user is....Dantheman....so it seems that some line codes ara not working or just....is NESC incompatibility....again...

Thanks for your work and consideration.

**Comment by KMFDManic** [comment]
@mrTruch , that appears to be path related, based on paths from his computer.  Also, SNESC is easier to do USB-HOST with.  I will be doing a tutorial on NESC for it.  Do you have an SNESC to do this with, in the meantime?

**Comment by mrTruch** [comment]
Yes. But I wanted to use it same hakchi for both....thanks for answer.
