### ISSUE TITLE
Black screen USB HOST (SFROM not accepted) [Temporary solution]

### ISSUE THREAD

**Issue by mrTruch** [KMFDManic/NESC-SNESC-Modifications#48]
Hi again. First at all thank you for your work.

Some time ago I could make to work USB HOST with my snesmini....and I let it be...

Yesterday and later...today I was struggling my head to make it work with my own compilation.

The SNESC is working, without USB like original. With USB I can read "boot.png", folders structure, games etc.

I've tried to modify with notepad++ all desktop files to make it work every ROM with snes/snes10 command but...it's not responding. You hit the rom and black screen starts

I've tried several ways:

CloverAPPforSNES. Manual mode( Load core/Load content....) not load the rom.

One game with folders/without folders
Both, linked, not linked, compressed, uncompressed....

All entire set "linked", divided per equal in folders get C7 error. (not black screen) (maybe is result to modify wrong the desktop files.....I don't know for sure)

All of these proved with diferents hakchi folders, old and clean.

--------ONLY SUPER NINTENDO ROMS WITH CANOE WORKS FOR ME----------

Maybe is some mistake...earlier. With hakchi1....but if loading roms with canoe is possible I don't think so....

What do you think....? Please help me and get me some ideas to try.

**Comment by KMFDManic** [comment]
Flash drive brand, size, and format?  OTG Device Type?  How are you powering it?

**Comment by mrTruch** [comment]
Flash drive 32Gb Phillips. Fat32. Same USB OTG like yours (previously tested with full psx game).
Powering through adapter USB (two models tested 2.4v & 1.5v)

All is working, as I said..., for example Super Nes roms loaded with canoe are working, cores and retroarch are inside checked via CloverAppSNES....¿? :'(

**Comment by KMFDManic** [comment]
Which way are you installing hmods?

**Comment by KMFDManic** [comment]
also, pick one random game you cannot run and show me command line and it's desktop file.

**Comment by mrTruch** [comment]
Installed hmods via "transfer" folder:

clovercon-usb.hmod
dtm_font_remount.hmod
fontfix.hmod
madmonkey-modules-3.4.112.hmod
tiny7zx-dynamic.hmod
_km_gambatte_10_24_17.hmod
_km_glupen64_6_26_17.hmod
_km_mame2014_10_24_17.hmod
_km_mgba_12_11_17.hmod
_km_pcsx_rearmed_neon_9_15_17.hmod
_km_picodrive_11_7_17.hmod
_km_retroarch_extreme_filters_11_25_17.hmod
_km_snes9x2010_11_9_17.hmod
_km_yabause_11_6_17.hmod
_km_mgba_12_11_17.hmod\bin
_km_mgba_12_11_17.hmod\etc
_km_mgba_12_11_17.hmod\install
_km_mgba_12_11_17.hmod\readme.txt
_km_mgba_12_11_17.hmod\bin\gba
_km_mgba_12_11_17.hmod\bin\mgba
_km_mgba_12_11_17.hmod\etc\libretro
_km_mgba_12_11_17.hmod\etc\libretro\core
_km_mgba_12_11_17.hmod\etc\libretro\info
_km_mgba_12_11_17.hmod\etc\libretro\system
_km_mgba_12_11_17.hmod\etc\libretro\core\mgba_libretro.so
_km_mgba_12_11_17.hmod\etc\libretro\info\mgba_libretro.info
_km_mgba_12_11_17.hmod\etc\libretro\system\gba_bios.bin


[NOT WORKING.zip](https://github.com/KMFDManic/NESC-SNESC-Modifications/files/1565753/NOT.WORKING.zip)
[WORKING WITH CANOE.zip](https://github.com/KMFDManic/NESC-SNESC-Modifications/files/1565755/WORKING.WITH.CANOE.zip)
Attached two desktop files. Thanks for helping. Again.

**Comment by KMFDManic** [comment]
I can already see you have a real mess on your hands.  I am not on computer yet.  But, I will step you through what to do when I am on PC.

**Comment by mrTruch** [comment]
Thank you very much!!!

**Comment by mrTruch** [comment]
Hi, Where you go? hahahaa, here it is 4:20 AM...and...I must to go to bed....but...after several hours today....I know what is the "problem" (For now, I have others: C errors)

I Think "tiny7zx-dynamic.hmod" it's not working, I've tried to install every time and twice.....

It because of that the first time I proved the USB host method it worked,.....because I used an eboot.pbp (PSX rom)....

Now with retroarch....Loadin core, and testing uncompressed roms....it works. So I have to uncheck compressed on hakchi2....now I have more space is viable....but it's necessary? Why this error?

I am gonna try for last time with Hakchi 2 exported & linked, uncompressing games and ?'ll see what happen....

Keep anwering and thank you for your help.

**Comment by KMFDManic** [comment]
I did not forget about you:)  I am posting a Core Update, which will directly be used in helping you do the process correctly. It will make things easier for you to follow my steps.

**Comment by mrTruch** [comment]
Thank Sensei!

Maybe you remeber me on youtube as the user with troubles with "xcopy"

Now...it seems games ".sfrom" & "7z" are not working with SnesX core.

**Comment by KMFDManic** [comment]
https://youtu.be/7jrcJZCynFA

**Comment by mrTruch** [comment]
Thank you. I didn't remeber this video, probably unwatched.I sw it before go to bed.

Well...how now i cannot have fixed the 7z....I don't think a double zipped works for now.

**Comment by mrTruch** [comment]
Hi, How are you today? Ara you still posting?

Maybe you are waiting for some cluster releases. I still dont know why tiny7zx doesnt install....or work. (for me). So tired to keep trying....

**Comment by KMFDManic** [comment]
Yep posting, shortly.

**Comment by mrTruch** [comment]
Hi, more testing.

Installed Tiny7zx hmod uncompressed like a folder.
sfc games compressed as 7z working. Sfrom not working yet.

**Comment by KMFDManic** [comment]
Updated Core Set.  Use the USB-HOST Specific Files I included.  Use the uninstall to remove everything, then install the ones I have.  You do not need to install fontfix.  install dtm_font_remount in its place.  Your issues are going to be directly related to your command lines and desktop file arrangements, after you do the process with 12-1-17, and use transfer folder for hmods, properly.  Copy an entire command line for whichever game you can't run.  I can help you with its proper set-up.  Be sure to keep games to 60 or less, at first, til we iron the kinks out.  Most people tend to have command lines or desktop files incorrect.  So, we will start with that, once you use today's Update.

**Comment by KMFDManic** [comment]
Let me know if you still need help.

**Comment by mrTruch** [comment]
Hello.

Sorry I didn't answer you sooner. I've tried everything you said, but it still doesn't work. I had a lot of trouble with this.

It's frozen several times. Nothing works and in the middle of a black screen... my usb is dead.

I've spent almost two days trying to resuscitate the usb because before so much power failure by forcing the switch off was in system "RAW" but I can assure that it was useless forever.

Many C3, C8 errors. In addition, the menu returns to its original state if the system is not turned off properly.

Honestly, it's not worth the effort. 

Tiny7zx does not work, I installed it as a HMOD folder. Then 7z files do work but commands through hakchi2 do not.

As I said before if I use CLOVERAPP it works by menu, except for some specific error... but of course, you can't save the games.

I think it's an error when modifying the kernel with hakchi 1, but it's rare that everything but desktop commands works.

All roms run uncompressed and installing Tiny7zx as I said work 7z with emulators but the roms in "SFROM" format do not.

It's a big headache. I'll wait for the cluster system to start and do everything through hakchi2 unless a new hakchi1 or system comes out that makes sure it reads SFROM.

Thank you so much for everything.

I don't know how he marks the subject as "weird mistake" or something like that.

PS: This time I have used a translator, although I defend myself in English. I'm sorry if it's not well understood, but from so many tests I've been a little mentally exhausted.

**Comment by KMFDManic** [comment]
You are ok, man!  Just don't let things get you down.  I am releasing a video today, which may help you out!  Again, you really need to keep things simple, to start with.  I will do my best in the video to make it easy!

**Comment by mrTruch** [comment]
Thank you. The video are no problem. Are good enough, but something is wrong....maybe hardware....my pc maybe is broke or infected, or the USB cable....I just don't know. I'll watch your video and I am going to follow your steps, but i did this time.....and no results.

**Comment by mrTruch** [comment]
By the way....Are you going to compile again hakchi1 with today cluster commits?

**Comment by mrTruch** [comment]
Hi mister!

Bad news.

All started again, from hakchi 1 & 2 clean. Nes USB cable.
1st Uninstall
2nd flash original, just in case....

This twice. (installing again NESMINI driver)

Only working through.....clover app loading roms unzipped.
This time it was impossible to me install tiny7zx.

Loding snes usa/japanese firmware working. Like I said everything except unzipping...and loading (obviously, from menu).

More information:

Hakchi 2 linked used, Linked shyncro.
CloverappSNES
and more 7 six games, (GBA, SNES, NES, MD, 32X, N64, GB) and inside media one folder with same uncompressed.

All the HMOD are only 15MB.

For last chance...I uninstalled all and just like you said before I have used dtfmount instead fontfix....

Edit: This time it's working like before (using dtfmount instead fontfix.)....working with 7z.....but if I select any "sfrom" it frezees.....

Stucked forever, I must to switch off twice getting C8 error.


Sorry men. I don't know what is wrong.

**Comment by mrTruch** [comment]
![menujp](https://user-images.githubusercontent.com/25885652/34286860-c8f219b8-e6e3-11e7-81ff-beac561fdab8.jpg)
![menuusa](https://user-images.githubusercontent.com/25885652/34286861-c942c9b2-e6e3-11e7-8a28-7508cfedb242.jpg)
Great Firmware use...but...not loading games...screen black....and after seconds return to menu with flying suspend point.
![flyingsuspend](https://user-images.githubusercontent.com/25885652/34286923-1edcc3dc-e6e4-11e7-95a8-1a5df4178f50.jpg)

**Comment by KMFDManic** [comment]
If you are ok using Teamviewer tomorrow, I can fix your setup for you.

**Comment by mrTruch** [comment]
Ok. Now here it’s very late xD as can you imagin.

I usually use it to help others. Family and friends. Actually never no one use it to enter to my pc. Let me know how can we contact to give you mi ID and pass or if you know the easy way.
I’ll try to prepare it all at the desktop and let it clean and handy.

Thank you very much. Goodbye

**Comment by mrTruch** [comment]
Let me know. Remeber, I am 6 hours more than you.
Teamviewer try my email: tarduschl@gmail.com
Telegram: Truchen

**Comment by KMFDManic** [comment]
I will email you.

**Comment by mrTruch** [comment]
Update 2:

7z files on menu, without folders is working, snes games with canoe and other are working....

But...SFROM files not working yet. Commando /bin/snes not working

Black screen appears, power offand then....C3, and other, I must to turn off with power off to avoid several errors. Turning on is like a reset/reboot no more error since I've decide to run SFROM.

Another try is to install all SNES core available. All core are the same....Browse archive and then....not even detect sfrom file...not to mention load them.

So...I think I am aproachin to unveil what is the problem...

**Comment by KMFDManic** [comment]
What is a full command line for an sfrom game?

**Comment by mrTruch** [comment]
Full command?

/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-VFDWU/Super_Mario_All-Stars__Super_Mario_World_USA.sfrom.7z --volume 100 -rollback-snapshot-period 600

By default...I just replace "clover-canoe-shvc-wr -rom" to "snes" by hand.

**Comment by KMFDManic** [comment]
Ok, try this, you familiar with my Dual Core Method?  You would 7zip, then zip the SNES rom, then add into hakchi2, so that it retains its .sfc format.  With this, you can install SNES9X Dual Core, and run it:)  You can STILL run Canoe Games.  But, this will allow you to run sfc ones, too.  So, more or less, your issues are entirely related to Cores you have installed, the file names, and command lines.

**Comment by mrTruch** [comment]
Ok, I 'll try it, but I was supossed that I was tested befor....more detaills. Thank you very much.

**Comment by KMFDManic** [comment]
Also try having sfroms uncompressed in hakchi2, then close hakchi2, so desktop files save correctly...Then, copy their folders to usb.

**Comment by mrTruch** [comment]
Not possible to load any SFROM.
But...I guessed a better way to LOAD ROMS from menu.....

I've selectes a few roms (sfc & smc super nintendo roms) and I've changed the extension to "SNES9X".

And I put it all of them on a folder, now...because you configured the SNES9X core to run "/bin/snes9x" how by default it recognizes as a extension.....

I don't hace to write anything else....now this roms are working from menu directly with snes9x core

1.54.1 5d60ecd

Well only I have to adjust with what core I needn in any case (just for compatibility, chip FX on 2005 or 2010)....and no more headaches...

Ok...its a temporal solution. It must to work simply changing "/bin/clover-canoe-shvc-wr -rom" to "/bin/snes" or similar...just after adding and hakchi have patched the rom but....how I prefer to run all my games by retroarch I just simply I have to start from beginning to changing all my extension, fpr now.

What do you thing about it? Don't you think it's easier to change it to snes9x extension instead of "inception zipping" hehehe

Let me know your opinion, is very important.

AH!! And I almost ? forget it....linked folders (only usual way) is not working....I think is something about desktop files becasue I try to load...it stills black....and return to the menu without C errors.

Wel...Thank you for everything, more ideas to solve linked folders...let me know.
[games.zip](https://github.com/KMFDManic/NESC-SNESC-Modifications/files/1583815/games.zip)

**Comment by mrTruch** [comment]
I wish you a merry Xmas, when you can look at my "linked estructure folder desktop"?, Now I'm spending my free time making my own romset on my PC.

**Comment by KMFDManic** [comment]
I am gonna put together a test setup for you to copy directly to flash drive.

**Comment by KMFDManic** [comment]
@mrTruch I know roughly why you are having general issues and need to get a video out about it.  But, I am gonna post you a test setup, as well.  Enjoy your Xmas!

**Comment by mrTruch** [comment]
Ok. Let me know how. Here or via email. Thanks!!!

**Comment by KMFDManic** [comment]
Making Dummies Guide to USB-HOST Video today.  Closing this issue. But, will keep communication with you via email.  The video should help you better understand why you are having trouble:)  I will keep in touch!
