### ISSUE TITLE
C4 ERROR Missing savestates

### ISSUE THREAD

**Issue by mrTruch** [KMFDManic/NESC-SNESC-Modifications#5]
Hi, thanks to your work. Me and my friends follow your work.

Today I was updating with your Retroarch "_km_retroarch_10_18_17.hmod" since i did this, it was impossible to keep saving savestates, always getting C4 error. (Even Canoe).

I had to do, flashing, restoring, etc but....the SNESC...turn into original status....and...then....when I have to do it again....SNESC turn into original status.....without savestates!!! Not single one!!

So I decided to reverse all my actions and return to Retroarch's Cluster (1.0c) and....MAGIC! The savestates have returned...

Sorry my english, I'm Spanish.
![yezpmc2p hz4](https://user-images.githubusercontent.com/25885652/31840266-df6dff20-b5e4-11e7-8454-153853b11e49.png)

Using: HAKCHI 2.21e
77 games (255mb free)

EDIT: PS: I Have to admit that...I don't know how...but my folder strucuture options was changed to another one. I have always use custom.

**Comment by KMFDManic** [comment]
Are your 77 Games in one single folder?

**Comment by mrTruch** [comment]
No, it's five folders. To rule that out, I've tried it again.
I've managed to get everything installed again.

I have uninstalled the cluster retroarch, I have set this one, when the process is finished, error C2 appears (returns the factory settings).
It doesn't work either.

I uninstall it and reinstall the retroarch that works (cluster' s) and the C2 error appears again.

The only way it'll work as usual.

**Comment by KMFDManic** [comment]
You try flashing custom Kernel?  I tested and had no issues.  I even tried it on 2.21e.  There has to be some minor thing that may have been missed.

**Comment by mrTruch** [comment]
I think too....

And yes, I have repeated all the process twice. Previously I used 2.21d.

Other minor things to check....
- Other usb
- Uninstall HMOD/s like extra_space
- Use clean hakchi folder...or just erase folders_snes.xml or config file....

**Comment by KMFDManic** [comment]
Try using the debug version of hakchi2.  Let me know if you still have any problems
  Do not worry:)  I have helped over 1000 people troubleshoot their nesc/snesc over the last year:)

**Comment by KMFDManic** [comment]
Worst case scenario, I have even gotten remotely connected via TeamViewer to see exactly which mistake others were making!  Do me this one little thing.  Copy a command line for one of the games that you are having trouble with save states with.

**Comment by KMFDManic** [comment]
Ok, grab the Updated RetroArch from my Main Release.  There was a bug which caused bigger save states, due to snap shots not being compressed.  Everything is fine and fixed now!  I would recommend using Factory Restore Settings on your SNESC/NESC to wipe save states, if you do not mind getting rid of them!  Thanks for the heads up.  I jumped right on making sure everything was ok.  You may have run into save states taking up too much space, which is why you had C4 Issues.  Things should be good now, as I just updated!

**Comment by mrTruch** [comment]
Well....after so many work....now is working!! 1.6.7!!
What I have done? Many things...

-change cable usb
-change usb port
-reboot windows
-try hakchi debug (twice, same errors) C4 with 1.6.7 and then....
C2,C2,C2,C2,C2,C2,C2,C2,C2,C2,.....everey time, get into the folder, out, turn on...etc...
-try hakchi 2.20 (old version that surprisingly I keep it....)
-try again hakchi debug erasin config file:


  ----factory reset inside menu SNESC (before saving my star fox level 1 passed)
  -----Configurate hakchi with my presets (custom folders, shortcut reset, etc)
   ----flash original kernel 
   ----flash custom kernel....
All the games were there and working...I don't know if I forgot something...is very strange case....

FOR NOW WORKING.....5:19 am...here.... :D

PS: I've attached the last log, maybe can help you (or me) to understand what was wrong
[debuglog.txt](https://github.com/KMFDManic/NESC-SNESC-Modifications/files/1403729/debuglog.txt)

PS2:  Meanwhile i was writing you remind me to wipe save dates....I almost forgot to write this step and I think this would be the solution.

THANK YOU VERY MUCH!!! KEEP UPDATING PLEASE!

![001](https://user-images.githubusercontent.com/25885652/31847617-8e945fbe-b61f-11e7-901a-c61b2de9ad7a.png)
![002](https://user-images.githubusercontent.com/25885652/31847618-8eb97934-b61f-11e7-907e-b134d5d8073a.png)
![003](https://user-images.githubusercontent.com/25885652/31847619-8ed70436-b61f-11e7-8516-65e1644f5715.png)

**Comment by KMFDManic** [comment]
Ok, your problem was that you needed to flash custom kernel:)  That was it!  But, enjoy the updated RetroArch I just posted, along with Stella, the great Atari 2600 Core:)  Flashing Custom Kernel is one of the most common reasons people have trouble with save states, games functioning, etc!  Thank you for following my Core Set, and enjoy the future updates, amigo!
