### ISSUE TITLE
Newest Release broke retroarch

### ISSUE THREAD

**Issue by Grumstrum** [KMFDManic/NESC-SNESC-Modifications#50]
I can't get any other games but snes to work after the newest core release.

**Comment by Grumstrum** [comment]
I have the bios_neo_uni_fba2012, fbalpha2016, mgba, picodrive, retroarch, snes9x2010, and remove thumbnails.

Fba works fine. Mgba and picodrive  dont seem to be working. MD, GBA, and GB games don't work anymore

**Comment by KMFDManic** [comment]
Fixed:)  Thanks so much for the feedback, my friend!
