### ISSUE TITLE
Night Slashers Mame 2003

### ISSUE THREAD

**Issue by pilotS1** [KMFDManic/NESC-SNESC-Modifications#52]
First of all thank you for the awesome work.

I wanted to give an update on night slashers. I cant get it to run past level 3. On level 4 the game just automatically resets and you have to start all over. I tried both the japanese and the us version of the rom with the same result. Any thoughts on to why thats the case?

**Comment by gingerbeardman** [comment]
Does it work on PC/MAC MAME 2003?

**Comment by pilotS1** [comment]
I am talking about the latest relase here:
https://www.youtube.com/watch?v=LRJVnPXj_ts

Night slashers was never a mame2003 game rather than  mame2010 game. (I think)

**Comment by KMFDManic** [comment]
Maybe you are stuck in Demo Mode:)  But, seriously...Night Slashers is a very heavily encrypted game.  There are prone to be unforseen bugs when implementing unencryption fixes.  Hopefully, this is one that can be replicated based on previous decryption attempts.  I will make the issue known to an acquaintance of mine and see if a fix is feasibly possible. Still, pretty awesome even being able to run this stubborn game!

**Comment by pilotS1** [comment]
That would be a pretty long interactive demo :). Thank you its such an awesome game!

**Comment by pilotS1** [comment]
Ok. I got it working over level 3 I am on level 4 now. You need a specific release for night slashers of rom. Its only a bit chopy on the sound on level 2 where the transparency or when too much is going on. Such awesomeness there cannot thank you enough. Been wanting to play this for ages without pc emulation.

**Comment by KMFDManic** [comment]
I still communicated the bug, and the US version of Night Slashers is not fully compatible with the decrypted code.  But, the other versions are:)  There is an ARM fix that went out in my latest MAME 2003 Update last night.  There will be another great Data East Game making an appearance in Today's Update:)
