### ISSUE TITLE
pcsx_rearmed_neon Core Japanese Games

### ISSUE THREAD

**Issue by pilotS1** [KMFDManic/NESC-SNESC-Modifications#55]
I am having trouble running japanese games. They dont start at all. Only JAP though. I checked the bios on the core and they are there. Can someone confirm if JAP games run with that core or dont?

**Comment by KMFDManic** [comment]
Being that you are the second person to let me know a Japanese Game was not running, within the last few weeks, I will investigate further:)

**Comment by gingerbeardman** [comment]
I didn't think to check other Japanese games 🤦‍♂️

**Comment by pilotS1** [comment]
It's not that I tried only one. I tried 5-6 games and its odd that they dont even boot. Something is wrong there just dont know what. I played around with the bios files a bit but had no luck starting a JAP game up.

**Comment by gingerbeardman** [comment]
I'm the other guy that reported this and I only tried one 😂

**Comment by KMFDManic** [comment]
I will try to fix, if possible, before Updating.

**Comment by KMFDManic** [comment]
@pilotS1 @gingerbeardman Here is a revised PSX Core, til I Update into my Set.  I was able to run a majority of Japanese Games without issue.  If you at first, do not succeed, try an ALTERNATE version of the same Game.  Some were ripped in very goofy ways, which breaks ability to run.  I was able to run 28 out of 34 Japanese Games, in testing with Revised Version.  Try loading the BIN Files, directly, from Load Content, as best test.  Or, main file, whichever source file you are working with.  Ignore the Cue files, for testing.  I am closing the issue, as Japanese Games run, minus the obvious goofy ripping methods, and overall compatibility.  I have a few REAL Japanese Games, and ripping them to computer, by my normal ripping methods, they all loaded:)  Thanks for the heads up, things should be better now!

Final Note, ECM Files need to be UnECMed using the tool in my Core Set.

And, @gingerbeardman still no success on your game.  But, other Hanafuda Games were fine.  Just check for more alternate sources, and hopefully you will hit a good one, if it is compatible!  But, Japanese Games now run.  I ran Pepsiman as a test on non-revised, and it failed.  Loaded it on THIS one, and it worked perfectly  

Date is unchanged in the Core, for my own personal records.  But, it IS different.

https://ufile.io/dsozu

**Comment by gingerbeardman** [comment]
I have the Jarinko Chie Hanafuda PSX disc here, what is your recommended way of ripping?

**Comment by KMFDManic** [comment]
IMGBURN is a great program for ripping PS1 Games from Real Discs.

**Comment by gingerbeardman** [comment]
OK, I'll try IMGBURN.

Do CHD files work with your cores? I try games on RetroArch on my Mac prior to loading them on the SNES Mini and only the Beetle PSX core supports CHD there?

**Comment by KMFDManic** [comment]
No to CHD.  I am trying to get CHD implemented for this Core, since Beetle PSX isnt compatible for NESC or SNESC.

**Comment by gingerbeardman** [comment]
OK, it's working!

I thought to myself "well why is it that it works in pcsx on my N3DS?" Maybe I ripped it a certain way years ago? Anyway I copied that image off my N3DS (bin/cue) and that works on the SNESC. I use the bin file and tick compressed in.

acb572b838efb208ed45608db432d41cc3e76a4f  Jarinko_Chie_Hanafuda.bin

**Comment by KMFDManic** [comment]
I should have thought to test other Japanese Games, as well:)  Glad all is ok, now.
