### ISSUE TITLE
MAME2003 cheats never show

### ISSUE THREAD

**Issue by jodriscoll** [KMFDManic/NESC-SNESC-Modifications#56]
I've tried, multiple times, with both types of modding (standard and USB-HOST), to load your mame2003 hmod for cheats and for whatever reason, it is refusing to pass through and show.

Not sure if I'm approaching something wrong, but I'll follow up with a video shortly within the day.

**Comment by KMFDManic** [comment]
You have to go into RetroArch Options, then Options, then Enable Cheats, then push R2, then open up the NEW Cheats Menu, and select the cheats for whichever game you load.  This only works with MAME 2003, and works fine on USB-HOST, as well as non-USB-HOST.  Cheats do not load the same way they do with the other Cores.  This way is entirely different, as when I tried the other way..it crashed the Core, every time.  This way works perfectly.

**Comment by KMFDManic** [comment]
I am assuming the solution I provided has solved the problem due to lack of response.  Feel free to respond of you need anymore assistance, @jodriscoll :)
