### ISSUE TITLE
Mame 2003 save states not working

### ISSUE THREAD

**Issue by bbaggins19** [KMFDManic/NESC-SNESC-Modifications#57]
Hello with the _km_mame2003_1_4_18.hmod  save states are not working.  They save, but when you go back into the save state, it does not load properly.  I am not using the USB host. Thanks for any assistance.

**Comment by gingerbeardman** [comment]
How are you managing the save states? Through SNESC interface?

**Comment by bbaggins19** [comment]
Once a save state is made when playing the snes, by pressing Y.  When I go to the save state, it does not work for the mame2003 hdmod, while it works for all the other hmod save states.

**Comment by KMFDManic** [comment]
They never have worked for MAME 2003 due to eeprom save issues.  They do work on FBA 2016, though:)

**Comment by bbaggins19** [comment]
Ok, thanks.

**Comment by KMFDManic** [comment]
Feel free to ask if you need anymore help:)
