### ISSUE TITLE
Street Fighter Alpha 2

### ISSUE THREAD

**Issue by sjgangler** [KMFDManic/NESC-SNESC-Modifications#58]
Hey guys, great  job with everything.  Modest hacker on this so I appreicate the videos and updates.  Just used the 1.118 release and went to try SFA2, and when I load it up, nothing happens.  Now the weird part is that then I start getting C2 C3 and C7 errors.  But other games played and worked until this one.  Is this just one of the games that cannot play or did not I load a modification that is needed?  Any help is appreciated as I get the hang of this!

Steve

**Comment by KMFDManic** [comment]
If running via canoe, it needs Preset ID adjustment.  It runs fine using my dual canoe method and one or more of the SNES 9X Cores

Dual Canoe
https://youtu.be/7jrcJZCynFA

**Comment by Dark-Akuma** [comment]
I'm not sure if the SFA2 sfrom was made with the old obsolete bat file, or sfrom Tool. But either way the result is a proper sfrom. If you take a proper sfrom in hakchi2 and open up the ctrl+alt+e preset id window, it will corrupt the sfrom. You don't need to set the preset id at all with either the bat file or sfrom tool generated sfroms. It's already set. This is the most likely cause of a issue like this that I can think of.

**Comment by KMFDManic** [comment]
@sjgangler I called in the residing expert, for this one::)  I know RetroArch, but not Canoe:)
