### ISSUE TITLE
[PC-98] ability to specify two "roms" to load into drives A and B

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#59]
Currently I do this to start PC-98 with floppy disk A loaded:
`/bin/pc98 /usr/share/games/CLV-Z-PMCAE/AlaskanMalamuteGC-Disk1.fdi`

but I'd like to be able to do this to load both A and B:
`/bin/pc98 /usr/share/games/CLV-Z-PMCAE/AlaskanMalamuteGC-Disk1.fdi  /usr/share/games/CLV-Z-PMCAE/AlaskanMalamuteGC-Disk2.fdi`

I mean, I can do that command line but the PC-98 core ignores the second "rom"

The workaround is to press L2 and then browser to /usr/share/games/CLV-Z-PMCAE/ and then mount floppy disk B manually, which is an annoyance.

Your consideration is appreciated!

**Comment by gingerbeardman** [comment]
I'm experimenting with a way to create my own PC98 .hdi image of any sets of floppies I have.

But I'd still like to see the above request!

**Comment by gingerbeardman** [comment]
whilst this would be nice, feel free to close it if you so wish

the new source of disks I have found seems to have .hdi for my games,

https://archive.org/details/@neo_kobe_team

**Comment by KMFDManic** [comment]
You will have another way of doing this, that I will communicate to you:)

**Comment by gingerbeardman** [comment]
Thanks!
