### ISSUE TITLE
[Request] np2kai (PC-98) core

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#6]
NEC PC-98 emulator (1980s/90s Japanese PC)

It's in the latest retroarch nightlies

**Comment by KMFDManic** [comment]
I can try to see on this one:)  I was aware of it!  But, I haven't really taken the time to test it yet!

**Comment by KMFDManic** [comment]
Success on PC-98!  I will update it to my set today:)  Have fun!

**Comment by gingerbeardman** [comment]
Sadly my SNES mini died and is off to Nintendo for repair (I think the USB port was shorted when I forced a cable in) but I can't wait for it to come back! Thanks!

**Comment by KMFDManic** [comment]
Ok, if you can, let me know what core u would like to try running on 3ds.  We gotta start somewhere. Try to keep it non-cpu intensive, for our testing.

**Comment by gingerbeardman** [comment]
It's not that the 3DS is short of cores, it has most things I want, but rather that they are old versions compared to yours and they're lacking features (such as touch screen keyboard in fMSX). I'll give it some thought.
