### ISSUE TITLE
[GME] core crashes when loading Mega Drive music in .vgz format

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#60]
I've tried some .vgz files, and even an .m3u but i cannot get the gme core to do anything?

**Comment by KMFDManic** [comment]
Command line /bin/gme

m3u is a playlist, so wouldn't work.

You can also load the core, then load content, then select the music files.

**Comment by gingerbeardman** [comment]
When i launch it i get a black screen and am then returned to the SNESC menu. No chance to open the core menu.

**Comment by KMFDManic** [comment]
Command line for one you are attempting to run?  If you added them with compression option enabled in hakchi2, that is why they do not work.  They should be uncompressed.

**Comment by KMFDManic** [comment]
In action

https://youtu.be/6Vh-UP178co

I did a few OST Videos, heh:)

**Comment by gingerbeardman** [comment]
OK, then I cannot play any Mega Drive vgz music from http://project2612.org

The core on macOS also cannot play them so I'll report it upstream.

**Comment by gingerbeardman** [comment]
https://github.com/libretro/libretro-gme/issues/4

**Comment by gingerbeardman** [comment]
Fix coming upstream

**Comment by gingerbeardman** [comment]
Works a treat! Thanks!
