### ISSUE TITLE
Hi I'm using your cheat modes and can't seem to get them to apply.

### ISSUE THREAD

**Issue by nychao** [KMFDManic/NESC-SNESC-Modifications#63]
I go to quick menu enable them but nothing happens when I try to apply them

**Comment by KMFDManic** [comment]
Try with an NES Game, such as Contra, to verify things are working.  Most of the time, people having issues, tend to use incorrect versions of games.  So, let a familiar NES Game be a starting test.  I tested with every system.  They all work when with appropriate games.

**Comment by DefKorns** [comment]
@nychao there are some cheats that simply won't work. For example Chrono Trigger have 15 cheats only 3 work (the one without multiline, the one that has a + and without ??)

**Comment by nychao** [comment]
Super Valis IV, x men for snes. Restart game doesn't work either if that gives any useful info

**Comment by nychao** [comment]
I was able to get some cheats working on xmen, it just doesn't say cheats applied like I saw on a video and I go to resume not restart. Thanks for your great work it's freeaking awesome, going to try getting a usb drive working next.

**Comment by KMFDManic** [comment]
@nychao ,It still says cheats applied.  The message is just invisible:)  I will show how to make messages appear, for confirmation, when I do another video.
