### ISSUE TITLE
[PC98] ability to bind the GRPH key to a gamepad button

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#64]
It would be very useful to be able to map this to a button. Some games use it for extra options or features. 

_Harukanaru Augusta 2_ uses it to allow the user to speed up graphics display on demand.

Thanks!

**Comment by KMFDManic** [comment]
Definitely post this as a request, for them to do:)  Very good Choice:)

**Comment by gingerbeardman** [comment]
Right Alt key is PC98’s GRPH/GRAPH key
