### ISSUE TITLE
mame2003 nba jam te rev 2.0 compatibility

### ISSUE THREAD

**Issue by firecat700** [KMFDManic/NESC-SNESC-Modifications#68]
Anyway to get said game above to work? I can get the other nba jams to work but they don't play right.The sound is screwed up on your latest mame 2003 for snes classic. Seems like a midway game issue cause mk1 acts up too.Thanks

**Comment by KMFDManic** [comment]
Midway Games have always had sound issues. Some of these run better on MAME 2000

**Comment by firecat700** [comment]
Is there a alternative hmod I could run that's more compatible besides mame 2000? Just think it would be fun to play these on my snes classic instead of my pc. thanks

**Comment by firecat700** [comment]
Also id loose my retroarch mame cheats on mame 2000 wouldn't i?

**Comment by KMFDManic** [comment]
@firecat700 Unfortunately, cheats will only work with MAME 2003/2014. Midway Games suffer somewhat on MAME 2003, and generally run better on 2000.  2014 due to being more accurate, will make some games run worse.  But, try 2000/2014 to see what suits you best.

**Comment by firecat700** [comment]
Ive been trying out mame2000 and nba jam te plays better (revision 2.0 still wont play though) its just that the buttons aren't configured right.They were already configured right on mame2003 without doing anything on the wii pro paddles. When i try to configure them right on mame2000 the settings wont save? Thanks

**Comment by KMFDManic** [comment]
I have been trying to get the more recent MAME 2000 to work.  But, some coding changes have hurt it being able to be properly compiled.  But, it contains a control mapper.  I am still looking into an alternative, and easy to follow way to map for 2000.  And, I will release it:)

**Comment by firecat700** [comment]
thanks
