### ISSUE TITLE
[NEstopia]

### ISSUE THREAD

**Issue by bavelb** [KMFDManic/NESC-SNESC-Modifications#69]
Nestopia functionality seems broken since the 1-11-18 version of Retroarch.

**Comment by KMFDManic** [comment]
You try /bin/nestopia

**Comment by bavelb** [comment]
Yup, all my commamdlines are bin/nestopia as i prefer that core. The roms wont load. And manually opening core/content gets no results either. I reverted back to retroarch version 12-30-17 and they work again

**Comment by KMFDManic** [comment]
@bavelb I will fix this for the next Update.  Thank you for your feedback:)

**Comment by bavelb** [comment]
No man, thank you for all your hard work. This wouldnt be even remotely possible without you. 

Not to hijack my own 'issue' but do you have any idea why replaying the new version of WinGui breaks the 'stock' games on SnesMini? 

I flashed the new version you released of it, in anticipation of the NTFS/SD support, but it seems the link to them is broken (it can no longer find the png's or the sfroms). I went both from the 1-5-18 version to the current, as well as  from stock to most recent. Both broke the link. Went back to 1-5-18 Wingui and I could continue playing FFIII :)

If needed I can open a ne issue if it's somehting worth looking into. Or maybe I'm missing something (should I put an hfqs file somewhere)?

**Comment by KMFDManic** [comment]
I will test default games to see if there is any conflict.

**Comment by bavelb** [comment]
Awesome man, love your work and your video's. Discovered a ton of new (arcade) games through them as well

**Comment by KMFDManic** [comment]
I will be doing many more Game Videos.  I have a style I will start following for them, more and more:)  Not sure if you have seen my spontaneous Stan Bush video:)

**Comment by bavelb** [comment]
That's how Rohga ended up on my SNES mini yea :)

Speaking of video's, in one of your last ones you said there'd be a upcoming video about the nuances of using ntfs/installing on ntfs. Is that one forthcoming, or is it pretty straightforward afterall using ntfs? (Maybe use the new wingui, add in the new ntfs hmod and go?)

**Comment by KMFDManic** [comment]
@bavelb Fixed:)  Be sure to check out latest videos in Arcade Series:)
