### ISSUE TITLE
[REQ] picodrive + genesis plus at the same time?

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#70]
I'd like to use 

1. PicoDrive for MegaDrive/Gensesis
2. Genesis Plus for other Sega consoles

Is this possible without me manually hacking the bin files over FTP?

**Comment by KMFDManic** [comment]
/bin/32x for picodrive in current set.  No conflict whatsoever, anymore:)
