### ISSUE TITLE
FBA2016

### ISSUE THREAD

**Issue by Grumstrum** [KMFDManic/NESC-SNESC-Modifications#71]
This doesnt appear to work anymore with the new update

**Comment by KMFDManic** [comment]
FBA 2016 was broken a few updates ago.  But, if using, FBA 2016 - 12-21-18 from current release, should work fine.  What are you trying to run? Can you load it as a Core to ensure it is installed?

**Comment by Grumstrum** [comment]
Sorry for the late response. I'm using bios_neo_uni_fba2012+req and fbalpha2016_12_21_17. Windjammers doesnt work with it anymore. Unless I'm doing something wrong

**Comment by KMFDManic** [comment]
USB-HOST?

**Comment by Grumstrum** [comment]
I'm not using the USB-Host

**Comment by KMFDManic** [comment]
See if windjammers loads using new bios, as a test.  I will check it out, otherwise, tomorrow.

**Comment by Grumstrum** [comment]
Unfortunately, I'm gone for a week. I'll try it when I get back home!

**Comment by KMFDManic** [comment]
With current FBA, Windjammers works fine for me.  I am closing the issue.  But, let me know if you still have a problem and I will help you with the correct setup:)
