### ISSUE TITLE
PSP doesn't load.

### ISSUE THREAD

**Issue by mrTruch** [KMFDManic/NESC-SNESC-Modifications#73]
PPSSPP recently installed.

I go to Load core....press PPSSPP no answer. Push back to the menu. Other core working...Are you sure you upload the good one?

Thanks.

**Comment by KMFDManic** [comment]
You can't load it as a Core.  It can only be loaded from main UI.  I did 4 videos showing that:)  Have game on main UI, with /bin/ppsspp OR /bin/psp  Try to check the videos out so you can see how to properly run it:)

**Comment by mrTruch** [comment]
Sorry I forgot to tell you I did it from UI too. I saw the videos.

Not working. I’m going to watch them again but...

**Comment by KMFDManic** [comment]
Command line for one of the UI Games?

**Comment by mrTruch** [comment]
Now working, I had to transfer it 3 times (2 yesterdat and 1 again now), and just in case change /bin/psp to /bin/ppsspp


Sorry for doubting you.

**Comment by KMFDManic** [comment]
I did just revert it to ONLY /bin/ppsspp, to clean things up, just a little bit ago.

**Comment by mrTruch** [comment]
Ok. But if you revert it...why you said “Have game on main UI, with /bin/ppsspp OR /bin/psp” on first answer?
Just because of that...I did know I put the “correct” command...but it results it wasn’t.

You just forgot you had revert it at the moment you write it?
