### ISSUE TITLE
old mame2003 bios (neogeo) conflicts with fba2012 bios

### ISSUE THREAD

**Issue by shedeus** [KMFDManic/NESC-SNESC-Modifications#74]
I'm having an issue where the hmod "bios_neo_mame2003_req" conflicts with the hmod "bios_neo_mame2010+req" when running neo geo games.

What's happening is I install the mame2003_OLD bios to play neo geo games, etc, then when I load the mame2010_NEW bios to play fba2012 games, I can no longer play those older neo geo games.  

If I reinstall the mame2003_OLD bios over again, neo geo games start working again, but those fba2012 neo geo games are now broken.

Can't seem to figure this out.  It's like I can only have old neogeo using mame2003 or the new neo geo games using fba2012.

USB Host btw, running CE 1.01 with latest 2/7 km_hmod build, retroarch 1.7.0

**Comment by shedeus** [comment]
USB Host btw, running CE 1.01 with latest 2/7 km_hmod build

**Comment by KMFDManic** [comment]
You can't install both at same time.  You need to manually copy the bios to each game directory if wanting to multi use. I use Dummy Folder method, so I can use each Bios once.

**Comment by shedeus** [comment]
Can you help me understand the dummy method?  What does it do and what is the benefit?

**Comment by gingerbeardman** [comment]
Basically you just put your ROMs in a folder that is not linked to any game in hakchi, it's uploaded yourself though FTP. Then when you are in RetroArch you can browse to any of those ROMs and run them in any core, rather than everything being through the SNEC interface. That way you could have a SNESC that looks standard, but one of the games opens up retroarch and from there you can play anything. each person has their own preference how they set things up @shedeus 

also see https://www.youtube.com/watch?v=M_9zw_itRqE

**Comment by shedeus** [comment]
Oh I see, interesting.  Thanks for explaining that!

In regards to the conflicting neogeo.zip bios, it turns out I only have 6 games that need this new fba20162 bios (metal slug 4-5, sengoku 3, etc.).  I tried copying the new neogeo.zip bios (fba2012) into the folders of said games and re-exported, but they still would not run.  I double checked, and those bios files did copy over to the USB HOST drive.

It seems the old neo geo bios hmod still supercedes the new neo geo bios that I saved into the respective game folders.

Is there perhaps another way to manually insert the bios files into those specific games?  Could I unzip the contents of the new neo geo bios into the zip file of the game itself?  Just trying to figure out a way for retroarch to prioritize this new neogeo.zip bios instead of pulling the old one first...

**Comment by KMFDManic** [comment]
https://youtu.be/Oo7T2WdANJE

**Comment by shedeus** [comment]
Awesome, thanks for confirming my suspicion!  LOVING the 32gb of space  :D

**Comment by KMFDManic** [comment]
Let me know if you need anymore assistance:)
