### ISSUE TITLE
Retroarchs not working on non-USB host snes classic

### ISSUE THREAD

**Issue by bbaggins19** [KMFDManic/NESC-SNESC-Modifications#75]
Hello.  Thanks again for all the hard work.  I have an non-USB host snes classic.  My snes classic is modded, but none of the retroarch's in the 2/7/18 core set will work.  I even tried the hotfix, but they will not load up any nes games.  Thanks for any assistance.

**Comment by gingerbeardman** [comment]
you only need one retroarch hmod to run new games

then use the `/bin/nes` command line

**Comment by bbaggins19** [comment]
I have tried all the different retroarch's included in the 2/7/18 zip.  When I into any nes game, all I get is a black screen.  I reverted to _km_retroarch_170_1_14_18.hmod, and it works perfectly.  I checked the command lines, and it is as you stated with the /bin/nes command line.  The newer retroarchs's seem to work with USB host snes classics, but are not working correctly with snes classics that do not run USB host.

**Comment by gingerbeardman** [comment]
I don't use USB, and am running _km_retroarch_170_2_7_18.hmod, and my NES (well, 3 Japanese Famicom games) run just fine

So it must be something else?

**Comment by KMFDManic** [comment]
@bbaggins19 COMMANDS Folder in my Core Set

/bin/fceumm AND/OR /bin/nestopia

/bin/snes with one SNES9x Core installed  OR /bin/snes02 , etc for multiples:)  You can use find and replace tool in my Core Set to very easily change to the proper Commands:)

**Comment by bbaggins19** [comment]
I made sure the command lines where correct and this is what happens: When I click on a nes, snes, mame, or sega game, after a second, I pop right back out to the main menu.  I think I will just stay on the earlier _km_retroarch_170_2_7_18.hmod, which seems to work well for me.  Thanks everyone for your assistance. Since it's working well for everyone else, it's probably something that I'm doing wrong.

**Comment by KMFDManic** [comment]
Given you have the hotfix, you should still custom kernel flash, then resynch the games, making sure the command lines are appropriate.  You are also likely to have one too many HMODS installed.  If using Hakchi2 CE, power system on, and look at which hmods are installed, then uninstall the old ones, before copying new ones to user mods folder and installing them.  After changing command lines, you also have to CLOSE hakchi2, or the desktop files will not always save properly.  But, if you do things correctly, the command lines will work.  1.  Hotfix  2. Proper HMODS installed  3.  Proper Command Lines:)

**Comment by bbaggins19** [comment]
Thank you, it worked!!  It was operator error!  I wasn't closing out of hakchi2 after making changes!  Also all of my nes games were /bin/nes  instead of /bin/fceumm.  Once I did the hotfix, closed out and reopened, then changed the command lines  and then closed and reopened, everything is working great now.  Thanks again for your help!

**Comment by KMFDManic** [comment]
No problem:)  Anytime:)
