### ISSUE TITLE
[PX68K] mouse emulation using gamepad?

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#76]
Is it possible this can be added the same way it is in np2kai?

Let me know if I need to add the issue upstream.

**Comment by gingerbeardman** [comment]
OK so the emulator has an option Joy/Mouse in it's L2 menu.

But even when set to Mouse I cannot move the mouse cursor using my gamepad?

**Comment by gingerbeardman** [comment]
this build for an ARM handheld has some improvements made:
https://pyra-handheld.com/boards/threads/px68k-sharp-x68000-emulator.75797/

> The code has been slightly modified (diff sources in the PND). It use GLES 1.1 for the display (so it use Hardware scaling), but also use Texture Streaming, to still have maximum speed.
> 
> The JoyKey button as been redirected to {X} and {B} Pandora buttons.
> 
> Of course, you need ROMS file for the Emu to start. You need 2 files, to be put in appdata/px68k. It's cgrom.dat and one of iplrom.dat, iplromco.dat, iplrom30.dat or iplromxv.dat
> 
> This emu is all in Japanese...
> 
> Use F11 to immediatly quit or F12 for the System Menu.
> 
> History log
> 
> =========
> 
> Build 08
> 
> -----------
> 
> Fixed Scanlines
> Build 07
> 
> -----------
> 
> Added option (in F12 screen) for (faked) Scanlines
> Added cgrom.dat to the rom package.
> Build 06
> 
> -----------
> 
> Added option (in F12 screen) for Stretched anamorphic display
> Added option to copy iplromxv.dat rom if none is found
> Build 05
> 
> -----------
> 
> Files are sorted with case insentive
> Max files increased from 1000 to 4000
> Speed browse: use Right Shoulder {R} and DPad
> Build 04
> 
> -----------
> 
> The "StartDir" in config file as now an effect in the File selection dialog
> Files are sorted now
> Fine tuned default parameters
> Build 03
> 
> -----------
> 
> Cut too long file name to avoid messing the GUI
> Added Left/Right in file browser for 10 lines movement
> Added powervr.ini file to minimise tearing
> Build 02
> 
> -----------
> 
> Fixed mouse support
> Build 01
> 
> -----------
> 
> Initial build
> Adapted GLES code to Linux build
> Added Texture Streaming support
> Adapted to Pandora keymap

**Comment by KMFDManic** [comment]
I will test this on latest Build to see how things handle.  Which controller are you using?

**Comment by gingerbeardman** [comment]
Wii Classic Pro

**Comment by KMFDManic** [comment]
I have exact same controller as you, and using last posted np2kai in my Core Set, enabled joy2 mouse, and it works fine.  I changed speed to x5 so it wasn't too fast.  I would try again.  I also need to update it again, for next Update.

**Comment by gingerbeardman** [comment]
np2kai is NEC PC98 emulator. Joy2mouse works fine. 

px68k is Sharp X68000 emulator. Mouse doesn't work.

**Comment by gingerbeardman** [comment]
I think it's broken which is why it had to be fixed in the Pyra build linked above.

I can have a go at merging those changes?

**Comment by gingerbeardman** [comment]
source for pandora version is here: https://github.com/ptitSeb/px68k

**Comment by KMFDManic** [comment]
These are severely outdated, we'd definitely not want such outdated variants on the Mini NES/SNES.  It would be best to request such changes to be implemented into the much more current libretro fork for px68k so that current platforms can also benefit.  I try to keep within libretro since Cores are more compatible and optimal for use with RetroArch

**Comment by gingerbeardman** [comment]
I'll integrate some of these changes into the current libretro code.

**Comment by KMFDManic** [comment]
Yes, we definitely need changes like this to apply to current code, not code from 2-3 years ago:)   They have achieved quite a bit since then:)

**Comment by gingerbeardman** [comment]
Actually this core has not really changed much in that time, so I am almost done with my changes!

**Comment by KMFDManic** [comment]
Thanks again for putting so much effort and patience into helping make the Cores better!  We will keep in contact:)

**Comment by gingerbeardman** [comment]
Happy to be able to give back!
