### ISSUE TITLE
[PX68K] compressed roms should expand all files to cache rather than just first

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#77]
I have a game with 3 disks each of 1.2MB:

- `Aquales_1.dim`
- `Aquales_2.dim`
- `Aquales_3.dim`

I'd like to add them to hakchi as a .7z archive of 2.15MB

- `Aquales.7z`

That way I can set `StartDir=/var/cache` in `/system/keropi/config` so that when I select any extra disks the file browser starts where the files have been decompressed to.

However, the PX68K core only seems to decompress the first file in a .7z (or .zip) to `/var/cache/`.

**Comment by KMFDManic** [comment]
The Core is incapable of loading compressed files this way. They have always needed to be uncompressed.  RetroArch can manually select them from within Archives.  But, to mount with the Core, the way you want, they are required to be uncompressed.

**Comment by gingerbeardman** [comment]
Yes, I understand that. I just want it to expand the whole contents of the archive rather than just the first file in it.

**Comment by gingerbeardman** [comment]
Have reported this upstream

https://github.com/libretro/RetroArch/issues/2614#issuecomment-365925705
