### ISSUE TITLE
[BUG] extra quotes when using .m3u playlist to specify ROM files

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#79]
This probably belongs in hakchi or retroarch-clover, as they seem hardcoded to only deal with one ROM on the command line.

But I'd like to see support for specifying multiple "ROMs" on the command line for systems that can take multiple items of media (MSX, PC98, X68, etc)

**Comment by gingerbeardman** [comment]
So the MSX, PS1 and X68 cores support .m3u files, so I should be able to do:

Aquales.m3u
> Aquales_2_GAME.dim
> Aquales_3_SAVE.dim
> Aquales_1_INTRO.dim

To insert `Aquales_2_GAME.dim` into FDD0 and `Aquales_3_SAVE.dim` into FDD1.
`Aquales_1_INTRO.dim` is then available for the "disk swap" feature.

However, at least in PX68K, extra quotes are put around the path:

![2hy4kjbe 0uf](https://user-images.githubusercontent.com/49612/36236122-49558cc4-11ec-11e8-999b-822435e6f0a9.png)

**Comment by KMFDManic** [comment]
Did you add .m3u as a game?

**Comment by gingerbeardman** [comment]
Yes

**Comment by gingerbeardman** [comment]
This does not happen on macOS with this core, which confirms the bug is specific to SNESC setup.

macOS
![Uploading Screen Shot 2018-02-15 at 12.25.09.png…]()

**Comment by gingerbeardman** [comment]
`libretro.c`:
```c
291         sprintf((char*)argv, "px68k \"%s\"", disk_paths[0]);
292         if(disk_images > 1)
293         {
294            sprintf((char*)argv, "%s \"%s\"", argv, disk_paths[1]);
295         }
```

**Comment by KMFDManic** [comment]
Once I post my next Update, I will check into anything that we may be able to do, before this as a bug is reported Upstream.  It might just need done slightly differently for us.

**Comment by KMFDManic** [comment]
I see they were having issues Upstream with M3U and had already been working on it.  Not sure if you were the one that alerted them:)  But, it affects a half dozen other Systems, too:)  Let's hope this is quickly resolved.  Keep in contact with me on it:)

**Comment by alex5555** [comment]
Any news for this issue? It is still happening.

**Comment by gingerbeardman** [comment]
I'm working on some changes to px68k that will hopefully solve this! Soon 🙌

**Comment by alex5555** [comment]
Ok, thanks!
