### ISSUE TITLE
Snes9x core update

### ISSUE THREAD

**Issue by alexcom84** [KMFDManic/NESC-SNESC-Modifications#8]
Hi. Can you please update the Snes9x core to add support to the newly translated "Tengai Makyou Zero: Far East of Eden"? The rom boots fine on snes mini but can't pass the RTC test of the SPC7110.
 The code change for the working snes9x Windows version is here: http://www.mediafire.com/file/lxlf5dkj50mhlpq/CodeChangeTmz.rar

```
``<cartridge region="NTSC">
	<rom>
		<map mode='shadow' size='0x100000' address='00-0f:8000-ffff'/>
		<map mode='shadow' size='0x100000' address='80-bf:8000-ffff'/>
		<map mode='linear' size='0x100000' address='c0-cf:0000-ffff'/>
		<map mode='linear' offset='0x600000' address='40-4f:0000-ffff'/>
	</rom>
	<spc7110>
		<ram size='0x2000'>
			<map mode='linear' address='00:6000-7fff'/>
			<map mode='linear' address='30:6000-7fff'/>
		</ram>
		<mmio>
			<map address='00-3f:4800-483f'/>
			<map address='80-bf:4800-483f'/>
		</mmio>
		<mcu offset='0x100000'>
			<map address='d0-ff:0000-ffff' offset='0x100000' size='0x500000'/>
		</mcu>
		<dcu>
			<map address='50:0000-ffff'/>
		</dcu>
		<rtc>
			<map address='00-3f:4840-4842'/>
			<map address='80-bf:4840-4842'/>
		</rtc>
	</spc7110>
</cartridge>
```

**Comment by KMFDManic** [comment]
What is the name of the rom that needs patched?

**Comment by alexcom84** [comment]
Tengai Makyou Zero.  The translation is at: http://www.romhacking.net/translations/3243/
 It's the biggest translated release since the times of Star Ocean, Tales of Phantasia and Final Fantasy 5.
The snes cart has the SPC7110 chip that it is emulated by snes9x but it's real time clock is not supported. Because of that RTC, the game is not passing the initial self test. The mediafire link posted earlier is the modification done on the Windows version of snes9x to be able to start the rom correctly. If it might help you I have a compiled version to test it.

**Comment by KMFDManic** [comment]
Because this would truly benefit MANY, upon several different formats, Android, 3DS, NESC/SNESC, etc, I put in a request (with your excellent info) to the great people who work on the 9x Core on a daily basis!  Thanks so much for pointing out this great game to me!  With the coding added, thousands will be able to enjoy the game:)  This is definitely something of interest to RPG Fans:)  Thanks again, and we should have things going within a few days!

**Comment by alexcom84** [comment]
That's really great news! I am happy that you got in touch with the people working on 9x core.
 Looking forward for this updated snes9x core so I can play it on snes mini. Would be a shame to play it on PC. I even ordered the original snes cart to reprogram the translated rom on it! :)
 Thanks again!

**Comment by flavioliu** [comment]
Hi KMFDManic, thank you so much for your effort on bringing snes cores for our nes/snes classic. About snes 9x cores, all of them have a problem with speed Gonzales (snes) where the level freezes, after jumping on the switch. This problem only is solved on Higan/Bsnes. Could you please check if it is possible to port higan's libretto core into your project, so we can fully play Speed Gonzales? Thank you once again.

**Comment by flavioliu** [comment]
More info about the freeze on speed gonzales can be found here: https://floating.muncher.se/byuu/accuracy/

**Comment by KMFDManic** [comment]
Updated SNES9x to have RTC Support for Tengai Makyou Zero now, it will be in my next update:)  Those guys who work with 9x were quick to jump on the request:)

**Comment by KMFDManic** [comment]
@flavioliu Bsnes runs very slowwww on the Mini NES/SNES.  I can try seeing if anything has changed since last time I tried it.  It would be nicer if there was an actual fix that could be implemented into the SNES9X Code:)

**Comment by alexcom84** [comment]
@KMFDManic That's great! Thanks a lot for everything. I am happy that this will benefit everyone using retroarch cores. :)
