### ISSUE TITLE
I couldn't start mame and neo geo roms. Please help

### ISSUE THREAD

**Issue by alptolga** [KMFDManic/NESC-SNESC-Modifications#80]
I tried many hmod files  but I couldn't start neo geo and mame rom games. I always get c7 errors. I use latest hakcki2 ith snes classic.  I tried street fighter and final fight series roms and art of fighting 2

**Comment by gingerbeardman** [comment]
What is your setup?

Please list the hmods you have installed.

**Comment by alptolga** [comment]
snes classic + hackchi 2.21f. I also added the qsound and neogeo to the games folders
Here are the screenshot of my configs.
![1](https://user-images.githubusercontent.com/23561317/36259194-76e985d2-126e-11e8-91d7-ab953120ba6b.png)
![2](https://user-images.githubusercontent.com/23561317/36259195-770aed4e-126e-11e8-8cfb-54859e422f5a.png)

**Comment by alptolga** [comment]
I tried many hmod files but I couldn't be successfull. Those are the last hmods that I tried.

**Comment by gingerbeardman** [comment]
OK, it seems you have a mix of hmods. They should all start with _km 

So
- remove all those hmods
- tidy your computer to remove the wrong hmods
- download the latest release
- install just those necessary (only one mame bios for the version of it that you choose)
again: https://github.com/KMFDManic/NESC-SNESC-Modifications/releases

**Comment by alptolga** [comment]
I still couldn't start the games. I got c7 error. I put the neogeo rom archive to art of fighting directory. and I just installed km fbalpha2012 neogeo 10 24 17 and also Ho can I understand the mame games version to use with right hmod ?

**Comment by gingerbeardman** [comment]
Ah, you need one of the retroarch hmods also (it's like a parent hmod)

Watch this video: https://www.youtube.com/watch?v=NprN2WFYl9k

Each version of MAME has a set of ROMs (game and BIOS) that are meant for it. You need to match them. You can find them at archive.org

Also, you should use hakchi2CE: https://github.com/TeamShinkansen/hakchi2/releases

**Comment by alptolga** [comment]
I tried the final fight rom from that link.
https://archive.org/download/MAME2003_Reference_Set_MAME0.78_ROMs_CHDs_Samples/roms/
Here is the game list
https://docs.google.com/spreadsheets/d/1LP1MELCvcxu7TfiowF_0ZuvRVEMqlfQyTVetnOJvuJc/edit#gid=1744967714
Please Can you tell me the right hmod?

**Comment by gingerbeardman** [comment]
Let's just try with final fight:

_km_retroarch_170_2_10_18.hmod
_km_bios_neo_mame2003_req.hmod
_km_mame2003_ffight_1_9_18.hmod

You should join the Nintendo Classics discord for instant help: https://discordapp.com/invite/42g2NUH

**Comment by alptolga** [comment]
Thank you very much for your helps.

**Comment by alptolga** [comment]
I used many devices, made many mods but this is really a headache. There is no proper information, many files...

**Comment by gingerbeardman** [comment]
It's easy but you need to understand what the files are so you have confidence in what you are doing. 

Did you watch the video?

**Comment by KMFDManic** [comment]
You using USB-HOST, or Non-USB-HOST @alptolga ?

@gingerbeardman Thanks for your continued assistance in helping those solve issues on my Github:)  You are an incredible friend:)

**Comment by alptolga** [comment]
Sorry for late reply. It works with hakchi2 CE v1.0.1 - Bugfix edition! Thank you verymuch with your helps.
