### ISSUE TITLE
_km_glupen64_6_26_17.hmod on snes classic and _km_picodrive_1_23_18.hmod on nes classic

### ISSUE THREAD

**Issue by bbaggins19** [KMFDManic/NESC-SNESC-Modifications#82]
Hello! Thanks for the update.  When using the snes classic in non usb-host mode, and using the _km_retroarch_141_extreme_2_15_18.hmod, the _km_glupen64_6_26_17.hmod will not allow changes to button configurations under settings, input, input user binds.  I tried to remap the L1 button.   I have it set to save configuration upon exit, and even went into quick menu, save game overrides, or save core overrides.  But when I exit the game, and go back in, the button configuration is not saved.  
Also, while using the _km_retroarch_141_extreme_2_15_18.hmod on the nes classic, in non-usb host mode,  the _km_picodrive_1_23_18.hmod will not load up any games.  I tried all 3 variants of the retroarch extremes included in the 2/15/18 update.  As far as games,  I tried Afterburner, , Space Harrier, and WWF Wrestlemania. I have it set for /bin/32x in hakchi2 and have also tried /bin/ picodrive.  Yet, on the snes classic, this works flawlessly and the problem is just on the nes classic. Thanks for any input and thanks again for your tireless work!

**Comment by bbaggins19** [comment]
I am using hakchi2 v2.21f.   For the 1st part of my problem, _km_glupen64_6_26_17.hmod will not save net input configurations on the snes classic.  For the 2nd part of my problem, on the nes classic, no sega 32x will work.  The full command lines are /bin/32x /usr/share/games/nes/kachikachi/CLV-Z-DWYDW/After_Burner_Complete_(32X).7z    I also tried it with also with replacing /bin/32x with bin/picodrive.

**Comment by KMFDManic** [comment]
You need to apply the hotfix to hakchi2.  It is in a folder in my set, as well as shown in a video.

https://youtu.be/KThTOZidDVM

If you have issues with input configs, go to Controls, set them, then save as mapper.  This mapper can easily be loaded.  You can additionally try 1.7.0 ffmpeg or another RetroArch to see if inputs are more reliable.  I included several so people have options. Hope that helps

**Comment by bbaggins19** [comment]
The 1.7.0 ffmpeg  and reapplication of the hotfix does fix my second problem with 32x loading up on the nes classic.  Thanks for your assistance.

**Comment by KMFDManic** [comment]
Best to save as mappers, as that is the proper way to ensure controls get saved:)  Let me know if you need anymore assistance:)
