### ISSUE TITLE
2 sets of hmods ?

### ISSUE THREAD

**Issue by DecanFrost** [KMFDManic/NESC-SNESC-Modifications#83]
Thanks for the hard work guyes....  just a question  newest update states 2 sets of hmods now in the archive ... i cant seem to find the other set. just seeing the main set of hmods

**Comment by KMFDManic** [comment]
I've only had one set:)

https://github.com/KMFDManic/NESC-SNESC-Modifications/releases

**Comment by gingerbeardman** [comment]
> Lo and behold, here is the Update:) RetroArch had to be done a very special way. There are now 2 Sets! One is Default Settings, for those who want completely untainted RetroArchs to play around with:) The other set, the extreme variant, has all of my optimizations for PSP, N64, System Wide Performance Boosts, and so on!

**Comment by KMFDManic** [comment]
Didn't even think that was what he was referring to:)  Hehe:)

**Comment by DecanFrost** [comment]
Post clearly says 2 sets. One with original settings and one with performance settings.  Not one set with different options or profiles  but 2 different sets.


________________________________

**Comment by KMFDManic** [comment]
Not two sets of HMODS, however.  Two sets of RetroArchs, one with standard, default settings...the other with Optimized Settings, as I have been showcasing in my N64/PSP, etc Performance Upgrade Videos.  Sorry for any confusion.  But, we both took what each other said literally:)  You will see the Extreme ones right next to the Standard ones in the set.  Hope that makes things easier:)

**Comment by DecanFrost** [comment]
Ok I load the reteoarch 1.7 extreme hmod correct. Now in the post it talks about the mame system 32 variant..  is there an extrmem version of that or is it just stating mame 2003 system 32 vs just the one labeled as mame 2003
?
________________________________

**Comment by KMFDManic** [comment]
Sorry I did not clarify that.  I did do a video on MAME 2003, as well.  I guess this also makes what I said about one set of HMODS partially untrue:)  Anyways, COMMANDS Folder in my Core Set shows the appropriate Command lines for the MAME 2003 HMODS.  You can install ONE at a time, and use /bin/mame2003  OR have 2-3 installed at a time, and must use the secondary command lines to avoid conflicts.  You, of course, would also need the appropriate rom sets to run these.  Also, make sure you are using a hakchi with hotfix applied.  You can also apply it, yourself, from the folder in my set, if it doesn't already have it.  Let me know if you need anymore help:)

https://www.youtube.com/watch?v=PAbJYsFx5M0&t=2s

**Comment by KMFDManic** [comment]
@DecanFrost Feel free to ask me anymore questions, as needed.  RetroArch will be slightly complicated for a little longer, til things are better consolidated:)

**Comment by DecanFrost** [comment]
Thanks for the info..  I do have an other question..

If i have the cores installed on my snes from let say one of the Feb 2018 updates you did and today I download the latest set form march , if i install the cores like fba2016 even though the file name is different does it still install internally the same so it over rights the older version  ???

**Comment by KMFDManic** [comment]
Only thing you do by installing NEW Cores on top of OLD Cores is create potential conflicts.  You should always uninstall the old ones first:)

**Comment by DecanFrost** [comment]
i hate running the uninstall and then having to add everything even the usb hmod and tiny7z,, gotta be an easier way

**Comment by KMFDManic** [comment]
Hakchi2 CE:)  Linked to in my Core Set

**Comment by DecanFrost** [comment]
one last question....  where can i find your mame samples pack,,

KMFDManic-mame_samples_pack(10-16-17)  or newer one..  I have searched and could not find it

**Comment by DecanFrost** [comment]
I installed the sample files i do have using the method listed in your video, for the different mame and fba cores and they are still not working
