### ISSUE TITLE
Random Cores Problems

### ISSUE THREAD

**Issue by GenralTOW** [KMFDManic/NESC-SNESC-Modifications#84]
Hi,

I tried to add ZX Spectrum Games to my SNES Mini, but when I try to start them, black screen and goes back to menu.

Core used : _km_fuse_1_25_18

Path : /bin/zx /var/games/CLV...

Any idea ?

Same issue with 64DD roms...

Core used : _km_mupen64plus_2_18_18

Path : /bin/mupen /var/games/CLV...

Thanks for your help ! :)

**Comment by gingerbeardman** [comment]
you need a main/parent retroarch core along with the fuse/mupen cores.

**Comment by KMFDManic** [comment]
@GenralTOW Which hakchi version you using?  And, yes, you need a RetroArch installed:)

**Comment by KMFDManic** [comment]
Do you have video splash screen installed?  And, what exact command lines for games that are not running?  Video splash screen has been the common denominator for broken cores, lately.

**Comment by GenralTOW** [comment]
Video splash screen ? No I don't think, I only have the "Hakchi" with "knock knock" on the upper left.

Here is a sample for ZX Spectrum games : 

/bin/zx /var/games/CLV-Z-QRAVY/Subbuteo_The_Computer_Game_Europe_.ipf.7z

Any idea ?

One more question, how do I choose for a N64 game to start with Glupen instead of Mupen for example (If both cores are installed), wich command line do I use ? How ?

**Comment by gingerbeardman** [comment]
@GenralTOW the FUSE ZX Spectrum emulator does not support `.ipf` files. 

It supports: `.tzx`, `.tap`, `.z80`, `.rzx`, `.scl`, `.trd`

For N64 you can use `/bin/glupen` and `/bin/mupen` to run one or the other emulator.

https://www.reddit.com/r/miniSNESmods/comments/7tccrf/list_of_cores_from_kmfdmanic_set_their_command/

**Comment by GenralTOW** [comment]
gingerbeardman> Oh thanks, I'm not lucky since EVERY games I downloaded are... ipf. But now I know what is wrong, I'll do my best for it to work.

Oh and, for N64 that would be : 

/bin/n64 /var/games/CLV-6-MMITS/Mario_Kart_64_Europe_.n64.7z

-- To : 

/bin/glupen/var/games/CLV-6-MMITS/Mario_Kart_64_Europe_.n64.7z for example ?

In the original command line, there is a space between "64" and "/", is it important ?

Really, thank you for your help, I'm new in this kind of things... But I will learn ! :)

(I'm french, sorry for my bad english)

**Comment by gingerbeardman** [comment]
Yes you need the space

`/bin/glupen` this part is the application to run
`/var/games/CLV-6-MMITS/Mario_Kart_64_Europe_.n64.7z` this part is the full path to the game

Ne rien!

**Comment by GenralTOW** [comment]
Your answer is perfect, and with your link on reddit, I learned A LOT of things, now I think I'm going to change a lot too in Hakchi.

I have one last question (for now). Do I have to change the command line for each games or is there a way to configure Retroarch to use "Gambate core" for GB, GBC, "mGBA core" for GBA roms etc... (I have more than 3000 games so it would be long to change every command line)...

Thanks, again...

**Comment by gingerbeardman** [comment]
Yikes! It would take a lifetime to play that many games 😮 

Anyway, Hakchi2 tries its best to figure out what `/bin/` to put on the command line, but if you load unsupported game formats it will not get it correct. 

Using hakchi, it will be hard work. Maybe impossible.

But you can use a Search and Replace application to do it the command lines are stored in the `.desktop` files. Take a look! I recommend this app: https://www.den4b.com/products/renamer

**Comment by gingerbeardman** [comment]
@GenralTOW also see: https://github.com/TeamShinkansen/hakchi2/issues/30#issuecomment-367053008

**Comment by GenralTOW** [comment]
Yeah I know it would take time, it's more fun to make it work, instead of play (At the moment).

Your last answer is EXACTLY what I needed...

You are my new God.

"Find and Replace" is a must have for every Hakchi user I think. Thanks a lot ! :)

**Comment by KMFDManic** [comment]
@GenralTOW   J'ai l'intention de faire mes fichiers readme tous en français car j'ai tellement d'amis français dans la scène de modding :) N'hésitez pas à me demander autre chose, quand vous le voulez, mon ami :)

@gingerbeardman Thanks as always!!!

**Comment by GenralTOW** [comment]
@KMFDManic Salut, ah clairement ça serait sympa, surtout pour un mec comme moi qui comprend rien à rien ah ah ! Merci encore c'est super, bon boulot ! :)
