### ISSUE TITLE
Nestopia not saving for FDS games

### ISSUE THREAD

**Issue by agufungus** [KMFDManic/NESC-SNESC-Modifications#89]
Hello, I remember this was an issue back in retroarch-clover ( [https://github.com/ClusterM/retroarch-clover/issues/23](url) ), and after playing and trying to save in Yume Koujou Doki Doki Panic, it seems that this is still an issue with this version of Retroarch (_km_retroarch_171_xtreme_2_26_18, using Nestopia). In case you're asking, I'm using Hakchi2 CE 1.1.0. Am I doing something wrong? I think it's supposed to save after clearing a world, or at least a stage. It is it because the ROM is in a .7z file?

**Comment by KMFDManic** [comment]
Try saving with either ffmpeg variant of RetroArch in my set.  And, let me know.

**Comment by agufungus** [comment]
OK, I tried it, and nope, still no save.

**Comment by KMFDManic** [comment]
How many games per folder and have you tried it on a known to save game, such as Zelda, and/or used a suspend state?  Try with fceumm, by chance?  Your command line for the game?

**Comment by agufungus** [comment]
OK, this is what I found: I have 36 games in the NES folder, three of which are FDS games, all loaded using bin/nestopia (using bin/nes instead defaults me to fceumm for some reason). I tried saving in Zelda with Nestopia, but it gives me no save. I tried with fceumm, and still no save. Here are the command lines I used:

/bin/nestopia /var/games/CLV-I-IXMSL/Yume_Koujou_Doki_Doki_Panic_Japan_.fds.7z
/bin/nes /var/games/CLV-I-IXMSL/Yume_Koujou_Doki_Doki_Panic_Japan_.fds.7z
/bin/nestopia /var/games/CLV-I-ZZSQC/Zelda_no_Densetsu_The_Hyrule_Fantasy_Japan_v1.1_.fds.7z
/bin/nes /var/games/CLV-I-ZZSQC/Zelda_no_Densetsu_The_Hyrule_Fantasy_Japan_v1.1_.fds.7z

Save states do work, however, but savegames don't.

**Comment by KMFDManic** [comment]
USB-HOST, or Non?

**Comment by agufungus** [comment]
Using USB-HOST. Saving works for the other games I have (SNES, NES, Genesis), but not for FDS.

**Comment by KMFDManic** [comment]
You using a /hakchi/saves folder?  And, since you are on CE, try this with non-USB, too.

**Comment by agufungus** [comment]
OK, already tried with non-USB. Still no save.

**Comment by KMFDManic** [comment]
I will try testing it, personally, tomorrow.  Thanks for the test results.

**Comment by KMFDManic** [comment]
For the record, the coding points to .fds as extension.  Back then, when it was implemented as a fix, NES/FDS Games, as compressed games, was not an option.  The coding is all intact, and the fix is there.  I didn't test it, yet.  But, basically, it looks for Nestopia as the Core, and FDS as the extension.  So, if you get to it before me, try it "uncompressed" with Nestopia:)  Most must be so reliant on Suspend States, they have not realized this:)  Good catch.

**Comment by KMFDManic** [comment]
If you have further tested this any, please let me know.  I know it is not exactly high priority.  But, it would be nice to fix it, if at all possible.  The original coding was for uncompressed FDS Games running on NESC.  Most are running on SNESC, now, with compressed Games:)  Keep me posted.  I will close the issue for now, but will still follow your responses as well as keep it on my agenda of things to hopefully be able to fix!
