### ISSUE TITLE
Save State icons

### ISSUE THREAD

**Issue by bbaggins19** [KMFDManic/NESC-SNESC-Modifications#90]
Hello, when using any of the 2/27/18 retroarch's on the NES classic, non-usb mode, I keep getting blank save states, no matter what core I am using.  Though the save states do work.  Is there a fix?  Thanks for any assistance.  And thanks for your great work!
![20180302_073604](https://user-images.githubusercontent.com/35228501/36899511-6ca18a18-1ded-11e8-8ed6-ba8c4d162f75.jpg)

**Comment by KMFDManic** [comment]
Which hakchi are you using?  And, do you close hakchi after adding games?  Then, reopen, then synch?

**Comment by bbaggins19** [comment]
I am using hakchi2 v2.30 and I did close hakchi after adding games and have resynch'd.  Any other advice for me to try?  Thanks for your assist.

**Comment by KMFDManic** [comment]
Hakchi2.3 conflicts with my RetroArchs.  You will need to use Hakchi2 CE, as you are likely to have other issues too, due to different busybox being used.  In the future, things will change.  Just not this moment:)

**Comment by bbaggins19** [comment]
I installed the latest Hackchi2 CE after restoring original dump, flashing custom kernel, uploading games, and installing hdmods to my nes classic.  This is the screen I get.  I doesn't show my games and wont allow me to do any navigation.
![20180302_125656](https://user-images.githubusercontent.com/35228501/36913972-ad0efe24-1e19-11e8-88fc-243035e0ed31.jpg)

**Comment by KMFDManic** [comment]
Did you use same games, or add them again?  Some were having issues with migrating games from CE to 2.3, and ended up having to completely Re-Add Many Games, before they worked.  Even if you didn't re-add them, you could still potentially fix things by fixing bad command lines.  Conflicts DO happen when jumping into a different program, at times:)  So, expect them!  I will do what I can to help you restore your former integrity, however.

So, try this.  Have fresh install of Hakchi2 CE, Copy JUST the dump folder from previous Hakchi to it.  Uninstall Kernel, Flash Original, Flash Custom, Disable Folders, And, uncheck Default Games, then add just a few Random SNES Games.  CLOSE Hakchi2 CE, Reopen, Synch.  Let me know:)  Then, we will go from there.

**Comment by KMFDManic** [comment]
You have used CE in the past, correct?  And, be sure to follow the steps I mentioned in the previous message.

**Comment by bbaggins19** [comment]
I have never used CE before.

**Comment by KMFDManic** [comment]
Did you try the steps I just outlined?  Also, you can try one other thing.  In my Core Set is 2.21e Debug:)  Try that out as a test back-up plan.  Do not get frustrated.  Many go through what you are going through!  You will be back in action, soon:)

**Comment by bbaggins19** [comment]
Fixed!!!  Thanks!  I just had to select uninstall, while in hakchi ce, so that all traces of hakchi were removed.  This was because when I originally installed, i didn't have any folders, so everything was together and not showing.  Once I uninstalled, i reinstalled custom kernel, transferred games, and installed hdmods!  Now it works great!  Thank you so much for taking the time to help!!  Thanks!!!

**Comment by KMFDManic** [comment]
Crt filter hack is outdated. I may need to update it since so many changes have been made since the time of the original hack.

**Comment by bbaggins19** [comment]
Ok,  Thanks again for your help!  We all appreciate all the hard work you do, even though you probably mostly hear from us just when there is a problem.  If everyone took the time to say thanks, there would be long threads of everyone showing appreciation for you.  But thanks again for everything!!

**Comment by KMFDManic** [comment]
You are welcome:)  I will check into the CRT Filter Hack:)  You will see it show up in Release Notes if and when I am able to look into it and fix it to work with Current Set-Ups Properly:)  Glad all has worked out!
