### ISSUE TITLE
Arcade titles from publisher IGS (China) don't run in mame or fba

### ISSUE THREAD

**Issue by shedeus** [KMFDManic/NESC-SNESC-Modifications#91]
* hakchi2 version: 1.10 CE 
  * retroarch: 1.71 standard / USB HOST
  * hmods: mame2003 (merged), fbalpha2012/2016 (latest 2/27 build)
  
Any arcade games from publisher IGS (China) don't run at all (ie Demon Front, Knights of Valour, etc.).  Is this an encryption issue like IREM used to be?

**Comment by KMFDManic** [comment]
They won't run without Bios  You can use Bios HMOD or merge the Bios per the method in my NEO-GEO Bypass Video

**Comment by shedeus** [comment]
I have "_km_bios_neo_mame2003_req" already installed.  Are you telling me that if I run the IGS games with the "new" neogeo bios, everything should be a-ok?

**Comment by KMFDManic** [comment]
These are not neo geo bios.  I work tonight.  But, I can better help you tomorrow.

**Comment by shedeus** [comment]
Thank you kindly!!

**Comment by KMFDManic** [comment]
Anyways, as far as running the IGS Games, you'd need to follow my NEO-GEO Bypass Video for best results, as far as merging or running them via Dummy Folder.  For NON-USB-HOST, using the Bios HMOD, and copying the igs bios into the root of the directory would help.  Which game/s are you attempting to run?  Luckily, most games run without need for Bios.  You just happened upon one of several that require them:)

**Comment by KMFDManic** [comment]
If able to use a Dummy Folder, and try loading these exact games with FBA 2016, MAME 2010, as well.  Rom Sets often work between Cores.  If not Dummy, test with them, anyways.  Be sure to try MAME 2014, as a final test.  Demon Front definitely works.  But, I recall it being a little slow in my test.  It would likely run a little better with Xtreme Add-On.  Gunforce 1 and 2 are like Demon Front and both run great on the MAME 2003 I recently Updated.  Knights of Valour may have no sound.  Keep me posted.

**Comment by shedeus** [comment]
Not having much luck but I'll keep trying!  Maybe I need to pull the files from a different romset.  Thanks for your help!

**Comment by KMFDManic** [comment]
This is an entirely different issue than we first realized.  I will likely do a video about it today.  It will show how to properly run PGM Games.  Don't go out of your way, as you won't be able to run them until I show you how:)  But, your Issue got me to check into things, and I pinpointed the conflict extremely fast:)

**Comment by shedeus** [comment]
In Kyland we trust lol

**Comment by KMFDManic** [comment]
Successfully got Demon Front running, at a very nice speed.  I will get a video posted by tomorrow:)  I will add the tweaks to run it faster in my Core Set Update.

**Comment by KMFDManic** [comment]
https://youtu.be/vVMznvqbezk

**Comment by shedeus** [comment]
HELL YEAH!!!  I'm playing DF right now hahaha
I can't believe it was as simple as changing to a child rom.  Why didn't I ever think to try that?

THanks so much man!!
