### ISSUE TITLE
PS1 games not working + Crash

### ISSUE THREAD

**Issue by GenralTOW** [KMFDManic/NESC-SNESC-Modifications#92]
Hi, here is my issue : 

  * hakchi2 version: 2.30
  * retroarch: _km_retroarch_171_standard_xtreme_2_27_18
  * hmods: _km_pcsx_rearmed_neon_1_28_18
 
When I try to load any PS1 game, it's not working and resulting in SNES Mini crash.

Changed "/bin /" to "/psx /" for every games.
  
Observed Results:

Black screen after a long loading time. Black screen = Start + Select not working to access Retroarch settings, and when I try to turn SNES Mini OFF, nothing happens. Still black screen. I have to disconnect the Power Source manually.

Any idea ? Bios missing ? (If this is the case, I don't know how to add them, I used your pack)
Compressed game ?

Thanks !

**Comment by gingerbeardman** [comment]
Use Hakchi2CE

**Comment by GenralTOW** [comment]
I will try to re-install each HMOD with Hakchi2CE. Waiting for results.

**Comment by GenralTOW** [comment]
Exactly the same problem. Nothing less, nothing more.

Hakchi2CE or Hakchi2 2.30.

**Comment by GenralTOW** [comment]
I'm trying to totaly reflash the SNES Mini and re-install everything with the last KMFD Pack, using Hakchi2 CE.

**Comment by GenralTOW** [comment]
Only one game is working now, Sim City 2000. But slowly (Game size : 32Mb).

Tryed with C&C, Pandemonium, Spyro, Armored Core and others... Crash.

Game Size problem ?

**Comment by KMFDManic** [comment]
You basically created a conflict by using hakchi2.3 with a RetroArch that was not "attuned" to it.  You will need to use Hakchi2 CE, uninstall Kernel, Flash Custom Kernel, and Reinstall HMODS.  Additionally, it would appear you may have not "properly" ripped some of these Games.  You need to use "smallest size video" option on Games that have issues when removing Videos/Audio Entirely.

**Comment by gingerbeardman** [comment]
Your options on SNESC: 
1. Use USB mod to get extra storage space, then you can use full PS1 ISOs. 
2. Use internal storage and ripped PS1 ISOs.

**Comment by KMFDManic** [comment]
@GenralTOW You would, for absolute sure, need USB-HOST to run full Command and Conquer.  Many games can be ripped of audio+video to work on Non-USB-HOST.  Ridge Racer is by far the best example of an easy one to do.

**Comment by GenralTOW** [comment]
Well, sorry. I did not mention that I am actually trying to do it with USB-Host... 64Gb key.

I will try again soon, not home for 3 days. But It's very strange.

**Comment by GenralTOW** [comment]
I tryed again before leaving home (Was impatient), waited in front of a black screen for 3 minutes (My key blinked for some seconds and stoped loading). Again, when I try to power off the system, It's not working and I have to manually remove the power cable.

I think there is a problem, maybe the Key itself ? Will try again in 3 days. Thanks guys.

**Comment by KMFDManic** [comment]
@GenralTOW There is only one true path you can go to get things going properly.

1.  use Hakchi2 CE
2.  Uninstall Kernel
3.  Flash Original Kernel
4.  Reinstall HMODS - RetroArch 1.71+PCSX ReArmed Neon
5.  Don't Use USB-HOST, initially
6.  Instead, test 1 single PS1 Game on Non-USB-HOST:)  

Keep me posted, and we will go from there:)

**Comment by GenralTOW** [comment]
Hi, I'm back !

I did all you asked, and tried with a 56Mb game, Cool Boarder 4. Same result, SNES Mini crash with black screen.

Also tested with only Crash Bash 65Mb, same problem.

I will try to uncompress games, since the option is checked by default. I need to find a PS1 game, uncompressed but small enough for the internal memory.

Wait for results, and thanks for your help !

**Comment by gingerbeardman** [comment]
I play Jarinko Chie Hanafuda, 6MB(!) compressed Japanese PS1 game. Most ISO of it online didn't work, I ripped my own disc and it works!

**Comment by GenralTOW** [comment]
Hi gingerbeardman,

I was suspecting ISO games that I found online, I'm trying different things (Using the same game from different website that I will not name), sometime, compressed and uncompressed size is different from a site to another.

I tryed different original formats, differents PCSX natively supported formats, tryed to convert some games with Ultra ISO etc...

Always the same problem. Some games (Listed above) still works, USB and NON-USB Host mode, but others still don't work, no mater what I do.

I think I will now try with different  PSX HMODS (Olds and new, and from another developper) just to be sure of what is going on.

And finally, maybe you are right about the ripping problem. I do have a lot of PS1 games, I think that I will test to ripp my own games and see if I've got better results ! :)

**Comment by gingerbeardman** [comment]
Don't waste your time trying random ISO you find online. Only try proven sources. 

Start with your own! Good luck

**Comment by KMFDManic** [comment]
@GenralTOW The Pcsx rearmed neon in my set is absolutely fine. The issues you are having have absolutely nothing to do with the hmod.  Send me a message on Reddit, under the name MDFMKanic  I will fix your user end errors:)  Issue closed, will personally help you on Reddit.
