### ISSUE TITLE
NOT an issue -- You're killing it with these f*ckin updates!!  I LOVE IT DUDE!!  :thumbs up:

### ISSUE THREAD

**Issue by shedeus** [KMFDManic/NESC-SNESC-Modifications#93]

**Comment by KMFDManic** [comment]
Thanks so much for the appreciative ISSUE:)  Hope you got some IGS Games running, man!

**Comment by shedeus** [comment]
nope.  Screw chinese arcade games lol

**Comment by KMFDManic** [comment]
Giving up:)  I will throw up a video of them in action and you might change your mind:)  Once I do, I will pass the appropriate set-up to you.

**Comment by shedeus** [comment]
Honestly, Demon Front is the only gem in the bunch imo.  I love Metal Slug and this was the only clone that really hung with the original gangster.  I mean Gun Force 2 was cute, but Demon Front is everybit as good as metal slug, dare I say even better! :P

**Comment by KMFDManic** [comment]
I will reconfirm what runs Demon Front.  Last I played it was a couple months ago.

**Comment by KMFDManic** [comment]
I got other PGM Games running in a quick test. I will try Demon Front tomorrow.

**Comment by shedeus** [comment]
On second thought, I haven't tried to source different versions of the bios.  Maybe I'm just using the wrong bios.  I'll have to do more googling...
