### ISSUE TITLE
Yabause stopped working on the last update.

### ISSUE THREAD

**Issue by Oradainer** [KMFDManic/NESC-SNESC-Modifications#94]
I only play one Saturn game due to low fps, but it stopped working altogether with the 3/5 update.

  * hakchi2 version: CE v1.1.0
  * retroarch: 171_3_5_18
  * hmods: yabause, mgba, stella, pce, genesis plus, mame2000, mame 2003, mame 2010, mupen64
  
#### Steps to reproduce:

  1. Install 3_5_18. Dropping back to the old retroarch seems to fix it.
_____
  2. _____
  3. _____
  
#### Observed Results:

Crashes back to dummy folder

To be honest, saturn is probably too much for the snes classic, but I'd love to just get dragon force playable. God I love that game...

**Comment by KMFDManic** [comment]
Command line for your Saturn Game?  I will retest if need be once home.  But, last time I checked, it was still working fine.

**Comment by KMFDManic** [comment]
Oh, I mentioned this in a previous video. You can only load one Saturn Game at a time in Dummy Folder.  Any game after that will always crash.  After that, you need to exit to main gui, and get back in.  You can also run from main gui, with /bin/yabause

**Comment by KMFDManic** [comment]
I can confirm this works flawlessly, as the Core has not at all changed in the last few releases.  Issue Closed.  Run Saturn games from main Gui using /bin/yabause  OR, load Core, and run ONE single Saturn game at a time, dummy folder wise.  Make sure they are NOT 7z compressed:)
