### ISSUE TITLE
Games no longer listed correctly in alphabetical order in SNES classic game launch GUI with 3/5 hmod update

### ISSUE THREAD

**Issue by shedeus** [KMFDManic/NESC-SNESC-Modifications#95]
* hakchi2 version: 1.10 CE / USB Host
  * retroarch: 1.71 standard 3_5_18
  * hmods: N/A

Sorting seems to have broken for me with the last 3/5 hmod update.  Games are no longer listed correctly in alphabetical order across all folders in SNES game launch GUI, despite being listed correctly in alphabetical order in hakchi.  Am I the only one seeing this?

**Comment by gingerbeardman** [comment]
You can change sort order by pressing SELECT

**Comment by shedeus** [comment]
All this time, I did NOT know that was a feature haha.  Thank you!
