### ISSUE TITLE
SNES classic: OEM bordersnot visible in retroarch cores, but works fine with canoe (SNES)

### ISSUE THREAD

**Issue by shedeus** [KMFDManic/NESC-SNESC-Modifications#99]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.10 CE / USB HOST / SNES classic
  * retroarch used (filename): _km_retroarch_171_xtreme_3_13_18.hmod
  * hmod(s) used by the game you are having problens with (filenames): all cores from 3/13 hmod build

Kyland! None of the OEM borders are displayed with any cores (FCEumm, SNES, mednafen, genesis plus GX, mame2003, fbalpha2012, etc.) except they are visible when playing SNES games with canoe.

Other than that, runs like a dream.  Great job my friend!

**Comment by bankaiprimera** [comment]
Yes I noticed this as well after updating to latest Hakchi & latest KMFDManic cores.

**Comment by KMFDManic** [comment]
There are a few kinks to iron out, and will get them fixed up for next release:)  Thanks for the Issue and feedback, both of you.

**Comment by KMFDManic** [comment]
https://www.reddit.com/r/miniSNESmods/comments/84r0xk/openbor_test_retroarch_aspect_fixes_explained/

Let me know if you still need any help:)

**Comment by shedeus** [comment]
Hey Kyland, canoe borders definitely work when you choose 4:3 mode and enable in onscreen display in Retroarch menu.  But if you choose CRT Filter 4:3 mode, borders are still invisible, despite menu options enabling overlay.  Can you please take a look?  Many thanks in advance!

**Comment by KMFDManic** [comment]
They work in CRT too, toggle enable off then on, resume, and it should show.  If not, exit game, re-enter, and redo.  I had them all working in CRT and 4:3.  Let me know.

**Comment by bankaiprimera** [comment]
I've tried disabling then enabling the overlays in RA (tried saving the setting in a selected emu core and in the RA main-menu), but the SNES classic overlay only seems to work with the 4:3 mode - _not_ the CRT mode selected.

**Comment by KMFDManic** [comment]
I will do a test example of it with CRT today.

**Comment by shedeus** [comment]
thanks for confirming bp!  I was like wtf am I doing wrong hahaha

**Comment by KMFDManic** [comment]
@shedeus @bankaiprimera There was definitely a bug related to CRT.  But, it should be OK, when I release today:)

**Comment by bankaiprimera** [comment]
Thanks @KMFDManic I will check it out soon. Are the canoe border _enabled by default_, or do I need to press L1 every time I boot up a game? Would be best great to have default = borders on.

**Comment by KMFDManic** [comment]
@bankaiprimera I will be posting a bugfix related to NESC/SNESC, later today.  It involves an issue that has always existed, and relates to Canoe Borders, as well.  If you use L1, the border should stay on.  R1 will disable it.  It actually amends the desktop file OF the games, to code in --bezel-mode on/off.  It is a very very nice feature, and very effective.  But, it will be better realized once I post the bugfix later today:)  Thanks, as always, for your patience and feedback!

**Comment by bankaiprimera** [comment]
@KMFDmanic thank YOU man, for all your work :)
I noticed the borders work now, but aren't animated unfortunately.. just a static image. I love the “color changing” canoe border, so I hope this can be fixed.

**Comment by KMFDManic** [comment]
@bankaiprimera color change border with Canoe run Games?

**Comment by bankaiprimera** [comment]
Yes SNES games with canoe have the animated border.

**Comment by KMFDManic** [comment]
The animated border wont work with RetroArch, by the way.  It is part of Canoe coding.  At least for now
